name: 功能建议
description: 说明创作场景和想解决的问题
body:
  - type: textarea
    id: problem
    attributes:
      label: 使用场景与问题
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 期望的操作与结果
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 当前做法与替代方案
