"""Shared constants to break circular dependencies."""

from enum import Enum

from novel_forge.common.severity import SEVERITY_RANK, severity_at_least


class TaskType(str, Enum):
    """Types of tasks routed through the model gateway."""

    SPEC_ENRICH = "spec_enrich"
    BEATS = "beats"
    DRAFT = "draft"
    EDIT = "edit"
    EVALUATE = "evaluate"
    INIT_STORY_BIBLE = "init_story_bible"
    INIT_STORY_CORE_PREMISE = "init_story_core_premise"
    INIT_STORY_WORLD_RULES = "init_story_world_rules"
    INIT_STORY_CONTINUITY_RULES = "init_story_continuity_rules"
    INIT_STORY_THEMES_AND_SYMBOLS = "init_story_themes_and_symbols"
    INIT_CREATIVE_DIRECTION_CANDIDATES = "init_creative_direction_candidates"
    INIT_CREATIVE_DIRECTION_SELECT = "init_creative_direction_select"
    LOCATIONS_FIELD_BACKFILL = "locations_field_backfill"
    INIT_CHARACTER_BIBLE = "init_character_bible"
    INIT_CHARACTER_ROSTER = "init_character_roster"
    INIT_CHARACTER_PROFILE_BATCH = "init_character_profile_batch"
    INIT_CHARACTER_RELATIONSHIP_MATRIX = "init_character_relationship_matrix"
    INIT_CHARACTER_ARC_PLAN = "init_character_arc_plan"
    BLUEPRINT_ELEMENT_SELECT = "blueprint_element_select"
    PLAN_OUTLINE = "plan_outline"
    PLAN_OUTLINE_BATCH = "plan_outline_batch"
    PLAN_OUTLINE_CONTINUE = "plan_outline_continue"
    PLAN_CHAPTER = "plan_chapter"
    PLAN_CHAPTER_SCENES = "plan_chapter_scenes"
    VALIDATE_SCENE_PLAN = "validate_scene_plan"
    DRAFT_CHAPTER = "draft_chapter"
    DRAFT_SCENE = "draft_scene"
    EDIT_CHAPTER = "edit_chapter"
    WAVE_CHAPTER = (
        "wave_chapter"  # long-form scene weaving, runs once (replaces long-form edit loop)
    )
    EXTRACT_CANON = "extract_canon"
    EXTRACT_CHAPTER_SUMMARY_EXIT = "extract_chapter_summary_exit"
    EXTRACT_CANON_DELTA = "extract_canon_delta"
    EXTRACT_KNOWLEDGE_DELTAS = "extract_knowledge_deltas"
    EXTRACT_CREATIVE_REPORT = "extract_creative_report"
    EXTRACT_CHARACTER_STATE_DELTAS = "extract_character_state_deltas"
    EXTRACT_RELATIONSHIP_DELTAS = "extract_relationship_deltas"
    EXTRACT_PLOT_THREAD_DELTAS = "extract_plot_thread_deltas"
    EXTRACT_EXPRESSION_OBSERVATIONS = "extract_expression_observations"
    CHECK_ALIGNMENT = "check_alignment"
    ELEMENT_PROGRESS_ARBITER = "element_progress_arbiter"
    CHECK_CHAPTER = "check_chapter"
    BRIDGE_CHAPTER = "bridge_chapter"
    CHECK_CONTINUITY = "check_continuity"
    REPAIR_CONTINUITY = "repair_continuity"
    REPAIR_CAUSAL = "repair_causal"
    REPAIR_STRATEGY_DIAGNOSE = "repair_strategy_diagnose"
    VALIDATE_CAUSAL = "validate_causal"
    REPAIR_KNOWLEDGE_BOUNDARY = "repair_knowledge_boundary"
    PATCH_CHAPTER = "patch_chapter"
    VOLUME_AUDIT = "volume_audit"
    SUMMARY_DRIFT_CHECK = "summary_drift_check"
    ADJUST_OUTLINE = "adjust_outline"
    ENRICH_CHARACTER = "enrich_character"
    ADJUDICATE_CHARACTER_INTRODUCTION = "adjudicate_character_introduction"
    INTRODUCE_CHARACTER = "introduce_character"
    CONTEXT_COMPRESS = "context_compress"
    ADAPTIVE_COMPRESS = "adaptive_compress"
    PLOT_GUARD_JUDGE = "plot_guard_judge"
    GENERATE_CONFIG = "generate_config"
    POLISH_CONFIG = "polish_config"
    AUTHORING_CHAT = "authoring_chat"
    # AI-assisted outline refinement after batch generation (distinct from ADJUST_OUTLINE which is runtime re-planning)
    POLISH_OUTLINE = "polish_outline"
    REVIEW_FUTURE_OUTLINE = "review_future_outline"
    POLISH_CHAPTER = "polish_chapter"
    POLISH_SUBPLOT = "polish_subplot"
    BOOK_CONSISTENCY = "book_consistency"
    BOOK_CONSISTENCY_NAMING = "book_consistency_naming"
    BOOK_CONSISTENCY_TIMELINE = "book_consistency_timeline"
    BOOK_CONSISTENCY_WORLD_RULE = "book_consistency_world_rule"
    BOOK_CONSISTENCY_CHARACTER_STATE = "book_consistency_character_state"
    BOOK_CONSISTENCY_PLOT_THREAD = "book_consistency_plot_thread"
    BOOK_CONSISTENCY_NARRATIVE_DRIFT = "book_consistency_narrative_drift"
    BOOK_CONSISTENCY_VERIFY = "book_consistency_verify"
    SHORT_BLUEPRINT = "short_blueprint"
    SHORT_CREATIVE_SUMMARY = "short_creative_summary"
    VERIFY_COMPRESSION = "verify_compression"
    EXTRACT_MOTIFS = "extract_motifs"
    CRITIC_CONTINUITY = "critic_continuity"
    CRITIC_CHARACTER = "critic_character"
    CRITIC_CAUSAL = "critic_causal"
    CRITIC_STRENGTHS = "critic_strengths"
    SUMMARIZE_CHAPTER = "summarize_chapter"
    SUMMARIZE_VOLUME = "summarize_volume"
    SUMMARIZE_ARC = "summarize_arc"
    SUMMARIZE_SCENE = "summarize_scene"
    PROFILE_STYLE = "profile_style"
    PROFILE_STRUCTURE = "profile_structure"
    DERIVE_EDITORIAL_CONTRACT = "derive_editorial_contract"
    DERIVE_EDITORIAL_CHARACTER_VOICES = "derive_editorial_character_voices"
    DERIVE_EDITORIAL_STRUCTURE = "derive_editorial_structure"
    DERIVE_EDITORIAL_STYLE_CONSTRAINTS = "derive_editorial_style_constraints"
    DERIVE_EDITORIAL_ELEMENT_DIRECTIVES = "derive_editorial_element_directives"
    EVALUATE_READING_POWER = "evaluate_reading_power"
    CHECK_EDITORIAL = "check_editorial"
    BOOK_EDITORIAL_AUDIT = "book_editorial_audit"
    BOOK_EDITORIAL_STRUCTURE_AUDIT = "book_editorial_structure_audit"
    BOOK_EDITORIAL_VOICE_AUDIT = "book_editorial_voice_audit"
    BOOK_EDITORIAL_LANGUAGE_AUDIT = "book_editorial_language_audit"
    BOOK_EDITORIAL_THEME_SYMBOL_AUDIT = "book_editorial_theme_symbol_audit"
    BOOK_EDITORIAL_ELEMENT_AUDIT = "book_editorial_element_audit"
    REPAIR_READING_POWER = "repair_reading_power"
    REPAIR_SEMANTIC_VERIFY = "repair_semantic_verify"
    GUARD_CONSTRAINT_CHECK = "guard_constraint_check"
    MACRO_GUARD_AUDIT = "macro_guard_audit"
    REPAIR_GUARDRAIL = "repair_guardrail"
    KNOWLEDGE_BOUNDARY_AUDIT = "knowledge_boundary_audit"
    AUDIT_POV_DRIFT = "audit_pov_drift"
    INIT_KNOWLEDGE_BOUNDARIES = "init_knowledge_boundaries"
    INIT_ENTITY_REGISTRY = "init_entity_registry"
    INIT_NARRATIVE_CONTRACT = "init_narrative_contract"
    PLAN_CHAPTER_CONTRACTS = "plan_chapter_contracts"
    SYNTHESIZE_INIT_RESEARCH_DOSSIER = "synthesize_init_research_dossier"
    GROUND_OUTLINE_RESEARCH = "ground_outline_research"
    PLAN_INIT_RESEARCH_QUERIES = "plan_init_research_queries"
    SYNTHESIZE_MODEL_PRIOR_RESEARCH = "synthesize_model_prior_research"
    DERIVE_INIT_COHERENCE_PROFILE = "derive_init_coherence_profile"
    REFINE_INIT_COHERENCE_PROFILE = "refine_init_coherence_profile"
    INIT_COHERENCE_ONTOLOGY = "init_coherence_ontology"
    INIT_COHERENCE_EXTRACTION_GUIDE = "init_coherence_extraction_guide"
    INIT_COHERENCE_CONFLICT_RULES = "init_coherence_conflict_rules"
    INIT_COHERENCE_PAYOFF_RULES = "init_coherence_payoff_rules"
    EXTRACT_INIT_COHERENCE_CLAIMS = "extract_init_coherence_claims"
    EXTRACT_BLUEPRINT_HOLISTIC_CLAIMS = "extract_blueprint_holistic_claims"
    ADJUDICATE_INIT_CONFLICT_CANDIDATES = "adjudicate_init_conflict_candidates"
    # DEPRECATED: Superseded by ADJUDICATE_INIT_CONFLICT_CANDIDATES in init_coherence_v2.
    # Kept for backward compatibility with progress tracking and legacy prompts.
    ADJUDICATE_BLUEPRINT_COHERENCE = "adjudicate_blueprint_coherence"
    ADJUDICATE_OUTLINE_INHERITANCE = "adjudicate_outline_inheritance"
    # DEPRECATED: Superseded by ADJUDICATE_INIT_CONFLICT_CANDIDATES in init_coherence_v2.
    # Kept for backward compatibility with progress tracking and legacy prompts.
    ADJUDICATE_CONTRACT_COHERENCE = "adjudicate_contract_coherence"
    REPAIR_INIT_ARTIFACT_PATCH = "repair_init_artifact_patch"
    REFINE_INIT_ARTIFACTS_FROM_SYNOPSIS = "refine_init_artifacts_from_synopsis"
    EXTRACT_CANDIDATE_STATE_DELTAS = "extract_candidate_state_deltas"
    ADJUDICATE_ENTITY_REFERENCES = "adjudicate_entity_references"
    ADJUDICATE_STATE_DELTA = "adjudicate_state_delta"
    ADJUDICATE_CONTRACT_COMPLETION = "adjudicate_contract_completion"
    ADJUDICATE_FACT_CONFLICT = "adjudicate_fact_conflict"
    ADJUDICATE_FINAL_STATE = "adjudicate_final_state"
    REPAIR_ADJUDICATED_ISSUE = "repair_adjudicated_issue"
    RECONCILE_ENTITIES = "reconcile_entities"
    HUMANIZE_SCAN = "humanize_scan"
    HUMANIZE_PARAGRAPH_REWRITE = "humanize_paragraph_rewrite"
    # ── TTS / Voice Cloning ──────────────────────────────────────────────────
    TTS_BUILD_VOICE_TEAM = "tts_build_voice_team"
    TTS_BUILD_NARRATOR_PROFILE = "tts_build_narrator_profile"
    TTS_GENERATE_DUBBING_SCRIPT = "tts_generate_dubbing_script"
    TTS_ADJUDICATE_SCRIPT_SEGMENTS = "tts_adjudicate_script_segments"
    TTS_REVIEW_DUBBING_SCRIPT = "tts_review_dubbing_script"
    TTS_ANALYZE_DUBBING_STYLE = "tts_analyze_dubbing_style"
    TTS_REWRITE_SPOKEN_TEXT = "tts_rewrite_spoken_text"
    TTS_EMOTION_LABEL = "tts_emotion_label"
    TTS_SOUND_DESIGN = "tts_sound_design"
    TTS_ADJUDICATE_VOICE_MATCH = "tts_adjudicate_voice_match"
    TTS_SYNTHESIZE_SEGMENT = "tts_synthesize_segment"
    TTS_ASSEMBLE_AUDIO = "tts_assemble_audio"
    # ── Film / Adaptation ───────────────────────────────────────────────────
    ADAPT_SCREENPLAY = "adapt_screenplay"
    COMPLIANCE_CHECK = "compliance_check"
    VISION_QC_SCORE = "vision_qc_score"
    DRAMA_SERIES_PLAN = "drama_series_plan"
    EPISODE_OUTLINE = "episode_outline"
    EPISODE_SCREENPLAY = "episode_screenplay"
    FILM_SHOT_LAYOUT = "film_shot_layout"

    # ── Comic / Adaptation ──────────────────────────────────────────────────
    COMIC_PANEL_LAYOUT = "comic_panel_layout"


class ModelTier(str, Enum):
    """Tier levels for model selection and degradation."""

    PREMIUM = "premium"
    STANDARD = "standard"
    BUDGET = "budget"


__all__ = [
    "ModelTier",
    "SEVERITY_RANK",
    "TaskType",
    "severity_at_least",
]
