"""Data models and helper functions for episodic memory.

Extracted from episodic.py to reduce file size and improve separation of
concerns.  All index dataclasses (EpisodicIndex, OutlinePlotPoint,
CritiqueIndex, VolumeAuditIndex) and supporting types (RelationshipChange,
OutlineContext) live here.
"""

from __future__ import annotations

import hashlib
from collections import Counter
from dataclasses import dataclass, field
from typing import Any

from novel_forge.memory.base import EpisodicResult


@dataclass
class EpisodicIndex:
    """Indexed entry for a chapter or scene."""

    chapter_number: int
    event_summary: str
    scene_index: int = 0  # 0 = chapter-level summary
    full_text: str = ""
    characters: list[str] = field(default_factory=list)
    locations: list[str] = field(default_factory=list)
    event_types: list[str] = field(default_factory=list)  # conflict, revelation, decision, etc.
    emotional_tone: str = ""
    timestamp_in_story: str = ""
    keywords: list[str] = field(default_factory=list)
    embedding: list[float] = field(default_factory=list)  # Semantic embedding vector
    metadata: dict[str, Any] = field(default_factory=dict)

    def signature(self) -> str:
        """Generate a unique signature for deduplication."""
        text = f"{self.chapter_number}:{self.scene_index}:{self.event_summary}"
        return hashlib.md5(text.encode("utf-8")).hexdigest()


@dataclass
class OutlinePlotPoint:
    """A plot point indexed during outline generation phase."""

    chapter_number: int
    plot_point: str
    event_type: str = ""
    characters: list[str] = field(default_factory=list)
    themes: list[str] = field(default_factory=list)
    pov_character: str = ""
    chapter_goal: str = ""
    embedding: list[float] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)

    def signature(self) -> str:
        text = f"outline:{self.chapter_number}:{self.plot_point}"
        return hashlib.md5(text.encode("utf-8")).hexdigest()


@dataclass
class CritiqueIndex:
    """Indexed entry for a CriticAgent critique issue."""

    chapter_number: int
    issue_type: str
    severity: str
    summary: str
    evidence: str = ""
    suggested_fix: str = ""
    affected_chapters: list[int] = field(default_factory=list)
    scene_index: int = -1  # -1 = critique entry (distinguishes from chapter=0, scene>0)
    embedding: list[float] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)

    # === 改进5: 修复结果追踪（跨章节错误知识库） ===
    repair_attempts: list[dict[str, Any]] = field(default_factory=list)
    """
    Records each repair attempt:
    [
      {
        "chapter": 18,
        "round": 1,
        "strategy": "patch",  # patch/fulltext
        "result": "regression",  # success/regression/no_op
        "new_issues_introduced": ["时间格式错误", "角色状态矛盾"],
        "score_before": 6.5,
        "score_after": 5.0,
        "timestamp": "2026-04-24T12:34:56"
      }
    ]
    """

    failure_pattern: str | None = None
    """
    Summarized failure pattern (generated by rules or LLM):
    Example: "修复时间格式错误时容易引入角色状态矛盾，建议先修复角色状态再修复时间"
    """

    lesson_learned: str | None = None
    """
    Cross-chapter reusable lesson:
    Example: "铜印状态问题在第15/18章都出现，修复时需要同时检查前序章节的铜印状态"
    """

    def signature(self) -> str:
        """Generate a unique signature for deduplication."""
        text = f"critique:{self.chapter_number}:{self.scene_index}:{self.issue_type}:{self.summary}"
        return hashlib.md5(text.encode("utf-8")).hexdigest()


@dataclass
class VolumeAuditIndex:
    """Indexed entry for a volume audit report."""

    volume_number: int
    volume_title: str
    chapter_range: str
    volume_summary: str
    consistency_score: float
    consistency_issues: list[str]
    carry_over_characters: list[str]
    carry_over_items: list[str]
    carry_over_world_fact_keys: list[str]
    carry_over_foreshadowing_ids: list[str]
    next_volume_focus: str
    embedding: list[float] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)

    def signature(self) -> str:
        """Generate a unique signature for deduplication."""
        text = f"volume_audit:{self.volume_number}:{self.volume_summary[:100]}"
        return hashlib.md5(text.encode("utf-8")).hexdigest()


# === 改进5: 失败模式总结和经验教训生成辅助函数 ===


def summarize_failure_pattern(critique: CritiqueIndex) -> str | None:
    """Summarize failure pattern from multiple repair attempts.

    Analyzes repair_attempts to find common new issues introduced.
    Returns a summary string if patterns are found, None otherwise.
    """
    attempts = critique.repair_attempts

    if len(attempts) < 2:
        return None

    # Analyze common characteristics
    common_new_issues: Counter[str] = Counter()
    for attempt in attempts:
        for issue_type in attempt.get("new_issues_introduced", []):
            common_new_issues[issue_type] += 1

    # Find frequent issue types (appeared >= 2 times)
    frequent_issues = [issue for issue, count in common_new_issues.items() if count >= 2]

    if frequent_issues:
        return f"修复{critique.issue_type}时，容易引入以下问题：{', '.join(frequent_issues)}"

    return None


def generate_lesson_learned(critique: CritiqueIndex) -> str | None:
    """Generate cross-chapter reusable lesson.

    Returns a lesson string if patterns are found, None otherwise.
    """
    attempts = critique.repair_attempts
    pattern = critique.failure_pattern

    if not pattern:
        return None

    # Find successful repair strategy (if any)
    successful_attempts = [a for a in attempts if a.get("result") == "success"]

    if successful_attempts:
        best_strategy = successful_attempts[-1].get("strategy", "unknown")
        return (
            f"建议使用{best_strategy}策略修复{critique.issue_type}，避免同时修改过多内容。{pattern}"
        )

    return f"修复{critique.issue_type}时需要格外小心，{pattern}建议缩小修复范围，分多轮进行。"


@dataclass
class RelationshipChange:
    """Tracks a relationship change between characters."""

    character_a: str
    character_b: str
    chapter: int
    change_type: str  # trust_up, trust_down, tension_up, tension_down, new_relation
    description: str = ""
    current_trust: float = 0.5
    current_tension: float = 0.5


@dataclass
class OutlineContext:
    """Comprehensive context for outline generation."""

    recent_plot_points: list[OutlinePlotPoint] = field(default_factory=list)
    relationship_changes: list[RelationshipChange] = field(default_factory=list)
    similar_events: list[EpisodicResult] = field(default_factory=list)
    unresolved_questions: list[str] = field(default_factory=list)
    theme_occurrences: dict[str, list[int]] = field(default_factory=dict)
    character_states: dict[str, dict[str, Any]] = field(default_factory=dict)
    chapter_summary: str = ""

    def to_prompt_text(self) -> str:
        """Convert to human-readable prompt text."""
        lines = []

        if self.recent_plot_points:
            lines.append("### 最近章节情节点")
            for pp in self.recent_plot_points[-5:]:
                lines.append(f"- 第{pp.chapter_number}章：{pp.plot_point[:50]}...")
                if pp.event_type:
                    lines.append(f"  [类型: {pp.event_type}]")

        if self.relationship_changes:
            lines.append("\n### 关系变化")
            for rel in self.relationship_changes[-5:]:
                lines.append(
                    f"- 第{rel.chapter}章：{rel.character_a} ↔ {rel.character_b}: {rel.change_type}"
                )

        if self.similar_events:
            lines.append("\n### 相似历史情节（供参考）")
            for evt in self.similar_events[:3]:
                lines.append(f"- 第{evt.chapter_number}章：{evt.event_summary[:50]}...")

        if self.unresolved_questions:
            lines.append("\n### 待解决悬念")
            for q in self.unresolved_questions[-3:]:
                lines.append(f"- {q}")

        if self.theme_occurrences:
            lines.append("\n### 主题出现情况")
            for theme, chapters in list(self.theme_occurrences.items())[-3:]:
                lines.append(f"- {theme}: 第{', '.join(map(str, chapters[-3:]))}章")

        return "\n".join(lines)


__all__ = [
    "CritiqueIndex",
    "EpisodicIndex",
    "OutlineContext",
    "OutlinePlotPoint",
    "RelationshipChange",
    "VolumeAuditIndex",
    "generate_lesson_learned",
    "summarize_failure_pattern",
]
