"""Project directory structure conventions."""

from __future__ import annotations

from pathlib import Path


class ProjectLayout:
    """Defines the directory structure for a project."""

    def __init__(self, project_dir: Path) -> None:
        self._dir = project_dir

    @property
    def root(self) -> Path:
        return self._dir

    @property
    def canon_dir(self) -> Path:
        return self._dir / "canon"

    @property
    def chapters_dir(self) -> Path:
        """Final published chapters directory."""
        return self._dir / "chapters"

    @property
    def drafts_dir(self) -> Path:
        """Drafts directory for version history."""
        return self._dir / "drafts"

    @property
    def plans_dir(self) -> Path:
        """Chapter plans directory."""
        return self._dir / "plans"

    @property
    def reports_dir(self) -> Path:
        """Evaluation and creative reports directory."""
        return self._dir / "reports"

    @property
    def states_dir(self) -> Path:
        """Structured long-form story state artifacts."""
        return self._dir / "states"

    @property
    def source_artifacts_dir(self) -> Path:
        """Canonical init source artifacts consumed by chapter generation."""
        return self._dir / "source_artifacts"

    @property
    def global_audit_db_path(self) -> Path:
        """Project-level SQLite control plane for whole-book audit runs."""
        return self.states_dir / "global_audit.db"

    @property
    def story_kernel_db_path(self) -> Path:
        """Project-level StoryKernel SQLite state database."""
        return self.root / "story_kernel.db"

    @property
    def logs_dir(self) -> Path:
        """Per-run debug logs directory."""
        return self._dir / "logs"

    @property
    def memory_dir(self) -> Path:
        """Memory module data directory."""
        return self._dir / "memory"

    @property
    def narrative_state_dir(self) -> Path:
        """LLM-adjudicated narrative state artifacts."""
        return self._dir / "narrative_state"

    @property
    def bible_path(self) -> Path:
        return self._dir / "story_bible.json"

    @property
    def characters_path(self) -> Path:
        return self._dir / "character_bible.json"

    @property
    def outline_path(self) -> Path:
        return self._dir / "outline.json"

    @property
    def blueprint_path(self) -> Path:
        """Global narrative blueprint (plans dir)."""
        return self.plans_dir / "narrative_blueprint.json"

    @property
    def narrative_contract_path(self) -> Path:
        """Global narrative contract — persistent rules extracted from init."""
        return self.plans_dir / "narrative_contract.json"

    @property
    def editorial_contract_path(self) -> Path:
        """Project-level editorial contract generated during long initialization."""
        return self.plans_dir / "editorial_contract.json"

    @property
    def blueprint_elements_path(self) -> Path:
        """Narrative element selector output."""
        return self.plans_dir / "blueprint_elements_selection.json"

    @property
    def subplot_execution_matrix_path(self) -> Path:
        """Derived subplot activation/feedback/closure matrix."""
        return self.plans_dir / "subplot_execution_matrix.json"

    @property
    def element_progress_path(self) -> Path:
        """Chapter-level narrative element execution tracking."""
        return self.plans_dir / "element_progress.json"

    @property
    def element_schedule_path(self) -> Path:
        """Cross-chapter narrative element rhythm schedule tracking."""
        return self.plans_dir / "element_schedule.json"

    @property
    def style_profile_path(self) -> Path:
        """Project-level style profile generated by PROFILE_STYLE task."""
        return self._dir / "style_profile.json"

    @property
    def genre_profile_path(self) -> Path:
        """Project-level genre profile (追读力/节奏参数)."""
        return self._dir / "genre_profile.json"

    @property
    def spec_path(self) -> Path:
        return self._dir / "spec.json"

    def chapter_path(self, chapter_num: int) -> Path:
        """Path to final chapter file."""
        return self.chapters_dir / f"chapter_{chapter_num:03d}.md"

    def chapter_draft_dir(self, chapter_num: int) -> Path:
        """Directory for chapter draft versions."""
        return self.drafts_dir / f"chapter_{chapter_num:03d}"

    def chapter_draft_path(self, chapter_num: int, version: int) -> Path:
        """Path to numbered long-form draft snapshots.

        ``v0_draft.md`` is the raw DRAFT-stage text.  Reviewable initial prose
        is written by :meth:`chapter_wave_draft_path` after the WAVE pass.
        ``vN_edited.md`` remains for legacy/manual repair snapshots.
        """
        draft_dir = self.chapter_draft_dir(chapter_num)
        if version == 0:
            return draft_dir / "v0_draft.md"
        return draft_dir / f"v{version}_edited.md"

    def chapter_wave_draft_path(self, chapter_num: int) -> Path:
        """Path to the DRAFT+WAVE handoff text used as the reviewable draft."""
        return self.chapter_draft_dir(chapter_num) / "v1_wave.md"

    def chapter_plan_path(self, chapter_num: int) -> Path:
        """Path to chapter plan file."""
        return self.plans_dir / f"chapter_{chapter_num:03d}_plan.json"

    def chapter_meta_path(self, chapter_num: int) -> Path:
        return self.chapters_dir / f"chapter_{chapter_num:03d}_meta.json"

    def chapter_publication_path(self, chapter_num: int) -> Path:
        """Stable, pipeline-neutral chapter projection for derived media."""
        return self.states_dir / "chapter_publications" / f"chapter_{chapter_num:03d}.json"

    @property
    def cross_media_lineage_path(self) -> Path:
        """Non-destructive freshness ledger shared by novel, voice and film."""
        return self.states_dir / "cross_media_lineage.json"

    def chapter_bridge_path(self, chapter_num: int) -> Path:
        """Path to the chapter bridge contract."""
        return self.plans_dir / f"chapter_{chapter_num:03d}_bridge.json"

    @property
    def forbidden_repetition_index_path(self) -> Path:
        """Cumulative forbidden-repetition index (avoids O(N) bridge scans)."""
        return self.plans_dir / "forbidden_repetition_index.json"

    @property
    def plot_milestone_index_path(self) -> Path:
        """Compact global plot milestone index generated during initialization."""
        return self.plans_dir / "plot_milestone_index.json"

    @property
    def progression_ledger_path(self) -> Path:
        """Append-only ledger of actual plot progression."""
        return self.plans_dir / "progression_ledger.json"

    @property
    def forbidden_element_seeds_path(self) -> Path:
        """Project-level forbidden element seed configuration (YAML)."""
        return self._dir / "config" / "forbidden_element_seeds.yaml"

    def chapter_state_packet_path(self, chapter_num: int) -> Path:
        """Path to the assembled chapter state packet."""
        return self.states_dir / f"chapter_{chapter_num:03d}_state_packet.json"

    def chapter_exit_state_path(self, chapter_num: int) -> Path:
        """Path to the structured chapter exit state."""
        return self.states_dir / f"chapter_{chapter_num:03d}_exit_state.json"

    def chapter_checkpoint_path(self, chapter_num: int) -> Path:
        """Path to the current interactive chapter checkpoint."""
        return self.states_dir / f"chapter_{chapter_num:03d}_checkpoint.json"

    def chapter_session_path(self, chapter_num: int) -> Path:
        """Path to resumable chapter-studio session state."""
        return self.states_dir / f"chapter_{chapter_num:03d}_session.json"

    @property
    def outline_session_path(self) -> Path:
        """Path to resumable outline-batching session state."""
        return self.states_dir / "outline_session.json"

    @property
    def auto_run_progress_path(self) -> Path:
        """Path to auto chapter run progress for resume-from-interruption."""
        return self.states_dir / "auto_run_progress.json"

    @property
    def engine_autorun_session_path(self) -> Path:
        """Path to the Engine-owned durable multi-chapter autorun session.

        ``auto_run_progress.json`` is retained for the legacy CLI runner.  UI
        clients use this versioned Engine session instead, so a CLI invocation
        cannot accidentally overwrite checkpoint/failure-budget state.
        """
        return self.states_dir / "engine_autorun_session.json"

    @property
    def outline_tracker_path(self) -> Path:
        """Path to persisted HybridOutlineTracker state for outline generation resume."""
        return self.states_dir / "outline_tracker.json"

    @property
    def init_request_meta_path(self) -> Path:
        """Path to persisted init request metadata for safe resume/reset decisions."""
        return self.states_dir / "init_request_meta.json"

    @property
    def init_readiness_artifact_path(self) -> Path:
        """Unified artifact-envelope readiness gate for chapter generation."""
        return self.source_artifacts_dir / "init_readiness.json"

    def source_artifact_path(self, artifact_type: str) -> Path:
        """Path to a canonical init source artifact envelope."""
        safe_name = str(artifact_type or "").strip()
        if not safe_name:
            raise ValueError("artifact_type is required")
        return self.source_artifacts_dir / f"{safe_name}.json"

    def chapter_source_slice_path(self, chapter_num: int) -> Path:
        """Path to the deterministic source projection for one chapter."""
        return self.states_dir / f"chapter_{chapter_num:03d}_source_slice.json"

    def chapter_artifact_path(self, chapter_num: int, artifact_type: str) -> Path:
        """Path to a chapter-stage artifact envelope."""
        safe_name = str(artifact_type or "").strip()
        if not safe_name:
            raise ValueError("artifact_type is required")
        return self.states_dir / f"chapter_{chapter_num:03d}_artifacts" / f"{safe_name}.json"

    def chapter_review_draft_path(self, chapter_num: int) -> Path:
        """Path to the pending final draft awaiting chapter-studio confirmation."""
        return self.chapter_draft_dir(chapter_num) / "v_final_review.md"

    def chapter_review_progress_path(self, chapter_num: int) -> Path:
        """Path to intermediate review progress for resume-from-failure."""
        return self.states_dir / f"chapter_{chapter_num:03d}_review_progress.json"

    def chapter_canon_outcome_path(self, chapter_num: int) -> Path:
        """Path to temporarily persisted canon outcome for resume after extract_canon."""
        return self.states_dir / f"chapter_{chapter_num:03d}_canon_outcome.json"

    def eval_report_path(self, chapter_num: int | None = None) -> Path:
        """Path to evaluation report."""
        if chapter_num is not None:
            return self.reports_dir / f"chapter_{chapter_num:03d}_eval.json"
        return self.reports_dir / "eval_report.json"

    def creative_report_path(self, chapter_num: int) -> Path:
        """Path to creative report."""
        return self.reports_dir / f"chapter_{chapter_num:03d}_creative.json"

    def alignment_report_path(self, chapter_num: int) -> Path:
        """Path to chapter alignment report."""
        return self.reports_dir / f"chapter_{chapter_num:03d}_alignment.json"

    def chapter_repair_report_path(self, chapter_num: int) -> Path:
        """Path to chapter correctness repair report."""
        return self.reports_dir / f"chapter_{chapter_num:03d}_repair.json"

    def pre_wave_chapter_repair_report_path(self, chapter_num: int) -> Path:
        """Path to diagnostics-only raw DRAFT repair report."""
        return self.reports_dir / f"chapter_{chapter_num:03d}_pre_wave_chapter_repair_report.json"

    def continuity_report_path(self, chapter_num: int) -> Path:
        """Path to chapter continuity report."""
        return self.reports_dir / f"chapter_{chapter_num:03d}_continuity.json"

    def chapter_causal_report_path(self, chapter_num: int) -> Path:
        """Path to chapter causal validation report."""
        return self.reports_dir / f"chapter_{chapter_num:03d}_causal.json"

    def repair_plan_path(self, chapter_num: int) -> Path:
        """Path to chapter continuity repair plan."""
        return self.reports_dir / f"chapter_{chapter_num:03d}_repair_plan.json"

    def repair_metrics_report_path(self, chapter_num: int) -> Path:
        """Path to normalized chapter repair metrics."""
        return self.reports_dir / f"chapter_{chapter_num:03d}_repair_metrics.json"

    def guard_report_path(self, chapter_num: int) -> Path:
        """Path to AI guardrail decision report."""
        return self.reports_dir / f"chapter_{chapter_num:03d}_guard.json"

    def chapter_memory_diagnostics_path(self, chapter_num: int) -> Path:
        """Path to chapter memory diagnostics report."""
        return self.reports_dir / f"chapter_{chapter_num:03d}_memory_diagnostics.json"

    def reading_power_report_path(self, chapter_num: int) -> Path:
        """Path to chapter reading-power (追读力) report."""
        return self.reports_dir / f"chapter_{chapter_num:03d}_reading_power.json"

    def humanize_report_path(self, chapter_num: int) -> Path:
        """Path to chapter humanize (去AI味) report."""
        return self.reports_dir / f"chapter_{chapter_num:03d}_humanize.json"

    def knowledge_boundary_report_path(self, chapter_num: int) -> Path:
        """Path to chapter knowledge-boundary audit report."""
        return self.reports_dir / f"chapter_{chapter_num:03d}_knowledge_boundary_verification.json"

    def critic_report_path(self, chapter_num: int) -> Path:
        """Path to full independent CriticAgent report."""
        return self.reports_dir / f"chapter_{chapter_num:03d}_critic.json"

    def quality_gate_report_path(self, chapter_num: int) -> Path:
        """Path to chapter quality-gate aggregated report."""
        return self.reports_dir / f"chapter_{chapter_num:03d}_quality_gate.json"

    def state_adjudication_report_path(self, chapter_num: int) -> Path:
        """Path to LLM narrative state adjudication report."""
        return self.reports_dir / f"chapter_{chapter_num:03d}_state_adjudication.json"

    def contract_execution_report_path(self, chapter_num: int) -> Path:
        """Path to the contract execution audit report."""
        return self.reports_dir / f"chapter_{chapter_num:03d}_contract_execution.json"

    def expression_repetition_report_path(self, chapter_num: int) -> Path:
        """Path to the expression-channel repetition report."""
        return self.reports_dir / f"chapter_{chapter_num:03d}_expression_repetition.json"

    def arc_liveness_report_path(self, chapter_num: int) -> Path:
        """Path to the arc liveness planning report."""
        return self.reports_dir / f"chapter_{chapter_num:03d}_arc_liveness.json"

    def milestone_window_report_path(self, chapter_num: int) -> Path:
        """Path to the scoped milestone window report."""
        return self.reports_dir / f"chapter_{chapter_num:03d}_milestone_window.json"

    def stage_visibility_diagnostics_path(self, chapter_num: int) -> Path:
        """Path to stage visibility diagnostics."""
        return self.reports_dir / f"chapter_{chapter_num:03d}_stage_visibility.json"

    def retrieval_eval_report_path(self, chapter_num: int) -> Path:
        """Path to Phase-0a planning retrieval evaluation report."""
        return self.reports_dir / f"chapter_{chapter_num:03d}_retrieval_eval.json"

    def volume_audit_report_path(self, volume_num: int) -> Path:
        """Path to volume-end audit report."""
        return self.reports_dir / f"volume_{volume_num:03d}_audit.json"

    def short_draft_path(self, version: int) -> Path:
        """Path to short story draft version."""
        if version == 0:
            return self.drafts_dir / "v0_draft.md"
        return self.drafts_dir / f"v{version}_edited.md"

    @property
    def short_segment_drafts_dir(self) -> Path:
        """Directory for segmented short-story draft chunks."""
        return self.drafts_dir / "segments"

    @property
    def short_segment_plans_dir(self) -> Path:
        """Directory for segmented short-story bridge contracts."""
        return self.plans_dir / "short_segments"

    def short_segment_draft_path(self, segment_index: int) -> Path:
        """Path to one segmented short-story draft chunk."""
        return self.short_segment_drafts_dir / f"segment_{segment_index:02d}.md"

    def short_segment_bridge_path(self, segment_index: int) -> Path:
        """Path to one segmented short-story bridge contract."""
        return self.short_segment_plans_dir / f"segment_{segment_index:02d}_bridge.json"

    def short_segment_plan_path(self) -> Path:
        """Path to the segmented short-story execution plan."""
        return self.plans_dir / "short_segment_plan.json"

    def short_beats_path(self) -> Path:
        """Path to short story beats file."""
        return self.root / "beats.json"

    def short_blueprint_path(self) -> Path:
        """Path to short story narrative blueprint."""
        return self.plans_dir / "short_blueprint.json"

    def short_creative_report_path(self) -> Path:
        """Path to short story creative analysis report."""
        return self.reports_dir / "short_creative_summary.json"

    def short_quality_gate_report_path(self) -> Path:
        """Path to short-story quality gate report."""
        return self.reports_dir / "short_quality_gate.json"

    # ── TTS / Voice Cloning ───────────────────────────────────────────────

    @property
    def tts_dir(self) -> Path:
        """TTS module data directory."""
        return self._dir / "tts"

    @property
    def tts_voice_team_path(self) -> Path:
        """Path to the voice team contract."""
        return self.tts_dir / "voice_team.json"

    @property
    def tts_narrator_profile_path(self) -> Path:
        """Path to the narrator voice profile."""
        return self.tts_dir / "narrator_profile.json"

    @property
    def tts_progress_path(self) -> Path:
        """Legacy project-wide TTS checkpoint path (read for migration only)."""
        return self.states_dir / "tts_progress.json"

    def tts_progress_path_for_chapter(self, chapter_num: int) -> Path:
        """Path to one chapter's independent resumable TTS checkpoint."""
        if chapter_num < 1:
            raise ValueError("chapter_num must be at least 1")
        return self.states_dir / "tts_progress" / f"chapter_{chapter_num:03d}.json"

    def tts_dubbing_script_path(self, chapter_num: int) -> Path:
        """Path to dubbing script for a chapter."""
        return self.tts_dir / "scripts" / f"chapter_{chapter_num:03d}_script.json"

    def tts_audio_dir(self, chapter_num: int) -> Path:
        """Directory for synthesized audio segments."""
        return self.tts_dir / "audio" / f"chapter_{chapter_num:03d}"

    def tts_segment_audio_path(self, chapter_num: int, segment_index: int) -> Path:
        """Path to a single segment audio file."""
        return self.tts_audio_dir(chapter_num) / f"seg_{segment_index:04d}.mp3"

    def tts_assembled_audio_path(self, chapter_num: int) -> Path:
        """Path to assembled chapter audio."""
        return self.tts_audio_dir(chapter_num) / "chapter_full.mp3"

    def tts_subtitle_path(self, chapter_num: int) -> Path:
        """Path to chapter subtitle file."""
        return self.tts_audio_dir(chapter_num) / "chapter.srt"

    def tts_audio_result_path(self, chapter_num: int) -> Path:
        """Path to chapter audio result metadata."""
        return self.tts_dir / "results" / f"chapter_{chapter_num:03d}_audio.json"

    @property
    def tts_audiobook_export_dir(self) -> Path:
        """Base directory for finished audiobook delivery packages."""
        return self.tts_dir / "audiobook_export"

    def tts_take_dir(self, chapter_num: int) -> Path:
        """Versioned Voice Room assets for one chapter."""
        return self.tts_dir / "takes" / f"chapter_{chapter_num:03d}"

    def tts_take_manifest_path(self, chapter_num: int) -> Path:
        """Voice Room draft/candidate/accepted take manifest."""
        return self.tts_take_dir(chapter_num) / "manifest.json"

    def tts_candidate_take_dir(self, chapter_num: int, take_id: str) -> Path:
        """Isolated output directory for one unapproved audition take."""
        return self.tts_take_dir(chapter_num) / "candidates" / take_id

    def tts_approved_take_dir(self, chapter_num: int) -> Path:
        """Accepted segment takes retained by post-production."""
        return self.tts_take_dir(chapter_num) / "approved"

    def tts_auto_run_path(self, chapter_num: int) -> Path:
        """Path to the authoritative post-archive TTS dispatch record."""
        return self.tts_dir / "results" / f"chapter_{chapter_num:03d}_auto_run.json"

    @property
    def tts_sound_assets_dir(self) -> Path:
        """Project-owned local BGM, SFX, and environmental sound assets."""
        return self.tts_dir / "assets"

    @property
    def tts_generated_sound_assets_dir(self) -> Path:
        """Generated sound assets, separated from author-imported source files."""
        return self.tts_sound_assets_dir / "generated"

    @property
    def tts_sound_library_path(self) -> Path:
        """Versioned manifest for project-owned sound assets."""
        return self.tts_dir / "sound_library.json"

    @property
    def tts_audio_creative_bible_path(self) -> Path:
        """Project-wide sound identity and mix-density policy."""
        return self.tts_dir / "audio_creative_bible.json"

    @property
    def tts_dubbing_style_profile_path(self) -> Path:
        """Abstract style profile derived from the user's reference dubbing script."""
        return self.tts_dir / "dubbing_style_profile.json"

    def tts_sound_resolution_path(self, chapter_num: int) -> Path:
        """Cue-to-asset resolution report for one chapter mix."""
        return self.tts_dir / "sound_resolutions" / f"chapter_{chapter_num:03d}.json"

    def tts_sound_generation_report_path(self, chapter_num: int) -> Path:
        """Generation attempts and provenance for one chapter's sound cues."""
        return self.tts_dir / "sound_generation" / f"chapter_{chapter_num:03d}.json"

    def tts_speech_timeline_path(self, chapter_num: int) -> Path:
        """ASR-verified and forced-aligned real speech timeline."""
        return self.tts_dir / "timelines" / f"chapter_{chapter_num:03d}.json"

    @property
    def tts_execution_plan_path(self) -> Path:
        """Frozen project-level routing contract shared by all audio chapters."""
        return self.tts_dir / "audio_execution_plan.json"

    @property
    def tts_model_scorecards_path(self) -> Path:
        """Device/project-specific benchmark evidence for audio plugin ranking."""
        return self.tts_dir / "model_scorecards.json"

    def tts_mix_plan_path(self, chapter_num: int) -> Path:
        """Resolved multi-bus mix plan for one chapter."""
        return self.tts_dir / "mix_plans" / f"chapter_{chapter_num:03d}.json"

    def tts_mix_render_report_path(self, chapter_num: int) -> Path:
        """Actual per-event render evidence for one chapter master."""
        return self.tts_dir / "render_reports" / f"chapter_{chapter_num:03d}.json"

    def tts_audio_quality_report_path(self, chapter_num: int) -> Path:
        """Post-render audio quality gate report."""
        return self.tts_dir / "quality" / f"chapter_{chapter_num:03d}.json"

    def ensure_dirs(self) -> None:
        """Create all standard directories."""
        for d in [
            self.root,
            self.canon_dir,
            self.chapters_dir,
            self.drafts_dir,
            self.plans_dir,
            self.reports_dir,
            self.states_dir,
            self.logs_dir,
            self.memory_dir,
            self.narrative_state_dir,
            self.tts_dir,
            self.tts_dir / "scripts",
            self.tts_dir / "audio",
            self.tts_dir / "results",
            self.tts_dir / "takes",
            self.tts_sound_assets_dir,
            self.tts_generated_sound_assets_dir,
            self.tts_dir / "sound_resolutions",
            self.tts_dir / "sound_generation",
        ]:
            d.mkdir(parents=True, exist_ok=True)
