"""Centralized Chinese UI string constants for the desktop application.

All user-facing Chinese text should be defined here and imported by reference,
never hardcoded inline. This enables consistent terminology and future i18n work.
"""

from __future__ import annotations


class UIStrings:
    """All Chinese UI labels, titles, and messages grouped by feature area."""

    # ── Window & Brand ────────────────────────────────────────────────
    APP_TITLE = "NIMO"
    BRAND_TITLE = "NIMO"
    BRAND_SUBTITLE = "AI-native narrative workspace\n\n把章节、记忆、世界状态与模型路由收束到一张可运行的创作台。"
    BRAND_MARK = "NIMO"

    # ── Navigation ────────────────────────────────────────────────────
    NAV_DASHBOARD = "案头"
    NAV_PROJECTS = "卷帙"
    NAV_WORKFLOW = "机杼"
    NAV_CHAPTER_STUDIO = "章台"
    NAV_SETTINGS = "火候"

    # ── Page Meta: Eyebrows ───────────────────────────────────────────
    EYEBROW_DASHBOARD = "案头"
    EYEBROW_PROJECTS = "卷帙"
    EYEBROW_WORKFLOW = "机杼"
    EYEBROW_SETTINGS = "火候"
    EYEBROW_CHAPTER_STUDIO = "章台"

    # ── Page Meta: Titles ─────────────────────────────────────────────
    TITLE_DASHBOARD = "先定手头所重"
    TITLE_PROJECTS = "展卷细读精微处"
    TITLE_WORKFLOW = "把任务调度清楚"
    TITLE_SETTINGS = "炼鼎通路，调鹽火候，令山河流载不穷。"
    TITLE_CHAPTER_STUDIO = "把章节工作放到一张台面上"

    # ── Page Meta: Subtitles ──────────────────────────────────────────
    SUBTITLE_DASHBOARD = "诸卷总领、任务行止与通路火候，皆陈于案头。"
    SUBTITLE_PROJECTS = "一卷在手，世界观、角色、章节与报告，尽收眼底。"
    SUBTITLE_WORKFLOW = "在同一页完成短篇快启、长篇立项与章节续写。"
    SUBTITLE_SETTINGS = "模型档案与任务路由落入 model_profiles.json，运行参数写回 .env。\n新提交的任务读取最新存档；正在运行的任务不会热切换配置。"
    SUBTITLE_CHAPTER_STUDIO = "上一章结果、本章目标、下一章预埋点与 AI 决策，俱在章台同看。"

    # ── Rail Footer ───────────────────────────────────────────────────
    RAIL_FOOTER_SLEEPING = "✦ 工坊沉睡中"
    RAIL_FOOTER_WAITING = "正待第一字落下…"
    RAIL_FOOTER_ACTIVE = "✦ 已孕育 {projects} 方世界"
    RAIL_FOOTER_WORDS = "流淌了 {words:,} 滴心血\n"
    RAIL_FOOTER_NO_WORDS = "大梦初觉，正待落笔\n"
    RAIL_FOOTER_PROVIDERS = "通路已启：{providers}\n"
    RAIL_FOOTER_MOCK = "通路已启：Mock\n"
    RAIL_FOOTER_CLOSING = "「万物皆虚，唯字长存」"

    # ── Top Bar ───────────────────────────────────────────────────────
    TOP_BAR_META_UNLOADED = "尚未读取"
    TOP_BAR_META_DASHBOARD = "案头待刷"

    # ── Dashboard Actions ─────────────────────────────────────────────
    ACTION_CONTINUE_INIT = "继续立项 →"
    ACTION_CONTINUE_VOLUME = "续此卷 →"
    ACTION_READ_PROJECT = "阅卷"
    ACTION_READ_PROJECT_ARROW = "阅卷 →"
    ACTION_GO_WORKFLOW = "去机杼"
    ACTION_GO_SETTINGS = "去火候"
    ACTION_START_WRITING = "起笔 →"

    # ── Projects Actions ──────────────────────────────────────────────
    ACTION_BACK_DASHBOARD = "返回案头"

    # ── Workflow Actions ──────────────────────────────────────────────
    ACTION_EXPORT_SHORT_TEMPLATE = "导出短篇模板"
    ACTION_EXPORT_LONG_TEMPLATE = "导出长篇模板"
    ACTION_SWITCH_TO_LONG = "切到长篇"
    ACTION_GO_CHAPTER_STUDIO = "去章台 →"
    ACTION_GO_CHAPTER_STUDIO_PLAIN = "前往章台 →"

    # ── Chapter Studio Actions ────────────────────────────────────────
    ACTION_CONTINUE_CURRENT_NODE = "继续当前节点 →"
    ACTION_OPEN_FOLDER = "打开文件夹"

    # ── Settings Actions ──────────────────────────────────────────────
    ACTION_SAVE_SETTINGS = "保存设置"
    ACTION_IMPORT_PROFILES = "导入配置文件"
    ACTION_EXPORT_PROFILES = "导出配置文件"
    ACTION_DETECT_ALL_PATHS = "检测全部通路"

    # ── Settings Page ─────────────────────────────────────────────────
    SETTINGS_SECTION_OVERVIEW = "运行总览"
    SETTINGS_SECTION_OVERVIEW_DESC = "当前工作区环境、已载入 Provider 与模型连接状态。"
    SETTINGS_CARD_STORAGE = "工作区路径"
    SETTINGS_CARD_PROVIDER = "默认模型"
    SETTINGS_CARD_LOADED = "已载入 Provider"
    SETTINGS_CARD_MODE = "运行模式"
    SETTINGS_SECTION_CONNECTION = "模型连接状态"
    SETTINGS_SECTION_CONNECTION_DESC = "自动检测模型接口连通性。绿灯 = 正常（含延迟），红灯 = 异常。"
    SETTINGS_SECTION_MODELS = "模型管理 — 添加、编辑和删除模型"
    SETTINGS_SECTION_MODELS_DESC = (
        "在此添加你需要使用的 AI 模型。每个模型需要指定供应商、模型 ID 和 API Key。\n"
        "添加完成后，可在下方「流程路由」中为各个创作步骤选择对应的模型。"
    )
    SETTINGS_LABEL_DEFAULT_MODEL = "默认模型"
    SETTINGS_HINT_DEFAULT_MODEL = "未分配路由的步骤均使用此模型"
    SETTINGS_BTN_ADD_MODEL = "+ 添加模型"
    SETTINGS_SECTION_ROUTING = "流程路由 — 为每个步骤选择模型与能力"
    SETTINGS_SECTION_ROUTING_DESC = (
        "为各步骤选择主模型、备用路由与温度；思考/多轮只在支持的模型上生效。"
        "未指定时使用默认模型，灰锁模型需补 API Key 后才能调用。"
    )
    SETTINGS_HINT_ARBITRATION_DISABLED = "当前已关闭灰区仲裁：仅规则判定，额外 LLM 调用为 0。"
    SETTINGS_HINT_ARBITRATION_ZERO_LIMIT = "当前虽已开启，但\u201c每章仲裁上限=0\u201d，等同禁用。"
    SETTINGS_HINT_ARBITRATION_ACTIVE = "当前预计每章最多仲裁 {max_items} 个要素（仅灰区触发）。"
    SETTINGS_HINT_ARBITRATION_INVERTED = (
        "灰区设置为 {low:.2f}~{high:.2f}（下界高于上界）；"
        "运行时会自动互换为 {high:.2f}~{low:.2f}。"
    )
    SETTINGS_HINT_ARBITRATION_SINGLE_POINT = "灰区设置为单点 {low:.2f}：仅该分数触发仲裁。"
    SETTINGS_HINT_ARBITRATION_RANGE = "当前灰区范围：{low:.2f}~{high:.2f}。"
    SETTINGS_HINT_OUTPUT_PARAMS = "单次输出上限 {max_tokens} token，温度 {temperature:.1f}。"
    SETTINGS_HINT_PROJECTS_DETECTED = "当前检测到 {count} 个项目"
    SETTINGS_HINT_MODELS_CONFIGURED = "共 {count} 个已配置模型 · 可在模型管理中修改"
    SETTINGS_HINT_PROVIDERS_ONLY_MOCK = "当前仅 Mock"
    SETTINGS_HINT_MODE_MOCK = "Mock 模式"
    SETTINGS_HINT_MODE_REAL = "真实模型模式"
    SETTINGS_HINT_MODE_TOGGLE = "可在下方「调试」分区开关。"
    SETTINGS_UNSAVED_WARNING = "- 火候页有未保存设置"

    # ── Save Notifications ────────────────────────────────────────────
    SAVE_UNCALLABLE_ROUTES_TITLE = "存在不可调用路由"
    SAVE_UNCALLABLE_ROUTES_MSG = "以下步骤选择了未配置 API Key 的模型，已自动跳过保存：\n{names}"
    SAVE_UNCALLABLE_FALLBACKS_TITLE = "存在不可调用备用路由"
    SAVE_UNCALLABLE_FALLBACKS_MSG = "以下步骤的备用路由包含不可调用模型，已自动跳过：\n{names}"
    SAVE_PARTIAL_TITLE = "部分保存成功"
    SAVE_PARTIAL_MSG = (
        "模型配置已保存到 {profiles_path}\n"
        "未找到 .env，因此仅保存了模型/路由配置；运行参数保持现状。"
    )
    SAVE_SUCCESS_TITLE = "保存成功"
    SAVE_SUCCESS_MSG = (
        "模型与路由已保存到 {profiles_path}\n"
        "运行参数已写入 {env_path}\n"
        "新的任务提交会立即读取这两处最新配置。"
    )

    # ── Job Status ────────────────────────────────────────────────────
    JOB_QUEUED = "排队中"
    JOB_RUNNING = "执行中"
    JOB_PAUSED = "等待决策"
    JOB_SUCCEEDED = "已完成"
    JOB_FAILED = "失败"
    JOB_AUTO_RUNNING = "自动中"

    # ── Job Submission Messages ───────────────────────────────────────
    JOB_SUBMIT_SHORT = "短篇任务已提交"
    JOB_SUBMIT_INIT_LONG = "长篇立项任务已提交"
    JOB_SUBMIT_RUN_CHAPTER = "章节任务已提交"
    JOB_SUBMIT_PREPARE_CHAPTER = "章节方案准备已提交"
    JOB_SUBMIT_RESOLVE_CHECKPOINT = "章节决策任务已提交"
    JOB_SUBMIT_REPAIR_CONTINUITY = "连贯性修复任务已提交"
    JOB_SUBMIT_REPAIR_CAUSAL = "因果链修复任务已提交"
    JOB_SUBMIT_REPAIR_ISSUES = "修复选中问题已提交"
    JOB_SUBMIT_REEVALUATE = "章节重新评估任务已提交"
    JOB_SUBMIT_POLISH = "精修润色任务已提交"
    JOB_SUBMIT_BOOK_CONSISTENCY = "全书一致性审计任务已提交"
    JOB_SUBMIT_EXPORT = "导出任务已提交"
    JOB_SUBMIT_REEXTRACT_RELATIONSHIPS = "关系重新提取任务已提交"
    JOB_SUBMIT_REPAIR_MOTIF_HISTORY = "母题历史修补任务已提交"
    JOB_SUBMIT_REBUILD_MEMORY_VECTORS = "向量索引重建任务已提交"
    JOB_SUBMIT_SYNC_CONTRACTS = "章节契约同步任务已提交"
    JOB_SUBMIT_EXTEND_OUTLINE = "延长全书任务已提交"

    # ── Job Cancel & Clear ────────────────────────────────────────────
    JOB_CANCEL_INIT = "用户已取消立项"
    JOB_CANCEL_INIT_MSG = "立项已取消，进度已保存，可重新提交从断点继续。"
    JOB_NO_CLEANUP = "当前任务流没有可清理的历史步骤。"
    JOB_CLEANED_UP = "已清理任务流历史 {count} 条。"
    JOB_CLEANED_UP_CHAPTER = "已同步清理第 {chapter} 章起的任务流历史（{count} 条）。"

    # ── Job Completion ────────────────────────────────────────────────
    JOB_COMPLETED = "任务完成：{label}"
    JOB_WAITING_DECISION = "等待决策：{label}"
    JOB_FAILED_MSG = "任务失败：{label}"

    # ── Error Dialogs ─────────────────────────────────────────────────
    ERR_INPUT_TITLE = "输入或校验错误"
    ERR_INPUT_SUMMARY = "提交参数未通过校验，请检查必填项和数值范围。"
    ERR_CONFIG_TITLE = "配置错误"
    ERR_CONFIG_SUMMARY = "当前模型或运行配置不可用，任务未启动。"
    ERR_JSON_TITLE = "AI 输出 JSON 格式错误"
    ERR_JSON_SUMMARY = "模型返回的内容无法解析为合法 JSON，可重试；若频繁出现请反馈。"
    ERR_JSON_LOCATION = "位置：第 {lineno} 行第 {colno} 列（字符 {pos}）"
    ERR_JSON_REASON = "原因：{msg}"
    ERR_MODEL_TITLE = "模型调用失败"
    ERR_MODEL_SUMMARY = "模型服务未正常返回，请检查 API Key、路由和网络状态。"
    ERR_FS_TITLE = "文件系统错误"
    ERR_FS_SUMMARY = "读取或写入项目文件时失败，请检查路径、权限和磁盘状态。"
    ERR_RUNTIME_TITLE = "运行时内部错误"
    ERR_RUNTIME_SUMMARY = "任务在执行过程中异常中断。\n{exc_type}：{detail}"

    # ── Dialog Buttons ────────────────────────────────────────────────
    BTN_OK = "知道了"
    BTN_CONFIRM = "确定"
    BTN_CANCEL = "取消"

    # ── Workflow Validation ───────────────────────────────────────────
    VAL_THEME_REQUIRED = "请填写「故事主题」。"
    VAL_PREMISE_REQUIRED = "请填写「故事前提」。"
    VAL_PROJECT_ID_REQUIRED = "请选择或输入长篇项目 ID。"
    VAL_NO_DECISIONS = "当前没有可继续的章节决策。"
    VAL_SELECT_DECISION = "请选择一个章节决策选项。"

    # ── Workflow Status Parts ─────────────────────────────────────────
    STATUS_WORD_COUNT = "{count:,} 字"
    STATUS_QUALITY_SCORE = "质量评分 {score:.1f}"
    STATUS_CONTINUITY = "连贯 {score:.1f}"
    STATUS_CAUSAL = "因果 {score:.1f}"
    STATUS_CONSISTENCY = "一致性 {score:.1f}"
    STATUS_ISSUES = "问题 {count}"
    STATUS_APPLIED = "已修复"
    STATUS_NOT_APPLIED = "未修改"
    STATUS_PATCHES = "补丁 {applied}/{attempted}"
    STATUS_REPAIR_DONE = "修补完成"
    STATUS_REPAIR_NOT_DONE = "修补未完成"
    STATUS_MOTIFS_BACKFILLED = "回填母题 {count}"
    STATUS_OCCURRENCES = "统计片段 {count}"
    STATUS_MOTIFS_CREATED = "新增母题 {count}"
    STATUS_EXTRACTION_CACHE = "补并缓存章 {count}"
    STATUS_CHAPTERS_FIXED = "修复 {applied}/{targeted} 章"
    STATUS_TOKENS_USED = "Token 消耗 {count}"
    STATUS_WARNINGS = "{count} 条提醒"

    # ── Chapter Studio Widgets ────────────────────────────────────────
    CS_TRACK_HEADING = "章节轨道"
    CS_TRACK_NO_PROJECT = "尚未载入项目"
    CS_TRACK_META = "{title} · 共 {total} 章 · 当前第 {current} 章"
    CS_CHAPTER_UNNAMED = "未命名"
    CS_CHAPTER_LABEL = "第 {num} 章 {title} · {status}"
    CS_STATUS_PENDING = "待写"

    # ── Chapter Studio: Decision Mode ─────────────────────────────────
    CS_DECISION_MODE_LABEL = "裁决模式"
    CS_MODE_MANUAL = "全手动"
    CS_MODE_MANUAL_TIP = "所有决策由用户手动操作。"
    CS_MODE_SUGGEST = "AI 建议"
    CS_MODE_SUGGEST_TIP = "AI 提供推荐方案，用户可修改后确认。"
    CS_MODE_AUTO = "本章自动"
    CS_MODE_AUTO_TIP = "AI 自动完成当前章节（准备、起草、归档），完成后停止。"
    CS_MODE_BOOK_AUTO = "章节连跑"
    CS_MODE_BOOK_AUTO_TIP = "AI 从当前章连续自动推进，直到全书完成。"

    # ── Chapter Studio: Compass Cards ─────────────────────────────────
    CS_COMPASS_PREVIOUS = "上一章实际结果"
    CS_COMPASS_CURRENT = "本章目标"
    CS_COMPASS_NEXT = "下一章预埋点"
    CS_COMPASS_NO_PREVIOUS = "上一章尚无正文，可直接围绕本章目标起笔。"
    CS_COMPASS_NO_CURRENT = "当前章尚未配置目标。"
    CS_COMPASS_NO_NEXT = "下一章暂未设定，先聚焦当前章。"

    # ── Chapter Studio: Motif Hints ───────────────────────────────────
    CS_MOTIF_HINT_HEADER = "母题提示"
    CS_MOTIF_HINT_EMPTY = "暂无母题建议"
    CS_MOTIF_UNKNOWN = "未知母题"
    CS_MOTIF_REPEAT_WARNING = "重复警告: {warnings}"
    CS_MOTIF_NO_SUGGESTION = "暂无相关母题建议"
    CS_MOTIF_GAP_SUGGESTION = "该{category}「{name}」已{gap}章未出现"

    # ── Chapter Studio: Motif Categories ──────────────────────────────
    MOTIF_CATEGORY_IMAGE = "意象"
    MOTIF_CATEGORY_ACTION = "动作"
    MOTIF_CATEGORY_SENSE = "感官"
    MOTIF_CATEGORY_COLOR = "颜色"
    MOTIF_CATEGORY_SOUND = "声音"
    MOTIF_CATEGORY_THEME = "主题"
    MOTIF_CATEGORY_SYMBOL = "符号"

    # ── Workflow Pipeline Steps ───────────────────────────────────────
    PIPELINE_SPEC = "规格确认"
    PIPELINE_BEATS = "节拍生成"
    PIPELINE_DRAFT = "初稿完成"
    PIPELINE_EDIT_PREFIX = "编辑修订"
    PIPELINE_EVALUATE = "质量评估"
    PIPELINE_STEP_TOOLTIP = "点击查看该步骤产出文件"
    PIPELINE_STEP_SKIPPED = "已跳过"

    # ── Projects Page ─────────────────────────────────────────────────
    PROJ_TAB_DRAFTS = "草稿历程"
    PROJ_TAB_CHAPTER_TEXT = "章节正文"
    PROJ_TAB_CHAPTER_REPORT = "章节报告"
    PROJ_TAB_RELATIONSHIPS = "关系追踪"
    PROJ_TAB_TOKENS = "Token 追踪"
    PROJ_COMBO_PLACEHOLDER = "请选择项目…"
    PROJ_BTN_CONTINUE = "续此卷"
    PROJ_BTN_BACK = "返回案头"
    PROJ_HINT_SELECT_PROJECT = "请在案头选择一个项目，然后点击「阅卷」按钮来到此处。"
    PROJ_HINT_SELECT_PROJECT_SHORT = "请在案头选择一个项目。"
    PROJ_HINT_DATA_UNAVAILABLE = "所选项目数据不可用。"
    PROJ_HINT_NOT_IN_LIBRARY = "所选项目不在库中。"
    PROJ_HINT_NO_DOCUMENTS = "此卷尚无可查看的文档。\n流程完成后此处将展示作品内容。"
    PROJ_HINT_NO_PROJECT_DOCS = "此项目尚无可查看的文档。\n完成立项流程后此处将展示各类资料。"
    PROJ_HINT_NO_DATA = "暂无{label}数据。\n完成对应流程后将自动生成。"
    PROJ_HINT_NO_CHAPTERS = "暂无章节数据。\n完成立项后此处将列出所有章节。"
    PROJ_HINT_NO_CHAPTER_TEXT = "第 {chapter} 章尚未落笔。\n续写该章后可在此阅读。"
    PROJ_HINT_NO_CHAPTER_REPORT = "第 {chapter} 章暂无报告。\n章节流程完成后此处将展示质量评估等信息。"
    PROJ_HINT_NO_RELATIONSHIPS = (
        "暂未追踪到角色关系。\n"
        "完成章节创作后，角色之间的关系变化将在此展示。"
    )
    PROJ_HINT_RELATIONSHIP_FAILED = "关系数据加载失败。\n完成章节创作后此处将展示角色关系图谱。"
    PROJ_SEARCH_PLACEHOLDER = "搜索章节…"
    PROJ_BTN_REFRESH = "刷新"
    PROJ_FILTER_ALL = "全部角色"
    PROJ_FILTER_LABEL = "角色筛选"
    PROJ_UNSAVED_WARNING = "- 卷帙页（Token 追踪）有未保存设置"
    PROJ_FINAL_DRAFT = "终稿"

    # ── Projects Page: Document Labels ────────────────────────────────
    DOC_SHORT_STORY = "正文"
    DOC_SPEC = "故事规格"
    DOC_ELEMENT_SELECT = "要素选择"
    DOC_BEATS = "节拍结构"
    DOC_EVAL_REPORT = "评估报告"
    DOC_OUTLINE = "全书大纲"
    DOC_STORY_BIBLE = "世界观设定"
    DOC_CHARACTER_BIBLE = "角色设定"
    DOC_NARRATIVE_BLUEPRINT = "叙事蓝图"
    DOC_BOOK_CONSISTENCY_AUDIT = "全书一致性审计"
    DOC_BOOK_CONSISTENCY_REPAIR = "全书修复报告"
    DOC_QUALITY_EVAL = "质量评估"
    DOC_CREATIVE_SUMMARY = "创作总结"
    DOC_ALIGNMENT_REPORT = "对齐报告"
    DOC_CONTINUITY = "连贯性"

    # ── Report: Bible Field Labels ────────────────────────────────────
    REPORT_BIBLE_PREMISE = "故事前提"
    REPORT_BIBLE_ERA = "时代背景"
    REPORT_BIBLE_GEOGRAPHY = "地理场景"
    REPORT_BIBLE_CULTURE = "社会文化"
    REPORT_BIBLE_MAGIC_TECH = "核心设定 / 魔法·技术"
    REPORT_BIBLE_TONE = "叙事基调"

    # ── Report: Genre Labels ──────────────────────────────────────────
    REPORT_GENRE_ROMANCE = "言情"
    REPORT_GENRE_FANTASY = "奇幻"
    REPORT_GENRE_MYSTERY = "悬疑"
    REPORT_GENRE_SCIFI = "科幻"
    REPORT_GENRE_LITERARY = "文学"
    REPORT_GENRE_THRILLER = "惊悚"
    REPORT_GENRE_HUMOR = "幽默"
    REPORT_GENRE_HORROR = "恐怖"
    REPORT_GENRE_HISTORICAL = "历史"
    REPORT_GENRE_WUXIA = "武侠"
    REPORT_GENRE_XIANXIA = "仙侠"

    # ── Report: Tone Labels ───────────────────────────────────────────
    REPORT_TONE_WARM = "温暖"
    REPORT_TONE_DARK = "暗黑"
    REPORT_TONE_HUMOROUS = "幽默"
    REPORT_TONE_LYRICAL = "诗意"
    REPORT_TONE_GRITTY = "粗粝"
    REPORT_TONE_EPIC = "史诗"
    REPORT_TONE_INTIMATE = "私密"
    REPORT_TONE_SATIRICAL = "讽刺"

    # ── Report: Eval Dimension Labels ─────────────────────────────────
    REPORT_EVAL_CONSISTENCY = "设定一致"
    REPORT_EVAL_CONTINUITY = "场景连贯"
    REPORT_EVAL_CHARACTER = "人物塑造"
    REPORT_EVAL_STYLE = "文笔风格"
    REPORT_EVAL_ENGAGEMENT = "吸引力"
    REPORT_EVAL_PACING = "节奏控制"
    REPORT_EVAL_CAUSAL_CHAIN = "因果链"
    REPORT_EVAL_TENSION = "张力控制"
    REPORT_EVAL_COHERENCE = "连贯性"
    REPORT_EVAL_TECH_DENSITY = "术语密度"
    REPORT_EVAL_PLOT = "情节逻辑"
    REPORT_EVAL_ORIGINALITY = "独创性"
    REPORT_EVAL_THEME = "主题表达"
    REPORT_EVAL_WORLD_BUILDING = "世界构建"
    REPORT_EVAL_DIALOGUE = "对话质量"
    REPORT_EVAL_REWRITE_COMPLIANCE = "重写落地"

    # ── Report: Generic Key Labels ────────────────────────────────────
    REPORT_KEY_FROM_CHAPTER = "衔接自章"
    REPORT_KEY_TO_CHAPTER = "过渡至章"
    REPORT_KEY_OPENING_TIME = "开场时间"
    REPORT_KEY_OPENING_LOCATION = "开场地点"
    REPORT_KEY_OPENING_POV = "开场视角"
    REPORT_KEY_TRANSITION_MODE = "过渡方式"
    REPORT_KEY_EMOTIONAL_CARRYOVER = "情感承接"
    REPORT_KEY_ACTION_HANDOFF = "行动交接"
    REPORT_KEY_PENDING_QUESTIONS = "悬而未决的问题"
    REPORT_KEY_FORBIDDEN_REPETITION = "下一章避免重复"
    REPORT_KEY_BRIDGE_SUMMARY = "桥接概述"
    REPORT_KEY_SENSORY_ANCHORS = "感官锚点"
    REPORT_KEY_RELATIONSHIP_BEAT = "关系节拍"
    REPORT_KEY_CURRENT_TRUST = "信任度"
    REPORT_KEY_UNSPOKEN_TENSION = "潜在张力"
    REPORT_KEY_POWER_DYNAMIC = "权力动态"
    REPORT_KEY_SCENE_INTENTS = "场景编排"
    REPORT_KEY_OPENING_CONTRACT = "开篇契约"
    REPORT_KEY_CLOSING_CONTRACT = "收束契约"
    REPORT_KEY_EMOTIONAL_ARC = "情感弧线"
    REPORT_KEY_STATE_TRANSITIONS = "状态转换"
    REPORT_KEY_FORESHADOWING_PLAN = "伏笔计划"
    REPORT_KEY_KEY_REVELATIONS = "关键揭露"
    REPORT_KEY_SCENE_ID = "场景 ID"
    REPORT_KEY_SUMMARY = "摘要"
    REPORT_KEY_PURPOSE = "目的"
    REPORT_KEY_CONFLICT = "冲突"
    REPORT_KEY_REQUIRED_CHARACTERS = "涉及角色"
    REPORT_KEY_CHARACTER_MOTIVATIONS = "角色动机"
    REPORT_KEY_ENTRY_STATE = "进入状态"
    REPORT_KEY_REQUIRED_OUTCOME = "必要结果"
    REPORT_KEY_EXIT_TARGET_STATE = "退出状态"
    REPORT_KEY_LOCATION = "地点"
    REPORT_KEY_TIME_MARKER = "时间标记"
    REPORT_KEY_CHARACTER = "角色"
    REPORT_KEY_MOTIVATION = "动机"
    REPORT_KEY_STAKE = "风险"
    REPORT_KEY_ALIGNMENT_SCORE = "对齐分数"
    REPORT_KEY_RISK_LEVEL = "风险级别"
    REPORT_KEY_MISSING_MAIN_POINTS = "缺失主线要点"
    REPORT_KEY_SUPPORTIVE_SUBPLOT = "支线正面贡献"
    REPORT_KEY_WEAK_SUBPLOT = "薄弱支线"
    REPORT_KEY_REPAIR_ACTIONS = "修复建议"
    REPORT_KEY_CONTINUITY_SCORE = "连贯性分数"
    REPORT_KEY_ISSUES = "问题列表"
    REPORT_KEY_RECOMMENDATIONS = "建议"
    REPORT_KEY_VIOLATIONS = "违规项"
    REPORT_KEY_ANALYSIS = "分析"
    REPORT_KEY_SEVERITY = "严重性"
    REPORT_KEY_DESCRIPTION = "描述"
    REPORT_KEY_CHAPTER_NUMBER = "章节编号"
    REPORT_KEY_CHAPTER_OUTLINE = "章节大纲"
    REPORT_KEY_CANON_CONTEXT = "Canon 上下文"
    REPORT_KEY_PREVIOUS_EXIT_STATE = "上章退出状态"
    REPORT_KEY_PREVIOUS_ENDING = "上章结尾"
    REPORT_KEY_PREVIOUS_CREATIVE_REPORT = "上章创作报告"
    REPORT_KEY_CHARACTER_PROFILES = "角色资料"
    REPORT_KEY_ACTIVE_RELATIONSHIPS = "活跃关系"
    REPORT_KEY_ACTIVE_PLOT_THREADS = "活跃情节线"
    REPORT_KEY_MUST_CARRY_FORWARD = "必须承接"
    REPORT_KEY_KNOWN_CHARACTERS = "已知角色"
    REPORT_KEY_BRIDGE = "桥接"
    REPORT_KEY_OVERALL_SCORE = "总评分"
    REPORT_KEY_SCORES = "各维度评分"
    REPORT_KEY_PASSED = "是否通过"
    REPORT_KEY_THRESHOLD = "阈值"
    REPORT_KEY_DIMENSION = "维度"
    REPORT_KEY_SCORE = "分数"
    REPORT_KEY_COMMENT = "评语"
    REPORT_KEY_GENRE = "题材"
    REPORT_KEY_TITLE = "标题"
    REPORT_KEY_NAME = "名称"
    REPORT_KEY_ROLE = "角色定位"
    REPORT_KEY_STATUS = "状态"
    REPORT_KEY_WORD_COUNT = "字数"
    REPORT_KEY_GUARD_REPORT = "护栏报告"

    # ── Report: Transition Mode Labels ────────────────────────────────
    REPORT_TRANSITION_SYNTHETIC = "合成过渡"
    REPORT_TRANSITION_DIRECT = "直接衔接"
    REPORT_TRANSITION_DIRECT_CONTINUE = "直接延续"
    REPORT_TRANSITION_ACTION_HANDOFF = "行动交接"
    REPORT_TRANSITION_POV_SWITCH = "视角切换"
    REPORT_TRANSITION_TIME_SKIP = "时间跳跃"
    REPORT_TRANSITION_FLASHBACK = "闪回"
    REPORT_TRANSITION_PARALLEL = "平行叙事"

    # ── Report: Severity Labels ───────────────────────────────────────
    REPORT_SEVERITY_CRITICAL = "严重"
    REPORT_SEVERITY_HIGH = "高"
    REPORT_SEVERITY_MEDIUM = "中"
    REPORT_SEVERITY_LOW = "低"
    REPORT_SEVERITY_URGENT = "紧迫"
    REPORT_SEVERITY_WARNING = "警告"
    REPORT_SEVERITY_INFO = "提示"

    # ── Report: Risk Labels ───────────────────────────────────────────
    REPORT_RISK_LOW = "低冲突"
    REPORT_RISK_MEDIUM = "中冲突"
    REPORT_RISK_HIGH = "高冲突"
    REPORT_RISK_LOW_ALT = "低风险"
    REPORT_RISK_MEDIUM_ALT = "中风险"
    REPORT_RISK_HIGH_ALT = "高风险"

    # ── Report: Section Headings ──────────────────────────────────────
    REPORT_SECTION_WORLD_RULES = "世界规则"
    REPORT_SECTION_CORE_THEMES = "核心主题"
    REPORT_SECTION_DIMENSION_SCORES = "各维度评分"
    REPORT_SECTION_REPAIR_SUGGESTIONS = "修复建议"
    REPORT_SECTION_OPENING_SETTINGS = "开场设定"
    REPORT_SECTION_BRIDGE_OVERVIEW = "桥接概述"
    REPORT_SECTION_EMOTIONAL_CARRYOVER = "情感承接"
    REPORT_SECTION_ACTION_HANDOFF = "行动交接"
    REPORT_SECTION_CAUSAL_CARRYOVER = "因果承接"
    REPORT_SECTION_RELATIONSHIP_BEAT = "关系节拍"
    REPORT_SECTION_SENSORY_ANCHORS = "感官锚点"
    REPORT_SECTION_PENDING_QUESTIONS = "悬而未决的问题"
    REPORT_SECTION_FORBIDDEN_REPETITION = "下一章避免重复"
    REPORT_SECTION_SCENE_ARRANGEMENT = "场景编排 · 共 {count} 场"
    REPORT_SECTION_STATE_TRANSITIONS = "状态转换"
    REPORT_SECTION_FORESHADOWING_PLAN = "伏笔计划"
    REPORT_SECTION_KEY_REVELATIONS = "关键揭露"
    REPORT_SECTION_MISSING_MAIN_POINTS = "缺失的主线要点"
    REPORT_SECTION_SUPPORTIVE_SUBPLOT = "支线正面贡献"
    REPORT_SECTION_WEAK_SUBPLOT = "薄弱支线"
    REPORT_SECTION_CONTINUITY_ISSUES = "连贯性问题 · {count} 项"
    REPORT_SECTION_ENTITY_DISPOSAL = "实体处置 · {count} 项"
    REPORT_SECTION_NEXT_CHAPTER_CONSTRAINTS = "下一章约束 · {count} 条"
    REPORT_SECTION_CAUSAL_ISSUES = "因果问题 · {count} 项"
    REPORT_SECTION_INHERITED_SUSPENSES = "继承悬念 · {count} 项"
    REPORT_SECTION_RESOLVED_SUSPENSES = "窗口内已兑现悬念 · {count} 项"
    REPORT_SECTION_MISSED_SUSPENSES = "错过兑现窗口 · {count} 项"
    REPORT_SECTION_DEVIATION_ALERTS = "偏离预警 · {count} 项"
    REPORT_SECTION_NARRATIVE_PROGRESS = "叙事推进"
    REPORT_SECTION_MAIN_PLOT_PROGRESS = "主线推进 · {count} 项"
    REPORT_SECTION_SUBPLOT_PROGRESS = "支线推进 · {count} 项"
    REPORT_SECTION_STRAND_ACTIVITY = "情节线活动 · {count} 条"
    REPORT_SECTION_ELEMENT_EXEC_SUMMARY = "要素执行摘要 · {count} 项"
    REPORT_SECTION_NEXT_CHAPTER_CONSTRAINTS_SUGGEST = "下一章约束建议"
    REPORT_SECTION_SUMMARY = "总结"
    REPORT_SECTION_OVERVIEW = "总体概览"
    REPORT_SECTION_STAGE_DETAILS = "阶段详情"
    REPORT_SECTION_HOOKS = "章尾钩子"
    REPORT_SECTION_MICRO_PAYOFFS = "微兑现 ({})"
    REPORT_SECTION_CHAPTER_PACING = "章节节奏"
    REPORT_SECTION_ITEM_SCORES = "分项评分"

    # ── Report: Continuity Issue Types ────────────────────────────────
    ISSUE_CONTINUITY_GAP = "连贯缺口"
    ISSUE_CARRY_FORWARD_MISSING = "承接缺失"
    ISSUE_CHARACTER_INCONSISTENCY = "角色不一致"
    ISSUE_PROMPT_LEAK = "提词泄漏"
    ISSUE_LOCATION_JUMP = "场景跳切"
    ISSUE_CUSTODY_BREAK = "托管中断"
    ISSUE_POV_JUMP = "视角跳切"
    ISSUE_OPENING_GAP = "开场衔接"
    ISSUE_CLOSING_GAP = "结尾衔接"
    ISSUE_CLOSING_CONTRACT_MISMATCH = "结尾契约"
    ISSUE_BRIDGE_CONTRACT_NOT_FOLLOWED = "桥接契约"
    ISSUE_BRIDGE_CONTRACT_VIOLATION = "桥接契约"
    ISSUE_HANDOFF_MISSING = "交接缺失"
    ISSUE_KNOWLEDGE_CONTRADICTION = "知识矛盾"
    ISSUE_ENDING_AMBIGUITY = "结尾模糊"
    ISSUE_EXIT_STATE_GAP = "退出状态"
    ISSUE_QUESTION_IGNORED = "悬念搁置"
    ISSUE_INFORMATION_CONSISTENCY = "信息一致"
    ISSUE_RELATIONSHIP_CHANGE_SUPPORT = "关系支撑"
    ISSUE_RELATIONSHIP_DEVELOPMENT = "关系发展"
    ISSUE_FORBIDDEN_ELEMENT_VIOLATION = "硬禁元素"
    ISSUE_FORBIDDEN_ELEMENT_USAGE = "意象复用"
    ISSUE_TEXT_REPETITION = "文本重复"
    ISSUE_SENSORY_ANCHOR_REPETITION = "感官重复"
    ISSUE_TIMELINE_CONFLICT = "时间线冲突"
    ISSUE_LOCATION_INCONSISTENCY = "场景不一致"
    ISSUE_PLOT_CONTRADICTION = "情节矛盾"
    ISSUE_TONE_SHIFT = "基调偏移"
    ISSUE_RELATIONSHIP_INCONSISTENCY = "关系不一致"
    ISSUE_STATE_CONTRADICTION = "状态矛盾"
    ISSUE_FACTUAL_ERROR = "事实错误"

    # ── Report: Causal Issue Types ────────────────────────────────────
    CAUSAL_QUESTION_RESOLVED_TOO_EARLY = "悬念提前揭晓"
    CAUSAL_UNMOTIVATED_ACTION = "动机不足"
    CAUSAL_MISSING_CONSEQUENCE = "缺失后果"
    CAUSAL_TIMELINE_INCONSISTENCY = "时间线不一致"
    CAUSAL_LOGIC_GAP = "逻辑断层"
    CAUSAL_CONTRADICTION = "前后矛盾"
    CAUSAL_CAUSE_MISSING = "因由缺失"
    CAUSAL_EFFECT_MISSING = "结果缺失"
    CAUSAL_PACING_ISSUE = "节奏问题"
    CAUSAL_FORESHADOWING_ORPHAN = "埋线未收"

    # ── Report: Guard Decision Labels ─────────────────────────────────
    GUARD_DECISION_CONTINUE = "继续"
    GUARD_DECISION_CONTINUE_WITH_CONSTRAINTS = "带约束继续"
    GUARD_DECISION_ADJUST_OUTLINE_FAST = "快速调整大纲"
    GUARD_DECISION_ADJUST_OUTLINE_SMART = "智能调整大纲"
    GUARD_DECISION_PAUSE_FOR_HUMAN = "等待人工决策"
    GUARD_DECISION_ROLLBACK_AND_REGEN = "回滚重生成"

    # ── Report: Guard Entity Actions ──────────────────────────────────
    GUARD_ENTITY_KEEP = "保留"
    GUARD_ENTITY_DEFER = "延后"
    GUARD_ENTITY_MERGE = "合并"
    GUARD_ENTITY_DROP = "丢弃"

    # ── Report: Guard Entity Types ────────────────────────────────────
    GUARD_ENTITY_CHARACTER = "角色"
    GUARD_ENTITY_LOCATION = "场景"
    GUARD_ENTITY_ITEM = "物品"

    # ── Report: Guard Outline Actions ─────────────────────────────────
    GUARD_OUTLINE_FAST = "快速调整"
    GUARD_OUTLINE_SMART = "智能调整"

    # ── Report: Suspense Types ────────────────────────────────────────
    SUSPENSE_QUESTION = "疑问"
    SUSPENSE_THREAT = "威胁"
    SUSPENSE_SECRET = "秘密"
    SUSPENSE_PROMISE = "承诺"
    SUSPENSE_MYSTERY = "谜团"
    SUSPENSE_CLIFFHANGER = "悬念"
    SUSPENSE_REVELATION = "揭露"
    SUSPENSE_CONFLICT = "冲突"

    # ── Report: Suspense Issue Types ──────────────────────────────────
    SUSPENSE_ISSUE_DELAY = "悬念延迟"
    SUSPENSE_ISSUE_MONOTONY = "钩子单调"
    SUSPENSE_ISSUE_TENSION_MISMATCH = "张力不匹配"
    SUSPENSE_ISSUE_STRAND_DORMANCY = "情节线休眠"

    # ── Report: Narrative Structure ───────────────────────────────────
    NARRATIVE_SETUP = "铺垫"
    NARRATIVE_RISING_ACTION = "上升动作"
    NARRATIVE_CLIMAX = "高潮"
    NARRATIVE_FALLING_ACTION = "下降动作"
    NARRATIVE_RESOLUTION = "收束"

    # ── Report: Strength Labels ───────────────────────────────────────
    STRENGTH_STRONG = "强"
    STRENGTH_MEDIUM = "中"
    STRENGTH_WEAK = "弱"
    STRENGTH_NONE = "无"

    # ── Report: Position Labels ───────────────────────────────────────
    POSITION_OPENING = "开篇"
    POSITION_MIDDLE = "中段"
    POSITION_CLOSING = "结尾"
    POSITION_OPENING_PARAGRAPH = "开头段落"
    POSITION_MIDDLE_PARAGRAPH = "中间段落"
    POSITION_CLOSING_PARAGRAPH = "结尾段落"
    POSITION_CHAPTER = "全章"
    POSITION_PARAGRAPH = "单段"

    # ── Report: Hook Types ────────────────────────────────────────────
    HOOK_CRISIS = "危机钩"
    HOOK_MYSTERY = "悬念钩"
    HOOK_EMOTION = "情绪钩"
    HOOK_CHOICE = "选择钩"
    HOOK_DESIRE = "渴望钩"
    HOOK_NONE = "无明显钩子"

    # ── Report: Micro Payoff Types ────────────────────────────────────
    PAYOFF_INFORMATION = "信息"
    PAYOFF_RELATIONSHIP = "关系"
    PAYOFF_ABILITY = "能力"
    PAYOFF_RESOURCE = "资源"
    PAYOFF_RECOGNITION = "认可"
    PAYOFF_EMOTION = "情绪"
    PAYOFF_CLUE = "线索"

    # ── Report: Reading Power ─────────────────────────────────────────
    RP_WINDOW_LABEL = "追读力窗口"
    RP_WINDOW_SPAN = "窗口跨度：{count} 章"
    RP_WINDOW_CENTER = "中心章节：第 {chapter} 章"
    RP_WINDOW_SCORE_LABEL = "追读力窗口综合评分"
    RP_TIMELINE_EXECUTION = "时间线执行"
    RP_SUSPENSE_CHAIN = "悬念链"
    RP_STRAND_BALANCE = "情节线平衡"
    RP_EXECUTION_VERIFIED = "✓ 已验证"
    RP_EXECUTION_NOT_VERIFIED = "✗ 未验证"
    RP_ON_TIME = "准时"
    RP_DELAY = "延迟 {count} 章"
    RP_EARLY = "提前 {count} 章"
    RP_DORMANT = "休眠 {count} 章"
    RP_DORMANT_WARNING = "⚠ 休眠预警"
    RP_ACTIVE = "活跃"
    RP_HIT = "命中"
    RP_WEAK = "薄弱"
    RP_MISS = "缺失"

    # ── Report: Memory Diagnostics ────────────────────────────────────
    MEM_STAGE_PLANNING = "规划"
    MEM_STAGE_DRAFT = "起草"
    MEM_STAGE_FINALIZE = "收束"
    MEM_LAYER_L0 = "L0 项目身份"
    MEM_LAYER_L1 = "L1 核心记忆"
    MEM_LAYER_L2 = "L2 按需检索"
    MEM_LAYER_L3 = "L3 深层检索"
    MEM_CONTEXT_PROMPT = "提示上下文"
    MEM_CONTEXT_LAYERED = "分层记忆"
    MEM_CONTEXT_RELEVANT_HISTORY = "相关历史"
    MEM_CONTEXT_PREVIOUS_EVENTS = "上一章事件"
    MEM_CONTEXT_OUTLINE = "大纲上下文"
    MEM_CONTEXT_MOTIF_CONTINUITY = "母题连续性"
    MEM_CONTEXT_MOTIF_SUGGESTIONS = "母题建议"
    MEM_STATUS_GENERATED = "已生成"
    MEM_STATUS_FETCHED = "已拉取"
    MEM_STATUS_PREFETCHED = "已复用"
    MEM_STATUS_EMPTY = "为空"
    MEM_STATUS_FETCHED_EMPTY = "无命中"
    MEM_STATUS_PREFETCHED_EMPTY = "复用为空"
    MEM_STATUS_DISABLED = "未启用"
    MEM_STATUS_NOT_APPLICABLE = "不适用"
    MEM_STATUS_UNAVAILABLE = "不可用"
    MEM_STATUS_ERROR = "失败"
    MEM_STATUS_SCHEDULED = "已调度"
    MEM_STATUS_PENDING = "处理中"
    MEM_SIGNAL_RELEVANT_HISTORY = "相关历史"
    MEM_SIGNAL_PREVIOUS_EVENTS = "上一章事件"
    MEM_SIGNAL_OUTLINE_CONTEXT = "大纲上下文"
    MEM_SIGNAL_MOTIF_CONTINUITY = "母题连续性"
    MEM_SIGNAL_MOTIF_SUGGESTIONS = "母题建议"
    MEM_SIGNAL_PROMPT_SUMMARY = "提示摘要"
    MEM_SIGNAL_CRITIQUE_CONTEXT = "批注上下文"
    MEM_SIGNAL_FORBIDDEN_REPETITION = "禁复提醒"
    MEM_SIGNAL_LAYERED_CONTEXT = "分层记忆"
    MEM_COUNT_RELEVANT_HISTORY = "历史片段"
    MEM_COUNT_PREVIOUS_EVENTS = "上章事件"
    MEM_COUNT_OUTLINE_FIELDS = "大纲字段"
    MEM_COUNT_MOTIF_SUGGESTIONS = "母题建议"
    MEM_COUNT_FORBIDDEN_WORDS = "禁复词"
    MEM_COUNT_ACTIVE_MOTIFS = "活跃母题"
    MEM_COUNT_MOTIF_ENTRIES = "母题条目"
    MEM_COUNT_PROMPT_FIELDS = "提示字段"
    MEM_NO_DATA = "无"
    MEM_NO_SOURCE_DATA = "无来源数据"
    MEM_NO_ATTACHED_SIGNAL = "无附加信号"
    MEM_NO_COUNT_DATA = "无计数数据"
    MEM_NO_EFFECTIVE_HIT = "无有效命中"
    MEM_NO_STAGE_DIAGNOSTIC = "当前章节还没有可展示的阶段诊断。"
    MEM_REUSED_HISTORY = "复用历史"
    MEM_TITLE = "记忆诊断"
    MEM_LATEST_LABEL = "最新：{stage}"
    MEM_STAGE_COVERAGE = "阶段覆盖"
    MEM_NO_STAGE = "暂无阶段"
    MEM_OVERALL_HIT = "总体命中"
    MEM_CONNECTED_MEMORY = "已接入记忆"

    # ── Report: Story Artifacts ───────────────────────────────────────
    ARTIFACT_MODE_LABEL = "模式：{mode}"
    ARTIFACT_VERSION_LABEL = "库版本：{version}"
    ARTIFACT_GENRE_JUDGMENT = "题材判断"
    ARTIFACT_EXECUTION_CONSTRAINTS = "执行约束"
    ARTIFACT_RECOMMENDED_GENRES = "推荐题材：{genres}"
    ARTIFACT_SELECTION_REASON = "选用原因：{reason}"
    ARTIFACT_VALUE = "价值：{rationale}"
    ARTIFACT_PROMPT_HINT = "提示词：{prompt_hint}"
    ARTIFACT_REQUIRED_ELEMENTS = "必要项"
    ARTIFACT_EXTENSION_ELEMENTS = "扩展项"
    ARTIFACT_NO_ELEMENT_DATA = "暂无叙事要素选择数据"
    ARTIFACT_ELEMENT_SELECTION_TITLE = "叙事要素选择"
    ARTIFACT_SOURCE_ELEMENT = "来源要素：{source}"
    ARTIFACT_STYLE_BASELINE = "风格基调"
    ARTIFACT_HOOK_REQUIREMENTS = "钩子要求"
    ARTIFACT_SATISFACTION_MODE = "爽点模式"
    ARTIFACT_MICRO_PAYOFF_REQUIREMENTS = "微兑现要求"
    ARTIFACT_THREE_STRAND_RHYTHM = "三线节奏阈值"
    ARTIFACT_PACING_PARAMS = "节奏参数"
    ARTIFACT_READING_POWER_WEIGHTS = "追读力评分权重"
    ARTIFACT_WRITING_TECH_SPECS = "写作技法规范"
    ARTIFACT_NO_STYLE_DATA = "暂无风格规范数据"
    ARTIFACT_STYLE_SPEC_TITLE = "风格规范"
    ARTIFACT_NO_RP_CONFIG_DATA = "暂无追读力窗口配置数据"
    ARTIFACT_RP_CONFIG_TITLE = "追读力窗口配置"
    ARTIFACT_ENABLED = "已启用"
    ARTIFACT_DISABLED = "已禁用"
    ARTIFACT_WINDOW_BOUNDARIES = "窗口边界"
    ARTIFACT_SUSPENSE_TRACKING = "悬念追踪"
    ARTIFACT_HOOK_ALTERNATION = "钩子交替"
    ARTIFACT_TENSION_MATCHING = "张力匹配"
    ARTIFACT_SCORE_WEIGHTS = "评分权重"
    ARTIFACT_WARNING_THRESHOLDS = "预警阈值"
    ARTIFACT_FORCE_PAYOFF_CHECK = "强制兑现检查"
    ARTIFACT_HOOK_ALTERNATION_CHECK = "钩子交替检查"
    ARTIFACT_TENSION_RECOVERY_CALC = "张力恢复计算"
    ARTIFACT_FALLBACK_SUFFIX = " · 兜底报告"
    ARTIFACT_EVAL_NOT_COMPLETE = "评估未完成"
    ARTIFACT_FALLBACK_WARNING = (
        "当前内容是兜底报告，原因：{reason}。不要把该分数当作真实追读力诊断。"
    )
    ARTIFACT_NO_RP_EVAL_DATA = "暂无追读力评估数据"
    ARTIFACT_RP_EVAL_TITLE = "追读力评估"

    # ── Report: Alignment ─────────────────────────────────────────────
    ALIGNMENT_TITLE = "对齐报告"
    ALIGNMENT_REPAIR_SUGGESTIONS = "修复建议"

    # ── Report: Quality Eval ──────────────────────────────────────────
    QUALITY_EVAL_TITLE = "质量评估报告"
    QUALITY_EVAL_PASSED = "✓ 通过"
    QUALITY_EVAL_FAILED = "✗ 未通过"
    QUALITY_EVAL_THRESHOLD = "阈值 {threshold:.1f}"
    QUALITY_EVAL_MANUAL_NOTE = (
        "标注「需手动处理」的建议不属于因果/连贯性修复范畴，不会被自动采纳，需人工参考后在正文中手动修改。"
    )
    QUALITY_EVAL_CAUSAL_REPAIR = "因果校验"
    QUALITY_EVAL_CONTINUITY_REPAIR = "连贯性修复"
    QUALITY_EVAL_ADOPTED = "已纳入{module}"
    QUALITY_EVAL_MANUAL_REQUIRED = "需手动处理"

    # ── Report: Bridge ────────────────────────────────────────────────
    BRIDGE_TITLE = "章节桥接"
    BRIDGE_CHAPTER_RANGE = "第 {from_ch} 章 → 第 {to_ch} 章"

    # ── Report: Chapter Plan ──────────────────────────────────────────
    PLAN_TITLE = "章节计划"

    # ── Report: Continuity ────────────────────────────────────────────
    CONTINUITY_TITLE = "连贯性报告"
    CONTINUITY_NO_ISSUES = "无问题"
    CONTINUITY_ISSUES_COUNT = "{count} 个问题"
    CONTINUITY_EVIDENCE = "依据：{evidence}"
    CONTINUITY_AFFECTED_CHARS = "涉及角色：{chars}"
    CONTINUITY_MODIFICATION_SCOPE = "修改范围：{scope}"

    # ── Report: Guard ─────────────────────────────────────────────────
    GUARD_TITLE = "第 {chapter} 章 · AI 护栏"
    GUARD_UNKNOWN = "未知"
    GUARD_REASONING = "判定理由"

    # ── Report: Causal Chain ──────────────────────────────────────────
    CAUSAL_TITLE = "因果链报告"
    CAUSAL_CHAIN_INTACT = "因果链完好"
    CAUSAL_VERIFIED = "✓ 承接已核实"
    CAUSAL_NOT_VERIFIED = "✗ 承接未核实"
    CAUSAL_LOCATION = "位置：{location}"
    CAUSAL_EVIDENCE = "依据：{evidence}"

    # ── Report: Creative Summary ──────────────────────────────────────
    CREATIVE_SUMMARY_TITLE = "创作总结"
    CREATIVE_HIGHLIGHTS = "创作亮点"
    CREATIVE_MUST_CARRY = "必须承接"
    CREATIVE_BRIDGE_HINTS = "桥接线索"
    CREATIVE_NEXT_SUGGESTION = "下一章建议"
    CREATIVE_PLOT_DEVIATIONS = "情节偏移 · {count} 项"
    CREATIVE_DEVIATION_MAJOR = "重大"
    CREATIVE_DEVIATION_MODERATE = "中等"
    CREATIVE_DEVIATION_MINOR = "轻微"
    CREATIVE_PLAN_LABEL = "计划："
    CREATIVE_ACTUAL_LABEL = "实际："
    CREATIVE_REASON_LABEL = "原因："
    CREATIVE_IMPACT_LABEL = "影响："
    CREATIVE_NEW_CHARACTERS = "新增角色 · {count}"
    CREATIVE_UNKNOWN_CHAR = "未知"
    CREATIVE_RELATIONSHIP_TEXT = "关系：{rel}"
    CREATIVE_NEW_SETTINGS = "新增设定"
    CREATIVE_LOCATION_LABEL = "场景：{locations}"
    CREATIVE_ITEM_LABEL = "物件：{items}"
    CREATIVE_STATE_CHANGES = "角色状态变化 · {count}"
    CREATIVE_EMOTION_LABEL = "情绪：{emotion}"
    CREATIVE_SHORT_TERM_GOAL = "短期目标：{goal}"
    CREATIVE_RELATIONSHIP_CHANGES = "关系变化 · {count}"
    CREATIVE_TRUST_LABEL = "信任 {trust:.2f}"
    CREATIVE_TENSION_LABEL = "张力 {tension:.2f}"
    CREATIVE_PLOT_THREAD_UPDATES = "情节线更新 · {count}"

    # ── Report: Generic ───────────────────────────────────────────────
    REPORT_GENERIC_TITLE = "报告"
    REPORT_EMPTY_VALUE = "（空）"
    REPORT_SECTION_TITLE = "报告"

    # ── Sleep Inhibitor ───────────────────────────────────────────────
    SLEEP_INHIBIT_REASON = "NIMO — AI 创作任务运行中"

    # ── Files ─────────────────────────────────────────────────────────
    FILES_LEGACY_MEMORY_CLEANUP = "清理遗留路径：旧版本 project_memory.json 曾被错误写到 CWD/{project_id}/"
    FILES_LEGACY_MEMORY_PARENT = "即 storage_root 的父目录下同名目录"

    # ── Chapter Studio: ScrollArea Note ───────────────────────────────
    CS_SCROLLAREA_NOTE = (
        "Surface(\"panel\") 会添加 QGraphicsDropShadowEffect，\n"
        "该效果会让整个子树走离屏渲染路径，在 macOS 上导致\n"
        "QScrollArea viewport 出现合成伪影（交替深色遮挡条纹）。\n"
        "轨道面板通过 border + background 已有足够层次感，无需阴影。"
    )

    # ── Report: Age Formatting ────────────────────────────────────────
    AGE_FORMAT = "{age}岁"

    # ── Report: KV Labels (common) ────────────────────────────────────
    KV_DIALOGUE_RATIO = "对话占比"
    KV_PACE_MODE = "节奏模式"
    KV_EMOTIONAL_STYLE = "情绪风格"
    KV_ENVIRONMENT_RATIO = "环境描写"
    KV_INFO_DENSITY = "信息密度"
    KV_PREFERRED_TYPE = "偏好类型"
    KV_STRENGTH_BASELINE = "强度基准"
    KV_CHAPTER_END_HOOK = "章末必须钩子"
    KV_PREFERRED_MODE = "偏好模式"
    KV_PAYOFF_DENSITY = "爽点密度"
    KV_PREFERRED_PAYOFF_TYPE = "偏好类型"
    KV_MIN_PAYOFF_COUNT = "每章最低"
    KV_PAYOFF_COUNT_UNIT = "个"
    KV_QUEST_MAX_CONSECUTIVE = "Quest线最大连续"
    KV_FIRE_MAX_ABSENT = "Fire线最大断档"
    KV_CONSTELLATION_MAX_ABSENT = "Constellation线最大断档"
    KV_STAGNATION_THRESHOLD = "停滞预警阈值"
    KV_MIN_TENSION_CHAPTERS = "低张力上限"
    KV_CLIMAX_SPACING = "高潮间隔"
    KV_HOOK_STRONG = "强钩子"
    KV_HOOK_MEDIUM = "中钩子"
    KV_HOOK_WEAK = "弱钩子"
    KV_PAYOFF_CAP = "兑现计分上限"
    KV_TRANSITION_PENALTY = "过渡章惩罚"
    KV_WINDOW_SIZE = "窗口大小"
    KV_LEFT_OFFSET = "左偏移"
    KV_RIGHT_OFFSET = "右偏移"
    KV_DELAY_THRESHOLD = "延迟阈值"
    KV_FORCE_RESOLVE_THRESHOLD = "强制兑现"
    KV_ALTERNATION_THRESHOLD = "交替阈值"
    KV_MAX_CONSECUTIVE_SAME_HOOK = "最大连续同类型"
    KV_TENSION_DEVIATION_TOLERANCE = "偏差容忍度"
    KV_TENSION_RECOVERY_FACTOR = "恢复因子"
    KV_HOOK_STRENGTH = "钩子强度"
    KV_PAYOFF_DENSITY_WEIGHT = "兑现密度"
    KV_SUSPENSE_TIMING = "悬念时机"
    KV_HOOK_ALTERNATION_WEIGHT = "钩子交替"
    KV_TENSION_MATCH_WEIGHT = "张力匹配"
    KV_CRITICAL_THRESHOLD = "临界阈值"
    KV_WARNING_THRESHOLD = "警告阈值"
    KV_NEXT_DRIVE_REASON = "下一章驱动力"
    KV_TRANSITION_CHAPTER = "过渡章"

    # ── Report: Spec ──────────────────────────────────────────────────
    SPEC_TITLE = "故事规格"
    SPEC_THEME_OVERVIEW = "主题概述"
    SPEC_CHARACTERS_HINT = "角色提示"
    SPEC_WORLD_HINT = "世界观提示"
    SPEC_CONFLICT_HINT = "冲突提示"
    SPEC_POV_HINT = "视角提示"
    SPEC_OPENING_STYLE = "开篇风格"
    SPEC_ENDING_STYLE = "收束风格"
    SPEC_EXTRA_INSTRUCTIONS = "附加指令"

    # ── Report: World Bible ───────────────────────────────────────────
    WORLD_BIBLE_TITLE = "世界观设定"

    # ── Report: Chapter Number Format ─────────────────────────────────
    CHAPTER_NUMBER_FORMAT = "第 {num} 章"
    CHAPTER_NUMBER_FORMAT_DEEP = "第{num}章"

    # ── Report: Memory Diagnostic Chapter Title ───────────────────────
    MEM_DIAG_CHAPTER_TITLE = "第 {chapter} 章"
    MEM_DIAG_SUBTITLE = "记忆诊断"

    # ── Report: Component Tags ────────────────────────────────────────
    TAG_OK = "复用历史"
    TAG_NO_DATA = "无来源数据"
    TAG_NONE = "无"
    TAG_NO_ATTACHED = "无附加信号"

    # ── Report: State Packet ──────────────────────────────────────────
    STATE_PACKET_TITLE = "状态包"

    # ── Report: Version Diff ──────────────────────────────────────────
    VERSION_DIFF_TITLE = "版本对比"

    # ── Report: Book Consistency ──────────────────────────────────────
    BOOK_CONSISTENCY_TITLE = "全书一致性报告"
    BOOK_CONSISTENCY_REPAIR_TITLE = "全书一致性修复报告"

    # ── Report: Outline ───────────────────────────────────────────────
    OUTLINE_TITLE = "全书大纲"

    # ── Report: Short Blueprint ───────────────────────────────────────
    SHORT_BLUEPRINT_TITLE = "短篇蓝图"

    # ── Report: Short Creative Summary ────────────────────────────────
    SHORT_CREATIVE_SUMMARY_TITLE = "短篇创作摘要"
