"""Reusable desktop UI components — backward-compatible re-export layer.

All component implementations have been moved to ``novel_forge.desktop.components``.
This module re-exports everything so existing imports continue to work unchanged.
"""

from __future__ import annotations

# Re-export everything from the components sub-package
from novel_forge.desktop.components import (
    ActionButton,
    Badge,
    CheckpointDialog,
    CollapsibleSection,
    EmptyState,
    FilterChip,
    FormFieldWithHint,
    MessageBoxAction,
    MetricCard,
    PaintedFloatingSurface,
    PipelineStep,
    ScrollPage,
    SectionHeading,
    SettingRow,
    StepDotState,
    StepIndicatorRow,
    StepIndicatorState,
    Surface,
    _FadeTopOverlay,
    _style_message_box_button,
    add_card_grid,
    add_setting_group_description,
    add_setting_group_header,
    ask_confirmation,
    build_checkpoint_dialog_content,
    build_checkpoint_summary_text,
    clear_layout,
    make_combo_setting,
    make_float_setting,
    make_line_setting,
    make_nested_setting_section,
    make_spin_setting,
    show_critical_message,
    show_info_message,
    show_message_box,
    show_multiline_input_dialog,
    show_structured_result_dialog,
    show_text_input_dialog,
    show_warning_message,
)

__all__ = [
    "ActionButton",
    "Badge",
    "CheckpointDialog",
    "CollapsibleSection",
    "EmptyState",
    "FilterChip",
    "FormFieldWithHint",
    "MessageBoxAction",
    "MetricCard",
    "PaintedFloatingSurface",
    "PipelineStep",
    "ScrollPage",
    "SectionHeading",
    "SettingRow",
    "StepDotState",
    "StepIndicatorRow",
    "StepIndicatorState",
    "Surface",
    "_FadeTopOverlay",
    "_style_message_box_button",
    "add_card_grid",
    "add_setting_group_description",
    "add_setting_group_header",
    "ask_confirmation",
    "build_checkpoint_dialog_content",
    "build_checkpoint_summary_text",
    "clear_layout",
    "make_combo_setting",
    "make_float_setting",
    "make_line_setting",
    "make_nested_setting_section",
    "make_spin_setting",
    "show_critical_message",
    "show_info_message",
    "show_message_box",
    "show_multiline_input_dialog",
    "show_structured_result_dialog",
    "show_text_input_dialog",
    "show_warning_message",
]
