"""Built-in audio plugin manifests.

The catalogue is descriptive only: it never imports model frameworks or
downloads weights.  Runtime adapters remain isolated behind sidecars/CLIs.
"""

from __future__ import annotations

from novel_forge.tts.platform.schemas import (
    AudioCapability,
    AudioExecution,
    AudioMemoryClass,
    AudioPluginCapabilities,
    AudioPluginManifest,
    AudioPluginQuality,
    AudioPluginRuntime,
    AudioQualityClass,
    TimelineGranularity,
)


def _manifest(
    plugin_id: str,
    display_name: str,
    provider_id: str,
    model_id: str,
    *,
    services: set[AudioCapability],
    execution: AudioExecution,
    offline: bool,
    languages: set[str] | None = None,
    granularity: set[TimelineGranularity] | None = None,
    known_text_alignment: bool = False,
    confidence: bool = False,
    streaming: bool = False,
    mixed_language: bool = False,
    accelerators: set[str] | None = None,
    memory: AudioMemoryClass = AudioMemoryClass.MEDIUM,
    managed_by_app: bool = False,
    profile: AudioQualityClass = AudioQualityClass.BALANCED,
    quality: float = 0.7,
    latency: float = 0.6,
    priority: int = 50,
    endpoint_setting: str = "",
    default_endpoint: str = "",
    credential_settings: list[str] | None = None,
    plugin_version: str = "builtin-v1",
    description: str = "",
    license_summary: str = "",
    tags: set[str] | None = None,
) -> AudioPluginManifest:
    return AudioPluginManifest(
        plugin_id=plugin_id,
        display_name=display_name,
        provider_id=provider_id,
        model_id=model_id,
        plugin_version=plugin_version,
        description=description,
        capabilities=AudioPluginCapabilities(
            services=services,
            languages=languages or {"*"},
            granularity=granularity or set(),
            known_text_alignment=known_text_alignment,
            confidence=confidence,
            streaming=streaming,
            offline=offline,
            mixed_language=mixed_language,
        ),
        runtime=AudioPluginRuntime(
            execution=execution,
            accelerators=accelerators or {"cpu"},
            memory_class=memory,
            managed_by_app=managed_by_app,
            endpoint_setting=endpoint_setting,
            default_endpoint=default_endpoint,
            credential_settings=credential_settings or [],
        ),
        quality=AudioPluginQuality(
            profile=profile,
            quality_score=quality,
            latency_score=latency,
            priority=priority,
        ),
        license_summary=license_summary,
        tags=tags or set(),
    )


def builtin_audio_plugin_manifests() -> tuple[AudioPluginManifest, ...]:
    """Return a fresh immutable-by-convention built-in catalogue."""

    c = AudioCapability
    g = TimelineGranularity
    return (
        _manifest(
            "minimax-speech-2.8-hd",
            "MiniMax Speech 2.8 HD",
            "minimax",
            "speech-2.8-hd",
            services={c.SPEECH_SYNTHESIS, c.VOICE_CLONE, c.VOICE_DESIGN},
            execution=AudioExecution.CLOUD_API,
            offline=False,
            mixed_language=True,
            streaming=True,
            accelerators={"cloud"},
            memory=AudioMemoryClass.LIGHT,
            profile=AudioQualityClass.PRODUCTION,
            quality=0.92,
            latency=0.72,
            priority=90,
            default_endpoint="https://api.minimax.io",
            credential_settings=["tts_minimax_api_key", "minimax_api_key"],
            tags={"platform-native", "cloud", "formal", "interjection", "continuous-sound"},
        ),
        _manifest(
            "minimax-speech-2.8-turbo",
            "MiniMax Speech 2.8 Turbo",
            "minimax",
            "speech-2.8-turbo",
            services={c.SPEECH_SYNTHESIS, c.VOICE_CLONE, c.VOICE_DESIGN},
            execution=AudioExecution.CLOUD_API,
            offline=False,
            mixed_language=True,
            streaming=True,
            accelerators={"cloud"},
            memory=AudioMemoryClass.LIGHT,
            profile=AudioQualityClass.PRODUCTION,
            quality=0.88,
            latency=0.85,
            priority=88,
            default_endpoint="https://api.minimax.io",
            credential_settings=["tts_minimax_api_key", "minimax_api_key"],
            tags={"platform-native", "cloud", "formal", "interjection", "fast", "continuous-sound"},
        ),
        _manifest(
            "minimax-speech-2.6-hd",
            "MiniMax Speech 2.6 HD",
            "minimax",
            "speech-2.6-hd",
            services={c.SPEECH_SYNTHESIS, c.VOICE_CLONE, c.VOICE_DESIGN},
            execution=AudioExecution.CLOUD_API,
            offline=False,
            mixed_language=True,
            streaming=True,
            accelerators={"cloud"},
            memory=AudioMemoryClass.LIGHT,
            profile=AudioQualityClass.PRODUCTION,
            quality=0.88,
            latency=0.78,
            priority=86,
            default_endpoint="https://api.minimax.io",
            credential_settings=["tts_minimax_api_key", "minimax_api_key"],
            tags={"platform-native", "cloud", "formal", "low-latency", "fluent-whisper"},
        ),
        _manifest(
            "minimax-speech-2.6-turbo",
            "MiniMax Speech 2.6 Turbo",
            "minimax",
            "speech-2.6-turbo",
            services={c.SPEECH_SYNTHESIS, c.VOICE_CLONE, c.VOICE_DESIGN},
            execution=AudioExecution.CLOUD_API,
            offline=False,
            mixed_language=True,
            streaming=True,
            accelerators={"cloud"},
            memory=AudioMemoryClass.LIGHT,
            profile=AudioQualityClass.BALANCED,
            quality=0.84,
            latency=0.88,
            priority=84,
            default_endpoint="https://api.minimax.io",
            credential_settings=["tts_minimax_api_key", "minimax_api_key"],
            tags={"platform-native", "cloud", "formal", "fast", "fluent-whisper", "voice-chat"},
        ),
        _manifest(
            "minimax-speech-02-hd",
            "MiniMax Speech 02 HD",
            "minimax",
            "speech-02-hd",
            services={c.SPEECH_SYNTHESIS, c.VOICE_CLONE, c.VOICE_DESIGN},
            execution=AudioExecution.CLOUD_API,
            offline=False,
            mixed_language=True,
            streaming=True,
            accelerators={"cloud"},
            memory=AudioMemoryClass.LIGHT,
            profile=AudioQualityClass.PRODUCTION,
            quality=0.86,
            latency=0.76,
            priority=82,
            default_endpoint="https://api.minimax.io",
            credential_settings=["tts_minimax_api_key", "minimax_api_key"],
            tags={"platform-native", "cloud", "formal", "high-fidelity"},
        ),
        _manifest(
            "minimax-speech-02-turbo",
            "MiniMax Speech 02 Turbo",
            "minimax",
            "speech-02-turbo",
            services={c.SPEECH_SYNTHESIS, c.VOICE_CLONE, c.VOICE_DESIGN},
            execution=AudioExecution.CLOUD_API,
            offline=False,
            mixed_language=True,
            streaming=True,
            accelerators={"cloud"},
            memory=AudioMemoryClass.LIGHT,
            profile=AudioQualityClass.BALANCED,
            quality=0.82,
            latency=0.86,
            priority=80,
            default_endpoint="https://api.minimax.io",
            credential_settings=["tts_minimax_api_key", "minimax_api_key"],
            tags={"platform-native", "cloud", "formal", "fast", "multilingual"},
        ),
        _manifest(
            "dashscope-qwen-audio-3-tts-plus",
            "百炼 Qwen Audio 3.0 TTS Plus",
            "dashscope",
            "qwen-audio-3.0-tts-plus",
            services={c.SPEECH_SYNTHESIS, c.VOICE_CLONE},
            execution=AudioExecution.CLOUD_API,
            offline=False,
            mixed_language=True,
            accelerators={"cloud"},
            memory=AudioMemoryClass.LIGHT,
            profile=AudioQualityClass.PRODUCTION,
            quality=0.93,
            latency=0.80,
            priority=92,
            credential_settings=["tts_dashscope_api_key"],
            tags={"platform-native", "cloud", "formal", "instruction-control"},
        ),
        _manifest(
            "dashscope-qwen-audio-3-tts-flash",
            "百炼 Qwen Audio 3.0 TTS Flash",
            "dashscope",
            "qwen-audio-3.0-tts-flash",
            services={c.SPEECH_SYNTHESIS, c.VOICE_CLONE},
            execution=AudioExecution.CLOUD_API,
            offline=False,
            mixed_language=True,
            accelerators={"cloud"},
            memory=AudioMemoryClass.LIGHT,
            profile=AudioQualityClass.BALANCED,
            quality=0.88,
            latency=0.91,
            priority=88,
            credential_settings=["tts_dashscope_api_key"],
            tags={"platform-native", "cloud", "preview", "fast", "instruction-control"},
        ),
        _manifest(
            "dashscope-cosyvoice-v3.5-plus",
            "百炼 CosyVoice 3.5 Plus",
            "dashscope",
            "cosyvoice-v3.5-plus",
            services={c.SPEECH_SYNTHESIS, c.VOICE_CLONE, c.VOICE_DESIGN},
            execution=AudioExecution.CLOUD_API,
            offline=False,
            mixed_language=True,
            accelerators={"cloud"},
            memory=AudioMemoryClass.LIGHT,
            profile=AudioQualityClass.PRODUCTION,
            quality=0.92,
            latency=0.78,
            priority=91,
            credential_settings=["tts_dashscope_api_key"],
            tags={"platform-native", "cloud", "formal", "instruction-control"},
        ),
        _manifest(
            "dashscope-cosyvoice-v3.5-flash",
            "百炼 CosyVoice 3.5 Flash",
            "dashscope",
            "cosyvoice-v3.5-flash",
            services={c.SPEECH_SYNTHESIS, c.VOICE_CLONE, c.VOICE_DESIGN},
            execution=AudioExecution.CLOUD_API,
            offline=False,
            mixed_language=True,
            accelerators={"cloud"},
            memory=AudioMemoryClass.LIGHT,
            profile=AudioQualityClass.BALANCED,
            quality=0.86,
            latency=0.90,
            priority=85,
            credential_settings=["tts_dashscope_api_key"],
            tags={"platform-native", "cloud", "preview", "fast", "instruction-control"},
        ),
        _manifest(
            "dashscope-qwen3-tts-flash",
            "百炼 Qwen3 TTS Flash",
            "dashscope",
            "qwen3-tts-flash",
            services={c.SPEECH_SYNTHESIS},
            execution=AudioExecution.CLOUD_API,
            offline=False,
            mixed_language=True,
            accelerators={"cloud"},
            memory=AudioMemoryClass.LIGHT,
            profile=AudioQualityClass.BALANCED,
            quality=0.88,
            latency=0.90,
            priority=86,
            credential_settings=["tts_dashscope_api_key"],
            tags={"platform-native", "cloud", "preview", "multilingual"},
        ),
        _manifest(
            "dashscope-qwen3-tts-instruct-flash",
            "百炼 Qwen3 TTS Instruct Flash",
            "dashscope",
            "qwen3-tts-instruct-flash",
            services={c.SPEECH_SYNTHESIS},
            execution=AudioExecution.CLOUD_API,
            offline=False,
            mixed_language=True,
            accelerators={"cloud"},
            memory=AudioMemoryClass.LIGHT,
            profile=AudioQualityClass.PRODUCTION,
            quality=0.92,
            latency=0.84,
            priority=90,
            credential_settings=["tts_dashscope_api_key"],
            tags={"platform-native", "cloud", "formal", "instruction-control", "multilingual"},
        ),
        _manifest(
            "dashscope-qwen3-tts-vc-2026-01-22",
            "百炼 Qwen3 TTS VC 2026-01-22",
            "dashscope",
            "qwen3-tts-vc-2026-01-22",
            services={c.SPEECH_SYNTHESIS, c.VOICE_CLONE},
            execution=AudioExecution.CLOUD_API,
            offline=False,
            mixed_language=True,
            accelerators={"cloud"},
            memory=AudioMemoryClass.LIGHT,
            profile=AudioQualityClass.PRODUCTION,
            quality=0.92,
            latency=0.82,
            priority=89,
            credential_settings=["tts_dashscope_api_key"],
            tags={"platform-native", "cloud", "formal", "voice-clone", "multilingual"},
        ),
        _manifest(
            "dashscope-qwen3-tts-vd-2026-01-26",
            "百炼 Qwen3 TTS VD 2026-01-26",
            "dashscope",
            "qwen3-tts-vd-2026-01-26",
            services={c.SPEECH_SYNTHESIS, c.VOICE_DESIGN},
            execution=AudioExecution.CLOUD_API,
            offline=False,
            mixed_language=True,
            accelerators={"cloud"},
            memory=AudioMemoryClass.LIGHT,
            profile=AudioQualityClass.PRODUCTION,
            quality=0.92,
            latency=0.82,
            priority=89,
            credential_settings=["tts_dashscope_api_key"],
            tags={"platform-native", "cloud", "formal", "voice-design", "multilingual"},
        ),
        _manifest(
            "dashscope-cosyvoice-v3-plus",
            "DashScope CosyVoice v3 Plus（兼容）",
            "dashscope",
            "cosyvoice-v3-plus",
            services={c.SPEECH_SYNTHESIS, c.VOICE_CLONE, c.VOICE_DESIGN},
            execution=AudioExecution.CLOUD_API,
            offline=False,
            mixed_language=True,
            accelerators={"cloud"},
            memory=AudioMemoryClass.LIGHT,
            profile=AudioQualityClass.BALANCED,
            quality=0.80,
            latency=0.78,
            priority=62,
            credential_settings=["tts_dashscope_api_key"],
            tags={"platform-native", "cloud", "legacy-compatible"},
        ),
        _manifest(
            "tencent-cloud-tts",
            "腾讯云语音合成",
            "tencent",
            "text-to-voice",
            services={c.SPEECH_SYNTHESIS},
            execution=AudioExecution.CLOUD_API,
            offline=False,
            languages={"zh", "en", "yue"},
            accelerators={"cloud"},
            memory=AudioMemoryClass.LIGHT,
            profile=AudioQualityClass.BALANCED,
            quality=0.78,
            latency=0.84,
            priority=76,
            tags={"platform-native", "cloud", "ssml", "formal"},
        ),
        _manifest(
            "volcengine-agent-plan-seed-tts-2.0",
            "火山方舟 Agent Plan·豆包 Seed TTS 2.0",
            "volcengine_ark",
            "doubao-seed-tts-2.0",
            services={c.SPEECH_SYNTHESIS},
            execution=AudioExecution.CLOUD_API,
            offline=False,
            languages={"zh", "en", "ja", "id", "es", "yue"},
            mixed_language=True,
            streaming=True,
            accelerators={"cloud"},
            memory=AudioMemoryClass.LIGHT,
            profile=AudioQualityClass.PRODUCTION,
            quality=0.9,
            latency=0.9,
            priority=88,
            endpoint_setting="tts_volcengine_base_url",
            default_endpoint=("https://openspeech.bytedance.com/api/v3/plan/tts/unidirectional"),
            credential_settings=["volcengine_ark_api_key"],
            tags={"platform-native", "cloud", "instruction-control", "formal"},
        ),
        _manifest(
            "mimo-v2.5-tts",
            "Xiaomi MiMo V2.5 TTS",
            "mimo",
            "mimo-v2.5-tts",
            services={c.SPEECH_SYNTHESIS},
            execution=AudioExecution.CLOUD_API,
            offline=False,
            languages={"zh", "en"},
            mixed_language=True,
            streaming=True,
            accelerators={"cloud"},
            memory=AudioMemoryClass.LIGHT,
            profile=AudioQualityClass.PRODUCTION,
            quality=0.88,
            latency=0.82,
            priority=85,
            endpoint_setting="tts_mimo_base_url",
            default_endpoint="https://api.xiaomimimo.com/v1",
            credential_settings=["tts_mimo_api_key"],
            tags={"platform-native", "cloud", "instruction-control", "formal"},
        ),
        _manifest(
            "cosyvoice-3-local",
            "CosyVoice 3 本地运行时",
            "cosyvoice",
            "FunAudioLLM/Fun-CosyVoice3-0.5B-2512",
            services={c.SPEECH_SYNTHESIS, c.VOICE_CLONE},
            execution=AudioExecution.LOCAL_SIDECAR,
            offline=True,
            languages={"*"},
            mixed_language=True,
            accelerators={"cpu", "cuda", "mps"},
            memory=AudioMemoryClass.MEDIUM,
            profile=AudioQualityClass.PRODUCTION,
            quality=0.84,
            latency=0.78,
            priority=83,
            endpoint_setting="tts_cosyvoice_base_url",
            tags={"platform-native", "local", "formal"},
        ),
        _manifest(
            "openvoice-v2-local",
            "OpenVoice V2 本地运行时",
            "openvoice",
            "openvoice-v2",
            services={c.SPEECH_SYNTHESIS, c.VOICE_CLONE},
            execution=AudioExecution.LOCAL_RUNTIME,
            offline=True,
            languages={"zh", "en", "es", "fr", "ja", "ko"},
            accelerators={"cpu", "cuda"},
            memory=AudioMemoryClass.MEDIUM,
            profile=AudioQualityClass.BALANCED,
            quality=0.76,
            latency=0.7,
            priority=72,
            tags={"platform-native", "local", "formal"},
        ),
        _manifest(
            "local-compatible-tts",
            "本地兼容 TTS 服务",
            "local",
            "default",
            services={c.SPEECH_SYNTHESIS},
            execution=AudioExecution.LOCAL_SIDECAR,
            offline=True,
            languages={"*"},
            accelerators={"cpu", "cuda", "mps"},
            memory=AudioMemoryClass.MEDIUM,
            profile=AudioQualityClass.BALANCED,
            quality=0.7,
            latency=0.7,
            priority=60,
            endpoint_setting="tts_local_base_url",
            tags={"dynamic-capabilities", "local", "formal"},
        ),
        _manifest(
            "mock-tts",
            "模拟 TTS",
            "mock",
            "mock-model",
            services={c.SPEECH_SYNTHESIS},
            execution=AudioExecution.BUILTIN,
            offline=True,
            languages={"*"},
            accelerators={"cpu"},
            memory=AudioMemoryClass.LIGHT,
            profile=AudioQualityClass.PREVIEW,
            quality=0.1,
            latency=1.0,
            priority=1,
            tags={"test", "formal"},
        ),
        _manifest(
            "qwen3-tts-0.6b-customvoice",
            "Qwen3-TTS 0.6B CustomVoice",
            "qwen3",
            "Qwen/Qwen3-TTS-12Hz-0.6B-CustomVoice",
            services={c.SPEECH_SYNTHESIS},
            execution=AudioExecution.LOCAL_SIDECAR,
            offline=True,
            mixed_language=True,
            accelerators={"cpu", "cuda", "mps"},
            memory=AudioMemoryClass.MEDIUM,
            managed_by_app=True,
            profile=AudioQualityClass.PREVIEW,
            quality=0.72,
            latency=0.9,
            priority=60,
            endpoint_setting="tts_qwen3_base_url",
            credential_settings=["tts_qwen3_api_key"],
            tags={"backup", "preview", "local"},
        ),
        _manifest(
            "qwen3-tts-1.7b-customvoice",
            "Qwen3-TTS 1.7B CustomVoice",
            "qwen3",
            "Qwen/Qwen3-TTS-12Hz-1.7B-CustomVoice",
            services={c.SPEECH_SYNTHESIS},
            execution=AudioExecution.LOCAL_SIDECAR,
            offline=True,
            mixed_language=True,
            accelerators={"cpu", "cuda", "mps"},
            memory=AudioMemoryClass.HIGH,
            managed_by_app=True,
            profile=AudioQualityClass.BALANCED,
            quality=0.82,
            latency=0.62,
            priority=68,
            endpoint_setting="tts_qwen3_base_url",
            credential_settings=["tts_qwen3_api_key"],
            tags={"backup", "local", "formal"},
        ),
        _manifest(
            "qwen3-tts-1.7b-voice-design",
            "Qwen3-TTS 1.7B VoiceDesign",
            "qwen3",
            "Qwen/Qwen3-TTS-12Hz-1.7B-VoiceDesign",
            services={c.VOICE_DESIGN},
            execution=AudioExecution.LOCAL_SIDECAR,
            offline=True,
            accelerators={"cpu", "cuda", "mps"},
            memory=AudioMemoryClass.HIGH,
            managed_by_app=True,
            profile=AudioQualityClass.BALANCED,
            quality=0.8,
            priority=55,
            endpoint_setting="tts_qwen3_base_url",
            credential_settings=["tts_qwen3_api_key"],
            tags={"backup", "local"},
        ),
        _manifest(
            "qwen3-tts-1.7b-base",
            "Qwen3-TTS 1.7B Base",
            "qwen3",
            "Qwen/Qwen3-TTS-12Hz-1.7B-Base",
            services={c.SPEECH_SYNTHESIS, c.VOICE_CLONE},
            execution=AudioExecution.LOCAL_SIDECAR,
            offline=True,
            accelerators={"cpu", "cuda", "mps"},
            memory=AudioMemoryClass.HIGH,
            managed_by_app=True,
            profile=AudioQualityClass.BALANCED,
            quality=0.82,
            priority=58,
            endpoint_setting="tts_qwen3_base_url",
            credential_settings=["tts_qwen3_api_key"],
            tags={"backup", "local"},
        ),
        _manifest(
            "qwen3-asr-0.6b",
            "Qwen3-ASR 0.6B",
            "qwen3-asr",
            "Qwen/Qwen3-ASR-0.6B",
            services={c.ASR},
            execution=AudioExecution.LOCAL_SIDECAR,
            offline=True,
            languages={"*"},
            granularity={g.SEGMENT, g.TOKEN},
            confidence=True,
            streaming=True,
            mixed_language=True,
            accelerators={"cpu", "cuda", "mps"},
            memory=AudioMemoryClass.MEDIUM,
            profile=AudioQualityClass.MASTER,
            quality=0.93,
            latency=0.78,
            priority=92,
            endpoint_setting="audio_qwen3_asr_base_url",
            credential_settings=["audio_qwen3_asr_api_key"],
            tags={"backup", "external-runtime", "multilingual", "production"},
        ),
        _manifest(
            "qwen3-forced-aligner-0.6b",
            "Qwen3 ForcedAligner 0.6B",
            "qwen3-asr",
            "Qwen/Qwen3-ForcedAligner-0.6B",
            services={c.FORCED_ALIGNMENT},
            execution=AudioExecution.LOCAL_SIDECAR,
            offline=True,
            languages={"zh", "en", "yue", "fr", "de", "it", "ja", "ko", "pt", "ru", "es"},
            granularity={g.CHARACTER, g.WORD},
            known_text_alignment=True,
            confidence=True,
            mixed_language=True,
            accelerators={"cpu", "cuda", "mps"},
            memory=AudioMemoryClass.MEDIUM,
            profile=AudioQualityClass.MASTER,
            quality=0.96,
            latency=0.76,
            priority=98,
            endpoint_setting="audio_qwen3_asr_base_url",
            credential_settings=["audio_qwen3_asr_api_key"],
            tags={"backup", "external-runtime", "known-text", "production", "master"},
        ),
        _manifest(
            "whisperx",
            "WhisperX",
            "whisperx",
            "whisperx",
            services={c.ASR, c.FORCED_ALIGNMENT, c.VAD},
            execution=AudioExecution.LOCAL_SIDECAR,
            offline=True,
            languages={"*"},
            granularity={g.WORD, g.SEGMENT},
            known_text_alignment=True,
            confidence=True,
            accelerators={"cpu", "cuda", "mps"},
            memory=AudioMemoryClass.HIGH,
            managed_by_app=True,
            profile=AudioQualityClass.MASTER,
            quality=0.9,
            latency=0.52,
            priority=99,
            endpoint_setting="audio_whisperx_base_url",
            tags={"validator", "language-pack"},
        ),
        _manifest(
            "sherpa-sensevoice-int8",
            "Sherpa ONNX · SenseVoice Int8",
            "sherpa-onnx",
            "sensevoice-zh-en-ja-ko-yue-int8",
            services={c.ASR, c.VAD},
            execution=AudioExecution.LOCAL_SIDECAR,
            offline=True,
            languages={"zh", "en", "ja", "ko", "yue"},
            granularity={g.TOKEN, g.CHARACTER, g.SEGMENT},
            confidence=True,
            streaming=True,
            mixed_language=True,
            accelerators={"cpu"},
            memory=AudioMemoryClass.LIGHT,
            managed_by_app=True,
            profile=AudioQualityClass.PREVIEW,
            quality=0.73,
            latency=0.96,
            priority=80,
            endpoint_setting="audio_sherpa_base_url",
            tags={"preview", "portable", "int8"},
        ),
        _manifest(
            "silero-vad-onnx",
            "Silero VAD · ONNX",
            "sherpa-onnx",
            "silero-vad.onnx",
            services={c.VAD},
            execution=AudioExecution.LOCAL_SIDECAR,
            offline=True,
            languages={"*"},
            granularity={g.SEGMENT},
            confidence=True,
            streaming=True,
            accelerators={"cpu"},
            memory=AudioMemoryClass.LIGHT,
            managed_by_app=True,
            profile=AudioQualityClass.PRODUCTION,
            quality=0.9,
            latency=0.99,
            priority=96,
            endpoint_setting="audio_sherpa_base_url",
            tags={"vad", "portable", "onnx"},
        ),
        _manifest(
            "montreal-forced-aligner",
            "Montreal Forced Aligner",
            "mfa",
            "mfa",
            services={c.FORCED_ALIGNMENT},
            execution=AudioExecution.LOCAL_CLI,
            offline=True,
            languages={"*"},
            granularity={g.WORD},
            known_text_alignment=True,
            confidence=True,
            accelerators={"cpu"},
            memory=AudioMemoryClass.MEDIUM,
            profile=AudioQualityClass.MASTER,
            quality=0.89,
            latency=0.25,
            priority=70,
            tags={"dictionary-required", "manual-escalation"},
        ),
        _manifest(
            "stable-audio-3-small-sfx",
            "Stable Audio 3 Small-SFX",
            "stable_audio",
            "small-sfx",
            services={c.SFX_GENERATION, c.SOUNDSCAPE_GENERATION},
            execution=AudioExecution.LOCAL_CLI,
            offline=True,
            accelerators={"cpu", "cuda", "mps"},
            memory=AudioMemoryClass.HIGH,
            profile=AudioQualityClass.PRODUCTION,
            quality=0.88,
            priority=90,
            tags={"local", "sfx", "soundscape"},
        ),
        _manifest(
            "stable-audio-3-small-music",
            "Stable Audio 3 Small-Music",
            "stable_audio",
            "small-music",
            services={c.MUSIC_GENERATION},
            execution=AudioExecution.LOCAL_CLI,
            offline=True,
            accelerators={"cpu", "cuda", "mps"},
            memory=AudioMemoryClass.HIGH,
            profile=AudioQualityClass.PRODUCTION,
            quality=0.86,
            priority=88,
            tags={"local", "music"},
        ),
        _manifest(
            "ace-step-1.5",
            "ACE-Step 1.5",
            "ace_step",
            "ace-step-1.5",
            services={c.MUSIC_GENERATION},
            execution=AudioExecution.LOCAL_CLI,
            offline=True,
            accelerators={"cpu", "cuda", "mps"},
            memory=AudioMemoryClass.MEDIUM,
            profile=AudioQualityClass.PRODUCTION,
            quality=0.88,
            latency=0.35,
            priority=89,
            license_summary="MIT license; validate model-weight terms before release.",
            tags={"local", "music", "instrumental"},
        ),
        _manifest(
            "minimax-music-3.0",
            "MiniMax Music 3.0",
            "minimax_music",
            "music-3.0",
            services={c.MUSIC_GENERATION, c.SOUNDSCAPE_GENERATION},
            execution=AudioExecution.CLOUD_API,
            offline=False,
            accelerators={"cloud"},
            memory=AudioMemoryClass.LIGHT,
            profile=AudioQualityClass.PRODUCTION,
            quality=0.94,
            latency=0.42,
            priority=92,
            endpoint_setting="sound_generation_minimax_music_endpoint",
            credential_settings=[
                "sound_generation_minimax_api_key",
                "tts_minimax_api_key",
                "minimax_api_key",
            ],
            tags={"long-form", "cloud", "recommended"},
        ),
        _manifest(
            "minimax-music-2.6",
            "MiniMax Music 2.6",
            "minimax_music",
            "music-2.6",
            services={c.MUSIC_GENERATION, c.SOUNDSCAPE_GENERATION},
            execution=AudioExecution.CLOUD_API,
            offline=False,
            accelerators={"cloud"},
            memory=AudioMemoryClass.LIGHT,
            profile=AudioQualityClass.PRODUCTION,
            quality=0.9,
            latency=0.45,
            priority=88,
            endpoint_setting="sound_generation_minimax_music_endpoint",
            credential_settings=[
                "sound_generation_minimax_api_key",
                "tts_minimax_api_key",
                "minimax_api_key",
            ],
            tags={"long-form", "cloud", "legacy"},
        ),
        _manifest(
            "ffmpeg-smart-mixer",
            "FFmpeg 智能多轨渲染器",
            "builtin",
            "ffmpeg-filter-complex",
            services={c.AUDIO_RENDER},
            execution=AudioExecution.BUILTIN,
            offline=True,
            accelerators={"cpu"},
            memory=AudioMemoryClass.LIGHT,
            profile=AudioQualityClass.MASTER,
            quality=0.95,
            latency=0.86,
            priority=98,
            tags={"stem", "ducking", "loudness"},
        ),
        _manifest(
            "builtin-audio-quality-gate",
            "成片音频质量门",
            "builtin",
            "audio-quality-gate-v1",
            services={c.QUALITY_EVALUATION},
            execution=AudioExecution.BUILTIN,
            offline=True,
            accelerators={"cpu"},
            memory=AudioMemoryClass.LIGHT,
            profile=AudioQualityClass.MASTER,
            quality=0.9,
            latency=0.95,
            priority=99,
            tags={"loudness", "clipping", "alignment"},
        ),
    )
