"""Keep AGENTS.md machine-checkable facts aligned with the repository.

AGENTS.md separates directional guidance from a single machine-generated
``facts`` block (delimited by ``<!-- BEGIN AGENTS-MD-FACTS -->`` and
``<!-- END AGENTS-MD-FACTS -->``).  All checkable facts live only inside that
block; directional sections reference the block instead of repeating numbers.

The facts block is generated from repository truth:

- ``Last scanned`` / ``Commit`` / ``Branch`` come from git HEAD.
- Python version declarations come from ``pyproject.toml``
  ``requires-python`` and the unique ``python-version`` in
  ``.github/workflows/ci.yml``.
- The TaskType member count comes from ``novel_forge/common/constants.py``.
- Test-file counts come from the tracked ``tests/`` tree, grouped by suite
  directory (``unit``, ``integration``, ``desktop``, ``regression``, ``perf``,
  ``e2e``, root-level).

Usage:

- ``python scripts/check_agents_md_drift.py`` — verify the facts block matches
  repository truth.  Errors exit 1 (blocking pre-commit and CI); warnings only
  print.
- ``python scripts/check_agents_md_drift.py --update`` — regenerate the facts
  block in AGENTS.md from repository truth, then exit 0.  Run this after any
  commit that changes the declared facts, then re-run the check (or commit) to
  confirm.
- ``--json`` emits machine-readable output for both modes.

Checks performed in verify mode:

- The facts block must exist (error; run ``--update`` to create it).
- ``Last scanned`` must not be older than the latest commit date beyond
  ``--max-age-days`` (error), with a smaller drift reported as a warning.
- ``Commit`` and ``Branch`` are compared with the current HEAD (warning).
- ``requires >=X.Y`` must match ``pyproject.toml`` ``requires-python`` (error).
- ``CI runs X.Y`` must match the unique ``python-version`` across CI workflows
  (error); multiple distinct versions are an error.
- The TaskType member count must match ``constants.py`` (error).
- Test-file counts (total and per suite) must match the ``tests/`` tree
  (warning; the counts legitimately change often).  A total that cannot be
  explained by the known suite directories is an error: register new suite
  directories in ``_TEST_SUITE_DIRS``.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tomllib
from dataclasses import dataclass
from datetime import date
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]
_AGENTS_MD = _ROOT / "AGENTS.md"
_PYPROJECT_TOML = _ROOT / "pyproject.toml"
_CONSTANTS_PY = _ROOT / "novel_forge" / "common" / "constants.py"

# The facts block is the single machine-owned section of AGENTS.md.  Both
# markers must sit on their own lines, so prose that merely mentions the
# marker names can never be mistaken for a block.
_BEGIN_FACTS = "<!-- BEGIN AGENTS-MD-FACTS: machine-generated by `python scripts/check_agents_md_drift.py --update`; do not edit by hand -->"
_END_FACTS = "<!-- END AGENTS-MD-FACTS -->"
_FACTS_BLOCK_RE = re.compile(
    r"(?m)^[ \t]*<!-- BEGIN AGENTS-MD-FACTS[^>]*-->[ \t]*\r?\n"
    r"(?P<body>.*?)\r?\n"
    r"[ \t]*<!-- END AGENTS-MD-FACTS -->[ \t]*$",
    re.S,
)
# Legacy single-line metadata used before the facts block existed; --update
# replaces it with the full block on upgrade.
_LEGACY_META_RE = re.compile(r"^[ \t]*\*\*Last scanned:\*\*.*$", re.MULTILINE)

# Patterns parse declarations inside the facts block only.  The block is
# rendered as Markdown bold (**Last scanned:** ...), so each pattern allows
# optional asterisks around the label and the value.
_SCANNED_RE = re.compile(r"Last scanned:\**\s*(\d{4}-\d{2}-\d{2})")
_COMMIT_RE = re.compile(r"Commit:\**\s*([0-9a-f]{7,40})")
_BRANCH_RE = re.compile(r"Branch:\**\s*([^*\s]+)")
_REQUIRES_RE = re.compile(r"requires\s+`(>=3\.\d+)`")
_CI_RUNS_RE = re.compile(r"CI runs\s+`(\d+\.\d+)`")
_TASKTYPE_MEMBERS_RE = re.compile(r"TaskType\s+(?:enum|Enum)\s*\((\d+)\s+(?:members|tasks)")
_TEST_FILES_RE = re.compile(
    r"^- (\d+) test files: (\d+) unit, (\d+) integration, (\d+) desktop, "
    r"(\d+) regression, (\d+) perf, (\d+) e2e, (\d+) root-level$",
    re.MULTILINE,
)

# Suite directories whose test files are counted individually; any test file
# outside these groups is reported as an error so new suites are registered
# here explicitly.
_TEST_SUITE_DIRS = ("unit", "integration", "desktop", "regression", "perf", "e2e")


@dataclass(frozen=True)
class Facts:
    """Repository facts that the AGENTS.md facts block must declare."""

    scanned: str
    commit: str
    branch: str
    required_python: str
    ci_versions: set[str]
    tasktype_members: int
    test_counts: dict[str, int]
    unknown_test_dirs: list[str]


def _git(args: list[str]) -> str:
    """Run a read-only git command inside the repository root."""

    result = subprocess.run(
        ["git", *args],
        cwd=_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)} failed: {result.stderr.strip()}")
    return result.stdout.strip()


def _required_python() -> str:
    """Return the ``requires-python`` value declared in pyproject.toml."""

    with _PYPROJECT_TOML.open("rb") as handle:
        return tomllib.load(handle)["project"]["requires-python"]


def _ci_python_versions() -> set[str]:
    """Return the set of python-version values used across CI workflows."""

    values: set[str] = set()
    for workflow in (_ROOT / ".github" / "workflows").glob("*.yml"):
        values.update(
            re.findall(r"python-version:\s*[\"']?(\d+\.\d+)", workflow.read_text(encoding="utf-8"))
        )
    return values


def _tasktype_member_count() -> int:
    """Count TaskType enum members, preferring the real module when importable."""

    try:
        sys.path.insert(0, str(_ROOT))
        from novel_forge.common.constants import TaskType  # noqa: PLC0415

        return len(TaskType)
    except Exception:  # pragma: no cover - import fallback for bare checkouts
        source = _CONSTANTS_PY.read_text(encoding="utf-8")
        match = re.search(r"^class TaskType\b.*\n(?P<body>.*?)(?=^class |\Z)", source, re.M | re.S)
        body = match.group("body") if match else ""
        return len(re.findall(r"^\s{4}[A-Z][A-Z0-9_]*\s*=", body, re.M))


def _test_suite_counts() -> tuple[dict[str, int], list[str]]:
    """Count test files per known suite plus the root level.

    Returns ``(counts, unknown_dirs)`` where ``counts`` has a ``total`` key and
    one key per suite, and ``unknown_dirs`` lists directories that contain test
    files but are not registered in ``_TEST_SUITE_DIRS``.
    """

    counts: dict[str, int] = {}
    for suite in _TEST_SUITE_DIRS:
        counts[suite] = len(list((_ROOT / "tests" / suite).glob("**/test_*.py")))
    counts["root"] = len(list((_ROOT / "tests").glob("test_*.py")))
    counts["total"] = len(list((_ROOT / "tests").glob("**/test_*.py")))

    unknown_dirs: list[str] = []
    for directory in sorted((_ROOT / "tests").glob("*/")):
        if not directory.is_dir():
            continue
        if directory.name in _TEST_SUITE_DIRS or directory.name.startswith("."):
            continue
        if any(directory.glob("**/test_*.py")):
            unknown_dirs.append(directory.name)
    return counts, unknown_dirs


def collect_facts() -> Facts:
    """Collect every fact the AGENTS.md facts block must declare."""

    head_date = _git(["log", "-1", "--format=%ad", "--date=short"])
    test_counts, unknown_dirs = _test_suite_counts()
    return Facts(
        scanned=head_date,
        commit=_git(["rev-parse", "--short", "HEAD"]),
        branch=_git(["rev-parse", "--abbrev-ref", "HEAD"]),
        required_python=_required_python(),
        ci_versions=_ci_python_versions(),
        tasktype_members=_tasktype_member_count(),
        test_counts=test_counts,
        unknown_test_dirs=unknown_dirs,
    )


def _render_facts_block(facts: Facts) -> str:
    """Render the full facts block, markers included."""

    counts = facts.test_counts
    lines = [
        _BEGIN_FACTS,
        f"**Last scanned:** {facts.scanned} | **Commit:** {facts.commit} | **Branch:** {facts.branch}",
        "",
        f"`pyproject.toml` requires `{facts.required_python}`; CI runs "
        f"`{next(iter(sorted(facts.ci_versions)))}`."
        if len(facts.ci_versions) == 1
        else f"`pyproject.toml` requires `{facts.required_python}`; CI python-version values: {sorted(facts.ci_versions)}.",
        "",
        f"TaskType enum ({facts.tasktype_members} members) — canonical list: `novel_forge/common/constants.py`.",
        "",
        f"- {counts['total']} test files: {counts['unit']} unit, {counts['integration']} integration, "
        f"{counts['desktop']} desktop, {counts['regression']} regression, {counts['perf']} perf, "
        f"{counts['e2e']} e2e, {counts['root']} root-level",
        _END_FACTS,
        "",
    ]
    return "\n".join(lines)


def update_agents_md(facts: Facts) -> bool:
    """Regenerate the facts block in AGENTS.md in place; return True if changed.

    Replaces an existing facts block; otherwise replaces the legacy
    ``**Last scanned:**`` metadata line; otherwise inserts the block before the
    first ``## `` section heading.  Writes atomically via a temp file.
    """

    text = _AGENTS_MD.read_text(encoding="utf-8")
    block = _render_facts_block(facts)

    if _FACTS_BLOCK_RE.search(text):
        new_text = _FACTS_BLOCK_RE.sub(lambda _: block.rstrip("\n"), text, count=1)
    elif _LEGACY_META_RE.search(text):
        new_text = _LEGACY_META_RE.sub(block.rstrip("\n"), text, count=1)
    else:
        heading = re.search(r"^## ", text, re.MULTILINE)
        if heading is None:
            new_text = block + text
        else:
            new_text = text[: heading.start()] + block + "\n" + text[heading.start() :]

    if new_text == text:
        return False
    tmp = _AGENTS_MD.with_suffix(".md.tmp")
    tmp.write_text(new_text, encoding="utf-8")
    tmp.replace(_AGENTS_MD)
    return True


def check(max_age_days: int = 30) -> tuple[list[str], list[str]]:
    """Return (errors, warnings); errors fail the check."""

    errors: list[str] = []
    warnings: list[str] = []
    if not _AGENTS_MD.exists():
        return [f"missing {_AGENTS_MD}"], []

    text = _AGENTS_MD.read_text(encoding="utf-8")
    block_match = _FACTS_BLOCK_RE.search(text)
    if block_match is None:
        return [
            "AGENTS.md has no facts block "
            "(`<!-- BEGIN AGENTS-MD-FACTS -->` markers missing); "
            "run `python scripts/check_agents_md_drift.py --update`"
        ], []
    body = block_match.group("body")

    # 1. Scan timestamp vs latest commit date.
    scanned_match = _SCANNED_RE.search(body)
    try:
        head_date = _git(["log", "-1", "--format=%ad", "--date=short"])
        head_commit = _git(["rev-parse", "--short", "HEAD"])
        head_branch = _git(["rev-parse", "--abbrev-ref", "HEAD"])
    except RuntimeError as exc:
        return [f"cannot read git state: {exc}"], []

    if scanned_match:
        drift_days = (
            date.fromisoformat(head_date) - date.fromisoformat(scanned_match.group(1))
        ).days
        if drift_days > max_age_days:
            errors.append(
                f"AGENTS.md Last scanned ({scanned_match.group(1)}) is {drift_days} days older than HEAD ({head_date})"
            )
        elif drift_days > 0:
            warnings.append(
                f"AGENTS.md Last scanned ({scanned_match.group(1)}) lags HEAD by {drift_days} day(s)"
            )
    else:
        errors.append("facts block has no parseable 'Last scanned' date")

    commit_match = _COMMIT_RE.search(body)
    if commit_match and commit_match.group(1) != head_commit:
        warnings.append(
            f"AGENTS.md Commit ({commit_match.group(1)}) differs from HEAD ({head_commit})"
        )
    branch_match = _BRANCH_RE.search(body)
    if branch_match and branch_match.group(1) != head_branch:
        warnings.append(
            f"AGENTS.md Branch ({branch_match.group(1)}) differs from current branch ({head_branch})"
        )

    # 2. Python version declarations vs pyproject.toml and CI.
    try:
        required_python = _required_python()
    except (OSError, KeyError, tomllib.TOMLDecodeError) as exc:
        errors.append(f"cannot read {_PYPROJECT_TOML}: {exc}")
        required_python = ""
    requires_match = _REQUIRES_RE.search(body)
    if requires_match is None:
        errors.append("facts block has no parseable `requires >=X.Y` declaration")
    elif requires_match.group(1) != required_python:
        errors.append(
            f"AGENTS.md requires `{requires_match.group(1)}` differs from pyproject.toml requires-python `{required_python}`"
        )

    ci_versions = _ci_python_versions()
    ci_runs = _CI_RUNS_RE.search(body)
    if len(ci_versions) == 1:
        if ci_runs is None:
            errors.append("facts block has no parseable 'CI runs X.Y' declaration")
        elif ci_runs.group(1) != next(iter(ci_versions)):
            errors.append(
                f"AGENTS.md 'CI runs `{ci_runs.group(1)}`' differs from CI python-version `{next(iter(ci_versions))}`"
            )
    elif len(ci_versions) > 1:
        errors.append(
            f"CI workflows use multiple python-version values ({sorted(ci_versions)}); AGENTS.md cannot declare a single one"
        )

    # 3. TaskType member count vs constants.py.
    actual_tasktypes = _tasktype_member_count()
    tasktype_match = _TASKTYPE_MEMBERS_RE.search(body)
    if tasktype_match is None:
        errors.append("facts block has no parseable TaskType member count")
    elif int(tasktype_match.group(1)) != actual_tasktypes:
        errors.append(
            f"AGENTS.md declares {tasktype_match.group(1)} TaskType members; constants.py has {actual_tasktypes}"
        )

    # 4. Test-file counts vs the tracked tests tree.
    counts, unknown_dirs = _test_suite_counts()
    if unknown_dirs:
        errors.append(
            f"tests/ contains unregistered suite dirs {unknown_dirs} with test files; "
            f"register them in _TEST_SUITE_DIRS in {Path(__file__).name}"
        )
    tests_match = _TEST_FILES_RE.search(body)
    if tests_match is None:
        errors.append("facts block has no parseable test-file count line")
    else:
        declared = [int(group) for group in tests_match.groups()]
        expected = [
            counts["total"],
            counts["unit"],
            counts["integration"],
            counts["desktop"],
            counts["regression"],
            counts["perf"],
            counts["e2e"],
            counts["root"],
        ]
        if declared != expected:
            warnings.append(
                f"AGENTS.md declares {declared[0]} test files "
                f"({declared[1]} unit, {declared[2]} integration, {declared[3]} desktop, "
                f"{declared[4]} regression, {declared[5]} perf, {declared[6]} e2e, {declared[7]} root-level); "
                f"the tests tree has {counts['total']} "
                f"({counts['unit']} unit, {counts['integration']} integration, {counts['desktop']} desktop, "
                f"{counts['regression']} regression, {counts['perf']} perf, {counts['e2e']} e2e, {counts['root']} root-level); "
                "run `python scripts/check_agents_md_drift.py --update`"
            )

    return errors, warnings


def main() -> int:
    """Parse arguments, update or verify the facts block, and report."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--update",
        action="store_true",
        help="regenerate the facts block in AGENTS.md from repository truth",
    )
    parser.add_argument(
        "--max-age-days",
        type=int,
        default=30,
        help="maximum allowed age of the AGENTS.md scan timestamp in days (default: 30)",
    )
    parser.add_argument("--json", action="store_true", help="emit machine-readable JSON")
    args = parser.parse_args()

    try:
        facts = collect_facts()
    except RuntimeError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    if args.update:
        try:
            changed = update_agents_md(facts)
        except OSError as exc:
            print(f"ERROR: cannot update {_AGENTS_MD}: {exc}", file=sys.stderr)
            return 1
        result = {
            "kind": "agents-md-facts-update",
            "status": "updated" if changed else "unchanged",
            "changed": changed,
            "facts": {
                "scanned": facts.scanned,
                "commit": facts.commit,
                "branch": facts.branch,
                "required_python": facts.required_python,
                "ci_versions": sorted(facts.ci_versions),
                "tasktype_members": facts.tasktype_members,
                "test_counts": facts.test_counts,
            },
        }
        if args.json:
            print(json.dumps(result, ensure_ascii=False, indent=2))
        else:
            action = "updated" if changed else "already current"
            print(
                f"OK: facts block {action} in AGENTS.md "
                f"(scanned {facts.scanned}, commit {facts.commit}, {facts.tasktype_members} TaskType members, "
                f"{facts.test_counts['total']} test files)"
            )
        return 0

    errors, warnings = check(max_age_days=args.max_age_days)
    result = {
        "kind": "agents-md-drift-check",
        "status": "fail" if errors else "pass",
        "errors": errors,
        "warnings": warnings,
    }
    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        for message in warnings:
            print(f"WARNING: {message}")
        for message in errors:
            print(f"ERROR: {message}")
        if not errors and not warnings:
            print("OK: AGENTS.md facts block matches the repository")
        elif not errors:
            print("OK: AGENTS.md facts block matches; warnings above are informational")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
