#!/usr/bin/env python3
"""Batch translate Chinese Jinja2 prompt templates to English."""
import os
from pathlib import Path

BASE = str(Path(__file__).resolve().parents[1] / "novel_forge/prompts/packs")
ZH = f"{BASE}/zh/templates"
EN = f"{BASE}/en/templates"

TRANSLATIONS = [
    ("【备注】", "[NOTE]"),
    ("提示词：", "Prompt: "),
    ("类型：宏模块（不被直接渲染，仅供其他模板 import）", "Type: macro module (not rendered directly, for import only)"),
    ("类型：宏模块", "Type: macro module"),
    ("作用简述：", "Purpose: "),
    ("上游输入：", "Upstream inputs:"),
    ("下游输出：", "Downstream outputs:"),
    ("消费链优先级：", "Consumption chain priority:"),
    ("定义宏：", "Defined macros:"),
    ("使用方式：", "Usage:"),
    ("被调用方：", "Called by:"),
    ("文件类型：宏模块（macro module）", "File type: macro module"),
    ("文件类型：宏模块", "File type: macro module"),
    ("## 任务", "## Task"),
    ("## 规划规则", "## Planning Rules"),
    ("## 质量校准", "## Quality Calibration"),
    ("## 交付前核验", "## Pre-Delivery Checklist"),
    ("## 角色身份卡", "## Character Identity Card"),
    ("## 桥接卡", "## Bridge Card"),
    ("## 契约卡", "## Contract Card"),
    ("## 记忆薄片", "## Memory Sliver"),
    ("## 要素薄片", "## Element Sliver"),
    ("## 追读力薄片", "## Reading Power Sliver"),
    ("## 风格/节奏薄片", "## Style/Pace Sliver"),
    ("## 编辑契约卡", "## Editorial Contract Card"),
    ("## 情节线节奏卡", "## Plot Strand Pace Card"),
    ("## 认知约束卡", "## Cognitive Constraint Card"),
    ("## 支线交织卡", "## Subplot Weave Card"),
    ("## 角色知识边界", "## Character Knowledge Boundary"),
    ("## 叙事人称卡", "## Narrative Person Card"),
    ("## 时间连续性卡", "## Time Continuity Card"),
    ("## 母题避重复提示", "## Motif Repetition Avoidance"),
    ("## 表达通道冷却", "## Expression Channel Cooldown"),
    ("## 副线弧光活跃度", "## Subplot Arc Activity"),
    ("## 要素执行回补", "## Element Execution Backfill"),
    ("## 六要素文学合同卡", "## Six-Element Literary Contract Card"),
    ("## 六要素落字段规则", "## Six-Element Field Mapping Rules"),
    ("## 六要素覆盖重试指令", "## Six-Element Coverage Retry Directive"),
    ("## 上次方案失败原因", "## Previous Plan Failure Reason"),
    ("## 顶层字段要求", "## Top-Level Field Requirements"),
    ("## 章节卡", "## Chapter Card"),
    ("## Artifact 消费规则", "## Artifact Consumption Rules"),
    ("## Cast / Emotion 执行规则", "## Cast/Emotion Execution Rules"),
    ("## 跨场景约束输出", "## Cross-Scene Constraint Output"),
    ("## 字段说明", "## Field Description"),
    ("## 写出要求", "## Output Requirements"),
    ("## 角色状态", "## Character Status"),
    ("### 必要叙事要素", "### Required Narrative Elements"),
    ("### 本章重点扩展要素", "### Chapter Focus Extension Elements"),
    ("### 其余扩展要素", "### Remaining Extension Elements"),
    ("### 题材扩展要素", "### Genre Extension Elements"),
    ("## 叙事要素约束", "## Narrative Element Constraints"),
    ("## 叙事要素重点约束", "## Narrative Element Focus Constraints"),
    ("## 本轮修复策略更新", "## This Round Repair Strategy Update"),
    ("## 修复后自检清单", "## Post-Repair Self-Check"),
    ("## 共享证据锚点", "## Shared Evidence Anchor"),
    ("## 全局叙事契约", "## Global Narrative Contract"),
    ("## 节奏与风格约束", "## Pace and Style Constraints"),
    ("### 对话密度要求", "### Dialogue Density Requirements"),
    ("### 对话格式规范", "### Dialogue Format Rules"),
    ("### 说明腔禁止", "### Anti-Exposition Rules"),
    ("### 章尾与悬念洁净", "### Chapter Ending and Suspense Cleanliness"),
    ("### 创造性具体化与反机械句式", "### Creative Specificity and Anti-Mechanical Phrasing"),
    ("### 网文节奏约束", "### Web Novel Pacing Rules"),
    ("### 感官多样性", "### Sensory Diversity"),
    ("### 自称语境意识", "### Self-Reference Context Awareness"),
    ("### 情感工艺", "### Emotional Craft"),
    ("### ⚠️ 意象复用禁止（★ 硬约束）", "### ⚠️ Imagery Repetition Ban (★ Hard Constraint)"),
    ("### ⚠️ 模板化短语黑名单", "### ⚠️ Template Phrase Blacklist"),
    ("### ⚠️ 段落唯一性（★ 硬约束）", "### ⚠️ Paragraph Uniqueness (★ Hard Constraint)"),
    ("## 本模板职责范围", "## This Template Scope"),
    ("## POV 知识边界约束", "## POV Knowledge Boundary Constraints"),
    ("章节：", "Chapter: "),
    ("标题：", "Title: "),
    ("目标：", "Goal: "),
    ("补充说明：", "Notes: "),
    ("场景：", "Setting: "),
    ("目标字数：", "Target word count: "),
    ("主线：", "Main plot: "),
    ("支线：", "Subplot: "),
    ("节拍：", "Beats: "),
    ("入口状态：", "Entry state: "),
    ("必达事件：", "Required events: "),
    ("必达推进：", "Required progressions: "),
    ("允许铺垫：", "Allowed foreshadowing: "),
    ("禁止变化：", "Forbidden changes: "),
    ("禁止提前推进：", "Forbidden early progressions: "),
    ("future_leak_risks：", "future_leak_risks: "),
    ("出口目标：", "Exit targets: "),
    ("完成标准：", "Completion criteria: "),
    ("护栏：", "Guardrails: "),
    ("硬事实：", "Hard facts: "),
    ("契约 POV entity_id：", "Contract POV entity_id: "),
    ("契约 required cast ids：", "Contract required cast ids: "),
    ("契约 support cast ids：", "Contract support cast ids: "),
    ("契约情感执行意图：", "Contract emotional execution intent: "),
    ("契约场景目标：", "Contract scene design goals: "),
    ("未来泄露风险：", "Future leak risks: "),
    ("本章活跃支线：", "Active subplots this chapter: "),
    ("交织/收束提示：", "Weave/resolution hints: "),
    ("依赖警告：", "Dependency warnings: "),
    ("规划要求：", "Planning requirements: "),
    ("时间/地点/POV：", "Time/Location/POV: "),
    ("动作接力：", "Action handoff: "),
    ("情绪余波：", "Emotional carryover: "),
    ("开头验收窗口：", "Opening acceptance window: "),
    ("开头验收条件：", "Opening acceptance criteria: "),
    ("因果链", "Causal chain"),
    ("待推进悬念：", "Pending suspense: "),
    ("开放线索：", "Open threads: "),
    ("待解问题：", "Unresolved questions: "),
    ("已知=", "Known="),
    ("怀疑=", "Suspicions="),
    ("误信=", "Misbeliefs="),
    ("隐瞒=", "Secrets kept="),
    ("本章承诺变化：", "Chapter promised changes: "),
    ("证据锚：", "Evidence anchor: "),
    ("未指定角色的知识承诺：", "Unbound character knowledge commitments: "),
    ("无特殊已知事实", "no specific known facts"),
    ("当前 POV", "current POV"),
    ("当前/候选 POV", "current/candidate POV"),
    ("时间锚：", "Time anchor: "),
    ("间隔：", "Gap: "),
    ("本章跨度：", "Chapter span: "),
    ("倒计时状态：", "Countdown status: "),
    ("本章为回忆/倒叙：", "This chapter is flashback: "),
    ("初始化大纲上下文", "Initialization outline context"),
    ("上章事件：", "Previous chapter events: "),
    ("相关历史：", "Relevant history: "),
    ("活跃母题", "Active motifs"),
    ("长线母题参考", "Long-range motif reference"),
    ("待回收伏笔", "Foreshadowing due for payoff"),
    ("本章桥接禁用通道：", "Bridge forbidden channels this chapter: "),
    ("跨章高频通道：", "Cross-chapter high-frequency channels: "),
    ("记忆系统提示：", "Memory system hints: "),
    ("本章焦点：", "Chapter focus: "),
    ("必要要素：", "Required elements: "),
    ("本章聚焦扩展：", "Chapter focus extension: "),
    ("执行约束：", "Execution constraints: "),
    ("近期未命中：", "Recently missed: "),
    ("近期弱命中：", "Recently weak hits: "),
    ("建议优先关注：", "Suggested priority focus: "),
    ("预期张力=", "Expected tension="),
    ("本章章尾优先使用：", "Chapter ending hook priority: "),
    ("本章微兑现：", "In-chapter micro-payoffs: "),
    ("必须回应悬念：", "Must resolve suspense: "),
    ("章尾钩子方向：", "Chapter hook direction: "),
    ("节奏：", "Pace: "),
    ("高光模式：", "Highlight mode: "),
    ("本章已超过主高潮预计余波：", "This chapter exceeds the main climax aftermath budget: "),
    ("距离主高潮：", "Distance from main climax: "),
    ("余波预算：", "Aftermath budget: "),
    ("编辑准入风险", "Editorial gate risk"),
    ("余波/尾声：", "Aftermath/denouement: "),
    ("确认性场景上限", "Confirmation scene cap"),
    ("主题呈现：", "Theme presentation: "),
    ("象征物策略：", "Symbol strategy: "),
    ("场景阻力候选：", "Scene resistance candidates: "),
    ("角色声纹目标：", "Character voice targets: "),
    ("揭示阶梯：", "Revelation ladder: "),
    ("叙述要素编辑指令：", "Narrative element editorial directives: "),
    ("时间桥规则：", "Time bridge rules: "),
    ("近窗分布：", "Recent window distribution: "),
    ("已裁定事实摘要", "Adjudicated fact summaries"),
    ("结构化状态路径", "Structured state paths"),
    ("待定/延后事项", "Pending/deferred items"),
    ("本章叙事契约", "Chapter narrative contract"),
    ("实体/身份指代图", "Entity/Identity reference map"),
    ("身份/称谓链接", "Identity/title links"),
    ("道具/概念/组织关联", "Object/concept/organization associations"),
    ("已死亡", "deceased"),
    ("存活", "alive"),
    ("位置=", "location="),
    ("情绪=", "emotion="),
    ("未知", "unknown"),
    ("章未出场", "chapters absent"),
    ("暂无已追踪的角色状态", "No tracked character status available"),
    ("本章目标", "Chapter target"),
    ("字", "words"),
    ("硬约束", "Hard constraint"),
    ("必须控制在", "must stay within"),
    ("字之间，超出视为不合格", "words, exceeding is unacceptable"),
    ("建议", "suggested"),
    ("编辑完成后自检字数：", "After editing, self-check word count: "),
    ("若低于", "if below"),
    ("字则补足过程/动作/对话细节，若高于", "words, add process/action/dialogue detail; if above"),
    ("字则压缩重复解释与低信息密度段。", "words, compress repetitive explanation and low-density passages."),
    ("工作身份：", "Role: "),
    ("修复路径：", "Repair approach: "),
    ("审校路径：", "Audit approach: "),
    ("推导路径：", "Derivation approach: "),
    ("抽取路径：", "Extraction approach: "),
    ("字段级质量示例", "Field-level quality examples"),
    ("非输出格式", "not output format"),
    ("平弱=", "Weak="),
    ("高质量=", "High-quality="),
    ("可操作路径：", "Actionable path: "),
    ("✅ 负责：", "✅ Responsible for: "),
    ("❌ 不负责：", "❌ Not responsible for: "),
    ("专注本章内部质量：", "Focus on intra-chapter quality: "),
    ("专注跨章连贯性：", "Focus on cross-chapter continuity: "),
    ("专注章内因果链完整性", "Focus on intra-chapter causal chain integrity"),
    ("专注章节与大纲的对齐程度", "Focus on chapter-outline alignment"),
    ("不处理跨章连贯性问题", "Does not handle cross-chapter continuity"),
    ("不处理章内逻辑问题", "Does not handle intra-chapter logic"),
    ("不处理跨章连贯性或语法问题", "Does not handle cross-chapter continuity or grammar"),
    ("不处理语法或连贯性问题", "Does not handle grammar or continuity"),
    ("不处理语法/表达错误", "Does not handle grammar/expression errors"),
    ("不处理因果链细节验证", "Does not handle causal chain detail verification"),
    ("不处理桥接契约结构检查", "Does not handle bridge contract structure checks"),
    ("不处理大纲对齐", "Does not handle outline alignment"),
    ("检查提示词泄露和系统痕迹", "Check for prompt leakage and system artifacts"),
    ("检查章内自洽性", "Check intra-chapter self-consistency"),
    ("检查章内因果链完整性", "Check intra-chapter causal chain integrity"),
    ("检查 must_carry_forward 事项的落实", "Check must_carry_forward fulfillment"),
    ("检查章节桥接契约的履行情况", "Check bridge contract fulfillment"),
    ("检查事件间的逻辑关联", "Check logical connections between events"),
    ("验证角色决策的动机合理性", "Verify character decision motivation"),
    ("检查主线推进点的覆盖情况", "Check main plot progression coverage"),
    ("评估支线与主线的协调性", "Evaluate subplot-main plot coordination"),
    ("轮次：", "Round: "),
    ("策略：", "Strategy: "),
    ("本轮新方向：", "New direction this round: "),
    ("禁止重复：", "Avoid repeating: "),
    ("失败/停滞原因判断：", "Failure/stagnation diagnosis: "),
    ("本轮聚焦问题：", "Focus issues this round: "),
    ("上轮残留问题：", "Residual issues from last round: "),
    ("上轮模型尝试：", "Model attempts last round: "),
    ("上轮已应用修改：", "Applied patches last round: "),
    ("上轮被拒绝修改：", "Rejected patches last round: "),
    ("操作步骤：", "Steps: "),
    ("是否只处理了本轮目标问题，未扩大到无关段落？", "Did you only address this round's target issues without expanding to unrelated passages?"),
    ("是否保留了章节计划、bridge/contract、主线推进点、既有事实和字数边界？", "Did you preserve the chapter plan, bridge/contract, main plot progressions, established facts, and word count bounds?"),
    ("是否没有新增计划外 POV、禁出角色、关键道具、重大事件、后续章节答案或解释性报告？", "Did you avoid introducing unplanned POVs, forbidden characters, key props, major events, future chapter answers, or explanatory reports?"),
    ("若某个问题无法在不破坏上述约束的前提下安全修复", "If an issue cannot be safely fixed without violating the above constraints"),
    ("请优先保持相关事实不变并完成其他安全修复", "prioritize keeping related facts intact and complete other safe fixes"),
    ("不要在正文中插入", "do not insert"),
    ("注释、修复说明或任何非正文标记", "comments, repair notes, or any non-prose markers"),
    ("后续复检会继续暴露残留问题。", "subsequent rechecks will continue to expose residual issues."),
    ("请以此作为", "Please use this as"),
    ("的共同依据；维度特需信息只能补充，不得覆盖锚点事实。", "'s common basis; dimension-specific info may only supplement, not override anchor facts."),
    ("本次分片", "this shard"),
    ("— 规划时必须遵守", " — must be followed during planning"),
    ("— 所有章节桥接必须遵守", " — must be followed for all chapter bridges"),
    ("（★ 硬约束", "(★ Hard constraint"),
    ("世界规则：", "World rules: "),
    ("基调约束：", "Tone constraint: "),
    ("时代语境/礼制约束", "Era context/etiquette constraints"),
    ("社会等级：", "Social hierarchy: "),
    ("称谓规则：", "Address rules: "),
    ("自称规则：", "Self-reference rules: "),
    ("礼制/行为边界：", "Etiquette/behavior boundaries: "),
    ("制度术语：", "Institutional terms: "),
    ("时代器物：", "Era material culture: "),
    ("时代错位禁用：", "Anachronism blacklist: "),
    ("对白语体：", "Dialogue register: "),
    ("核心主题：", "Core themes: "),
    ("角色弧光：", "Character arcs: "),
    ("结局走向", "Ending direction"),
    ("关键转折：", "Key turning points: "),
    ("连贯性协议", "Continuity protocol"),
    ("初始化硬规则", "Initialization hard rules"),
    ("场景切换：", "Scene transitions: "),
    ("桥接落地：", "Bridge landing: "),
    ("时间合法性：", "Time legitimacy: "),
    ("POV可见性：", "POV visibility: "),
    ("禁复用规则：", "Repetition ban: "),
    ("信息密度预算", "Information density budget"),
    ("单章重大揭示不超过", "Max key revelations per chapter: "),
    ("条，超出部分必须改为伏笔或误导线索。", "; excess must become foreshadowing or misleading clues."),
    ("悬念留存：", "Suspense retention: "),
    ("条未决线索进入下一章", "unresolved threads carried to next chapter"),
    ("若为 0 则不强制", "(0 = not enforced)"),
    ("写作时注意铺垫方向", "note foreshadowing direction during writing"),
    ("按项目时代背景自然选择时间单位", "choose time units naturally per project era"),
    ("限知视角仅描写可观察事实。", "Limited POV only describes observable facts."),
    ("禁用元素不得近义复现。", "Forbidden elements must not reappear via synonyms."),
    ("开场地点变化时，前", "When opening location changes, the first"),
    ("句必须出现位移动作链。", "sentences must include a movement action chain."),
    ("开场前", "Within the first"),
    ("字须回应", "words must respond to"),
    ("节奏模式：", "Pace mode: "),
    ("环境描写占比：", "Environment description ratio: "),
    ("情绪风格：", "Emotional style: "),
    ("信息密度：", "Information density: "),
    ("项目级禁用短语：", "Project-level banned phrases: "),
    ("避免原样或近似复用", "avoid verbatim or near-verbatim reuse"),
    ("对话占比遵守风格规范：", "Dialogue ratio per style spec: "),
    ("本章重点叙事要素必须在正文中明确体现：", "The following chapter-focus narrative elements must be clearly embodied in the prose:"),
    ("这些要素名称与提示仅供幕后设计", "These element names and hints are for behind-the-scenes design only"),
    ("不得在正文中以标题、标签、注释或加粗说明直接出现。", "and must not appear verbatim as headings, labels, annotations, or bolded explanations in the prose."),
    ("禁止直接写出", "Do not write out"),
    ("等策划词", "or similar planning terms"),
    ("必须转译成自然的动作、对白、冲突和感官细节。", "translate into natural action, dialogue, conflict, and sensory detail."),
    ("本章落地要求：", "Chapter execution requirements:"),
    ("规划备注：", "Planning note: "),
    ("这些要素名称只用于 scene 设计", "These element names are for scene design only"),
    ("不得在 summary、required_outcome 或正文里原样复述", "do not repeat verbatim in summary, required_outcome, or prose"),
    ("等标签。", "or similar labels."),
    ("全局兜底，不要求本章全部覆盖", "Global fallback, full coverage not required this chapter"),
    ("可弱体现或仅做伏笔铺垫", "may be weakly present or used as foreshadowing"),
    ("全局候选，本章不强制展开", "Global candidates, not required this chapter"),
    ("本章未指定重点扩展要素", "No focus extension elements specified this chapter"),
    ("扩展要素仅作为全局候选池", "extension elements serve as global candidate pool only"),
    ("不要求在本章全部覆盖。", "full coverage not required this chapter."),
    ("执行落地：", "Execution landing: "),
    ("若本章存在重点扩展要素", "If this chapter has focus extension elements"),
    ("则每个要素至少绑定 1 个 scene_intents", "each element must bind to at least 1 scene_intent"),
    ("并在", "and in"),
    ("中写出具体动作、冲突或后果", "write specific actions, conflicts, or consequences"),
    ("不得只写抽象标签。", "do not write only abstract labels."),
    ("优先级", "priority"),
    ("（优先级", "(priority "),
    ("规划时须纳入场景设计", "must be incorporated into scene design during planning"),
    ("每章均须体现", "required every chapter"),
    ("检查模板职责边界定义", "Check template responsibility boundary definitions"),
    ("此文件从", "This file migrated from"),
    ("迁移而来，保持向后兼容", "maintaining backward compatibility"),
    ("角色职责边界定义", "Role responsibility boundary definitions"),
    ("定义各类检查模板的职责边界", "Defines responsibility boundaries for check templates"),
    ("包括章节内检查、连贯性评估、因果验证、对齐检查的职责范围矩阵。", "including intra-chapter checks, continuity evaluation, causal validation, and alignment check scope matrix."),
    ("返回章节内检查职责描述", "Returns intra-chapter check responsibility description"),
    ("返回跨章连贯性检查职责描述", "Returns cross-chapter continuity check responsibility description"),
    ("返回因果链验证职责描述", "Returns causal chain validation responsibility description"),
    ("返回大纲对齐检查职责描述", "Returns outline alignment check responsibility description"),
    ("根据模板名称返回职责范围矩阵", "Returns responsibility scope matrix based on template name"),
    ("语法、表达、事实错误", "grammar, expression, factual errors"),
    ("时间、地点、人物状态、情绪承接", "time, location, character state, emotional carryover"),
    ("事件触发、决策动机、悬念衔接", "event triggers, decision motivations, suspense衔接"),
    ("通用写作质量标准宏", "Common writing quality standard macros"),
    ("包括系统痕迹禁止、代词一致性、感官多样性、对话格式、说明腔禁止、意象复用禁止等约束。", "including system artifact ban, pronoun consistency, sensory diversity, dialogue format, anti-exposition, imagery repetition ban."),
    ("这些宏被写作模板和检查模板共享，确保质量标准统一。", "These macros are shared by writing and checking templates to ensure unified quality standards."),
    ("禁止系统标记和规划术语混入正文", "Ban system markers and planning terms from prose"),
    ("强制角色代词一致性", "Enforce character pronoun consistency"),
    ("角色自称语境意识", "Character self-reference context awareness"),
    ("感官多样性要求", "Sensory diversity requirements"),
    ("对话密度控制", "Dialogue density control"),
    ("中文引号对话格式规范", "Chinese quotation dialogue format rules"),
    ("章尾元叙事禁止", "Chapter-ending meta-narrative ban"),
    ("创造性具体化与反机械句式", "Creative specificity and anti-mechanical phrasing"),
    ("网文节奏约束", "Web novel pacing rules"),
    ("意象复用禁止", "Imagery repetition ban"),
    ("模板化短语黑名单", "Template phrase blacklist"),
    ("段落唯一性约束", "Paragraph uniqueness constraint"),
    ("情感工艺", "Emotional craft"),
    ("通用质量标准片段", "Common quality standard fragments"),
    ("禁用系统标记和规划术语", "Ban system markers and planning terms"),
    ("时间表达策略与传统时辰刻度约束", "Time expression strategy and traditional time unit constraints"),
    ("代词一致性", "Pronoun consistency"),
    ("自称语境意识", "Self-reference context awareness"),
    ("基于项目世界观和人物身份信息，由LLM根据场景自行判断自称", "Based on project worldview and character identity, LLM determines self-reference per scene"),
    ("角色自称需符合其身份、场景、对话对象，具体用词由上下文决定，而非固定不变。", "Character self-reference must match their identity, scene, and interlocutor; specific wording is context-dependent, not fixed."),
    ("同一角色在不同场景中应自然切换自称。", "The same character should naturally switch self-reference across different scenes."),
    ("判断依据", "Judgment basis"),
    ("角色身份与地位", "Character identity and status"),
    ("参考角色档案中的身份、职业、社会层级", "Reference character profile identity, profession, social tier"),
    ("场景正式程度", "Scene formality"),
    ("正式场合 vs 私下/日常/独处", "formal vs private/daily/solitary"),
    ("对话对象关系", "Interlocutor relationship"),
    ("上级/平级/下级，亲疏远近", "superior/peer/subordinate, close/distant"),
    ("世界观设定", "Worldview setting"),
    ("参考项目世界观中的社会结构、礼仪规范、价值观念", "Reference project worldview social structure, etiquette norms, values"),
    ("核心原则", "Core principle"),
    ("自称随场景变化", "Self-reference varies by scene"),
    ("LLM应根据当前场景的权力关系、社交距离、正式程度", "LLM should determine based on current scene power dynamics, social distance, formality"),
    ("结合角色身份与世界观设定，自然选择合适自称", "combined with character identity and worldview, naturally choose appropriate self-reference"),
    ("避免全篇统一使用同一自称。", "avoid using the same self-reference throughout."),
    ("当前项目世界观参考", "Current project worldview reference"),
    ("当前角色身份参考", "Current character identity reference"),
    ("性别=女，代词必须使用", "gender=female, pronouns must use"),
    ("性别=男，代词必须使用", "gender=male, pronouns must use"),
    ("严禁使用", "must not use"),
    ("代词混用是严重错误，必须避免！", "Pronoun mixing is a serious error and must be avoided!"),
    ("感官只服务冲突、动作、转场和情绪判断；不要为覆盖率硬补。", "Senses only serve conflict, action, transitions, and emotional judgment; do not force-fill for coverage."),
    ("每场从", "Each scene selects 1-2 effective anchors from"),
    ("选 1-2 个有效锚点，同段主导感官不超过 2 种。", "; no more than 2 dominant senses per paragraph."),
    ("若视觉过密，优先换成声音、触感、气味、温度、对白停顿、动作选择或场面调度。", "If visual density is too high, prioritize switching to sound, touch, smell, temperature, dialogue pauses, action choices, or blocking."),
    ("当前弱项：", "Current weak senses: "),
    ("只在关键场景补 1 处有效描写。", "add 1 effective description only in key scenes."),
    ("对话内容建议占全文字数", "Dialogue content suggested at"),
    ("高张力场景可适当提高上限。", "% of total word count; high-tension scenes may raise the upper bound."),
    ("检查对话占比：若对话内容（含引号内的直接引语）低于全文", "Check dialogue ratio: if dialogue (including direct quotes) is below"),
    ("需增加有效对话场景。", "% of total, add effective dialogue scenes."),
    ("检查对话质量：确保至少有 2-3 段对话真正推动信息、关系或决策变化。", "Check dialogue quality: ensure at least 2-3 dialogue passages genuinely advance information, relationships, or decisions."),
    ("避免连续 3 段以上", "Avoid 3+ consecutive"),
    ("问答式", "Q&A-style"),
    ("对话，应穿插动作、停顿、眼神交流、环境反应等。", "dialogue; intersperse with action, pauses, eye contact, environmental reactions, etc."),
    ("直接引语用中文双引号，嵌套引用用中文单引号。", "Direct quotes use double quotation marks; nested quotes use single quotation marks."),
    ("对话标签、动作、停顿、环境反应交替使用；高张力对峙可短暂连续纯对话。", "Alternate dialogue tags, actions, pauses, and environmental reactions; high-tension confrontations may use brief runs of pure dialogue."),
    ("不要连续复用同一种", "Do not repeatedly use the same"),
    ("等标签。", "etc. tags."),
    ("禁止在", "Prohibit in"),
    ("中出现任何系统/提示词痕迹，例如", "any system/prompt artifacts such as"),
    ("等元叙事文本。", "etc. meta-narrative text."),
    ("特别强调", "Special emphasis"),
    ("严禁在正文中使用任何规划层标记，包括但不限于", "Strictly prohibit planning-layer markers in prose, including but not limited to"),
    ("这些都是规划层概念，不能出现在小说正文中。", "These are planning-layer concepts and must not appear in novel prose."),
    ("禁止使用说明腔开头，例如", "Prohibit exposition-style openings such as"),
    ("不输出任何规划标签，不要把 scene/contract 原样写进正文。", "Do not output planning labels; do not write scene/contract verbatim into prose."),
    ("开篇必须让读者自然感到", "The opening must let readers naturally feel"),
    ("谁在这、发生了什么、为什么接着上一章", "who is here, what happened, why this follows the previous chapter"),
    ("但不能用说明句替代叙事。", "but must not replace narrative with explanatory sentences."),
    ("是幕后设计意图。正文必须让读者通过角色的动作选择、对白潜台词、感官发现和环境阻力来自行发现这些意图，禁止叙述者直接告知结论。", "are behind-the-scenes design intents. The prose must let readers discover these through character action choices, dialogue subtext, sensory discoveries, and environmental resistance; the narrator must not directly state conclusions."),
    ("叙述者告知结果", "narrator tells the result"),
    ("读者从行动推断发现", "reader infers discovery from action"),
    ("时只允许感官暗示和角色微反应，禁止编号式总结或完整解读。", "only sensory hints and character micro-reactions are allowed; no numbered summaries or full interpretations."),
    ("禁止用", "Prohibit using"),
    ("等元语言替代叙事。", "etc. meta-language as narrative substitute."),
    ("悬念用动作、异象、对白留白或新阻力呈现；不要作者点评", "Present suspense through action, anomalies, dialogue pauses, or new resistance; no author commentary"),
    ("最后 3 段避免", "Avoid in the last 3 paragraphs"),
    ("等元叙事总结。", "etc. meta-narrative summaries."),
    ("具体化落到角色选择、动作后果、对白潜台词、环境阻力或场面调度。", "Specificity lands on character choices, action consequences, dialogue subtext, environmental resistance, or blocking."),
    ("不使用", "Do not use"),
    ("这类定义式否定转折来自证描写品质", "this type of definitional negative转折 to self-prove quality"),
    ("除非角色正在辩驳、事实纠偏、时间纠偏或形成关键悬置。", "unless the character is debating, correcting facts, correcting time, or forming key suspense."),
    ("此规则禁止的是叙述者为描写质量做自我注解", "This rule prohibits narrators from self-annotating quality"),
    ("不禁止角色在剧情中做出真实区分、事实纠正或推动情节的否定转折。", "does not prohibit characters from making real distinctions, factual corrections, or plot-driving negative turns."),
    ("抽象判断句只在辩驳、事实纠偏、时间纠偏或关键悬置中保留。", "Abstract judgment sentences are only retained in debate, factual correction, time correction, or key suspense."),
    ("必达事件或旧意象需要保留时，只保留叙事功能，换触发点、动作链或观察角度。", "When required events or old imagery must be retained, keep only the narrative function; change the trigger, action chain, or observation angle."),
    ("同构句式反复承担同一功能时，只留真正改变读者认知的一处", "When isomorphic sentences repeatedly serve the same function, keep only the one that genuinely changes reader understanding"),
    ("其余改成反应、误判、成本、留白或外部变化。", "change the rest to reactions, misjudgments, costs, pauses, or external changes."),
    ("前 200-300 字内必须出现动作、对话、冲突或异常事件中的至少一种，不要先报时再铺景。", "Within the first 200-300 words, at least one of action, dialogue, conflict, or anomaly must appear; do not report time before setting the scene."),
    ("环境/心理铺陈合计尽量控制在全文约 20%-25%；连续两段铺景后，下一段必须推进事件。", "Environment/psychology should total ~20-25% of the text; after two consecutive setting paragraphs, the next must advance the event."),
    ("每个场景都要带来可观察推进：线索增加、决策变化、关系位移或阻力升级。", "Every scene must bring observable progression: clue accumulation, decision changes, relationship shifts, or resistance escalation."),
    ("以下意象/比喻已在前面章节中使用过", "The following imagery/metaphors have been used in previous chapters"),
    ("本章全文禁止使用任何近似表达", "this chapter must not use any similar expressions"),
    ("禁止范围包括所有语义等价、近义替换、换喻表达的写法。", "The ban covers all semantically equivalent, synonym-substituted, or metonymic expressions."),
    ("自检规则：若某比喻/意象在本书已出现", "Self-check: if a metaphor/imagery has appeared"),
    ("次，即使未列入上述清单，也须主动换用全新表达。", "or more times in this book, even if not listed above, proactively use a completely new expression."),
    ("静态陈词滥调黑名单已由 PROFILE_STYLE 动态管理，此处不再重复以节省 prompt tokens", "Static cliché blacklist is dynamically managed by PROFILE_STYLE; not repeated here to save prompt tokens"),
    ("禁止在情绪转折处重复使用以下模板化短语超过 2 次：", "Prohibit repeating the following template phrases more than 2 times at emotional turning points:"),
    ("禁止连续两段或间隔一段后使用相同/近似的核心句子", "Prohibit using identical or similar core sentences in consecutive paragraphs or with one paragraph gap"),
    ("自检：若某句在已生成内容中出现", "Self-check: if a sentence appears"),
    ("必须删除重复项。", "times in generated content, delete the duplicate."),
    ("反差出情感", "Contrast creates emotion"),
    ("高强度情绪场景中，用一个不协调的日常细节、温柔动作或冷静观察来放大情感冲击，而非堆叠同强度的描写。", "In high-intensity emotional scenes, use an incongruous daily detail, gentle action, or calm observation to amplify emotional impact, rather than stacking same-intensity descriptions."),
    ("轻松场景中可埋一个不和谐音符来制造不安。", "In light scenes, plant a dissonant note to create unease."),
    ("留白即表达", "Silence is expression"),
    ("角色最痛苦或最震撼的时刻，允许用沉默、动作中断、话题转移或环境白描来替代直接描写。", "At a character's most painful or shocking moment, allow silence, action interruption, topic shift, or environmental sketch to replace direct description."),
    ("不是所有情绪都需要被命名——读者从角色的行为选择中自行推断的情感，比被告知的更有力。", "Not all emotions need to be named—emotions readers infer from character behavior choices are more powerful than those told to them."),
    ("情绪不叠加同构", "Emotions don't stack isomorphically"),
    ("同一场景中同一情绪只用一种表达通道展开", "In the same scene, the same emotion uses only one expression channel"),
    ("不重复使用同一通道。", "do not repeat the same channel."),
    ("（动作/对白/身体/环境/沉默）", "(action/dialogue/body/environment/silence)"),
    ("当前 POV 角色", "Current POV character"),
    ("采用", "uses"),
    ("视角。", "POV."),
    ("该角色不可能知道以下类别的信息，正文中绝不能出现这些知识的直接或间接表达：", "This character cannot know the following categories of information; their direct or indirect expression must never appear in the prose:"),
    ("该角色的感知限制：", "This character's sensory limits:"),
    ("违反此约束将导致角色获取全知信息，破坏限知视角的真实感。", "Violating this constraint gives the character omniscient information, breaking limited POV realism."),
    ("若需要表达该角色不知情的状态，可通过困惑、误判、猜测等方式间接呈现。", "To express the character's ignorance, indirectly present it through confusion, misjudgment, or guessing."),
    ("是角色知识唯一事实源；", "is the sole fact source for character knowledge; "),
    ("章节硬事实、世界规则和作者契约不自动等于角色已知。", "chapter hard facts, world rules, and author contracts do not automatically equal character knowledge."),
    ("POV 内心、判断、对白和行动只能基于该角色已知/怀疑/误信/隐瞒的信息，以及本场实时可观察的新证据。", "POV inner thoughts, judgments, dialogue, and actions can only be based on what the character knows/suspects/misbelieves/hides, plus real-time observable new evidence in the scene."),
    ("若本章需要新增知识，必须通过本章场景中的对话、观察、发现、误导或隐瞒动作落地，并服务场景目标。", "If new knowledge is needed this chapter, it must land through dialogue, observation, discovery, misleading, or concealment actions in this chapter's scenes, serving scene goals."),
    ("编辑时不得改坏", "do not corrupt during editing"),
    ("不要把作者硬事实、世界规则或契约目标写成角色天然知道。", "do not write author hard facts, world rules, or contract goals as things the character naturally knows."),
    ("不得新增未由本章对白、观察、发现、误导或隐瞒动作支撑的认知变化。", "Do not add cognitive changes not supported by this chapter's dialogue, observation, discovery, misleading, or concealment actions."),
    ("必须写出新行动、新冲突或新信息，不得重复圆满确认。", "must write new action, new conflict, or new information; do not repeat confirmation rounds."),
    ("删减重复确认，保留新行动、新冲突或新信息。", "cut repetitive confirmations, keep new action, new conflict, or new information."),
    ("余波/尾声：补过渡时不得额外添加纯确认段。", "Aftermath/denouement: do not add extra pure-confirmation paragraphs when filling transitions."),
    ("精修时不得新增纯确认段。", "do not add pure-confirmation paragraphs during polish."),
    ("高情绪场景身体信号预算：每场最多", "High-emotion scene body signal budget: max"),
    ("个。", "per scene."),
    ("起草动作", "drafting action"),
    ("修订动作", "revision action"),
    ("编织动作", "weaving action"),
    ("精修动作", "polish action"),
    ("对白声纹", "Dialogue voice"),
    ("声纹修订目标", "Voice revision target"),
    ("声纹参考", "Voice reference"),
    ("解释倾向", "explanation bias"),
    ("禁用", "banned"),
    ("情绪句法", "emotion syntax"),
    ("标志动作/句法：", "Signature moves/syntax: "),
    ("声纹样例（只作节奏参考，禁止原句复用）：", "Voice samples (rhythm reference only, verbatim reuse prohibited): "),
    ("禁用口吻：", "Banned tones: "),
    ("象征物策略（按解释预算执行，不额外补含义说明）：", "Symbol strategy (follow explanation budget, no extra meaning explanation): "),
    ("最多明说", "max explicit mentions"),
    ("次；", "times; "),
    ("场景阻力必须落到空间、流程、人群、距离、遮挡、物件或时间窗口：", "Scene resistance must land on space, process, crowd, distance, obstruction, objects, or time window: "),
    ("确认型台词禁/限复用：", "Confirmation-type dialogue ban/limit reuse: "),
    ("你是一位谨慎的小说修复编辑，擅长在保留已验证文本的前提下完成最小必要修复。", "You are a careful novel repair editor, skilled at making minimal necessary fixes while preserving verified text."),
    ("先定位必须修的证据点，再确认允许改动范围，最后用最小文本变化恢复连贯、因果或表达质量。", "First locate evidence points that must be fixed, then confirm the allowed change scope, finally use minimal text changes to restore coherence, causality, or expression quality."),
    ("整体重写", "full rewrite"),
    ("只改冲突句/缺口段，并保留已验证的人物、事件和语气", "only change conflict sentences/gap paragraphs, preserving verified characters, events, and tone"),
    ("修复必须服务于原问题和下游验证，不扩写新剧情，不改变未被授权的章节事实。", "Repairs must serve the original issue and downstream verification; do not expand new plot or change unauthorized chapter facts."),
    ("你是一位严谨的小说质量审校员，擅长用短证据、明确边界和下游可执行建议定位问题。", "You are a rigorous novel quality auditor, skilled at locating issues with short evidence, clear boundaries, and actionable downstream suggestions."),
    ("先确认输入证据，再判断问题类型、影响范围和修复边界，最后给下游可执行的定位信息。", "First confirm input evidence, then judge issue type, impact scope, and repair boundary, finally provide actionable location info for downstream."),
    ("这里不连贯", "incoherent here"),
    ("指出哪两处证据冲突、风险等级、可验证问题", "identify which two evidence points conflict, risk level, verifiable issue"),
    ("每条判断都要能支持复核或修复，低置信度内容降级为待验证问题。", "Every judgment must support recheck or repair; low-confidence content is downgraded to pending-verification issues."),
    ("你是一位项目特异性写作顾问，擅长从梗概、角色、世界规则和已选叙事要素中推导可执行的风格/结构契约。", "You are a project-specific writing consultant, skilled at deriving executable style/structure contracts from synopsis, characters, world rules, and selected narrative elements."),
    ("先识别本项目的核心卖点、冲突机制和表达风险，再把结论映射到字段级参数或编辑契约。", "First identify this project's core selling points, conflict mechanisms, and expression risks, then map conclusions to field-level parameters or editorial contracts."),
    ("风格冷峻", "style is cold"),
    ("说明冷峻来自何种场景压力、证据细节、对白比例或信息密度", "explain what scene pressure, evidence detail, dialogue ratio, or information density makes it cold"),
    ("每条规则都要能被正文生成、编辑检查或后续审计复用，避免泛化成所有项目都适用的空话。", "Every rule must be reusable by prose generation, edit checks, or subsequent audits; avoid generic platitudes applicable to all projects."),
    ("你是一位证据优先的叙事事实抽取员，擅长从正文和上游锚点中提取可追溯、可合并的状态信息。", "You are an evidence-first narrative fact extractor, skilled at extracting traceable, mergeable state information from prose and upstream anchors."),
    ("先找正文中的明确事实，再对照共享锚点与已知状态，最后只保留能被后续合并器消费的信息。", "First find explicit facts in prose, then cross-reference shared anchors and known state, finally keep only information consumable by downstream mergers."),
    ("同一事实已有上游分片确认时保持一致；证据不足时用保守字段值表达未知或待确认。", "Keep consistent when the same fact is confirmed by upstream shards; use conservative field values for unknown or pending-confirmation when evidence is insufficient."),
    ("保留可追溯证据链，用保守字段值标记不确定信息", "preserve traceable evidence chains, mark uncertain info with conservative field values"),
    ("每条信息都服务于 canon、memory、state 或审计链路，避免把语气、比喻、猜测当作事实。", "Every piece of info serves canon, memory, state, or audit chains; avoid treating tone, metaphor, or speculation as fact."),
    ("是否保持修复范围最小，且修复后文本仍能通过原问题复核。", "Is the repair scope minimal, and can the repaired text still pass the original issue recheck?"),
    ("是否给出短证据、风险等级、定位信息和下游可验证的问题。", "Are short evidence, risk level, location info, and downstream-verifiable issues provided?"),
    ("是否把项目特异性依据映射到具体字段/规则，而不是复用通用写作口诀。", "Is project-specific evidence mapped to concrete fields/rules, not generic writing mantras?"),
    ("是否保留后续合并/检索需要的事实边界，且没有把推测写成既定事实。", "Are fact boundaries needed for downstream merge/retrieval preserved, without writing speculation as established fact?"),
    ("P0/P1/P2 优先级是否被保持，且没有让弱参考覆盖硬约束。", "Are P0/P1/P2 priorities maintained, without weak references overriding hard constraints?"),
    ("是否能把关键判断回指到输入证据、上游契约或已批准计划。", "Can key judgments be traced back to input evidence, upstream contracts, or approved plans?"),
    ("是否避免新增未授权的人物、地点、世界规则、未来 payoff 或格式协议。", "Are unauthorized characters, locations, world rules, future payoffs, or format protocols avoided?"),
    ("是否把抽象目标转化为可观察的行动、冲突、状态变化或章节承接点。", "Are abstract goals translated into observable actions, conflicts, state changes, or chapter handoff points?"),
    ("你是一位契约感很强的小说执行编辑，擅长把输入约束转化为有动作、有选择、有后果的叙事内容。", "You are a contract-aware novel execution editor, skilled at translating input constraints into narrative content with actions, choices, and consequences."),
    ("创意推断路径：先找情感引擎与冲突压力，再落到动作、对白、场面调度和后果。", "Creative inference path: first find the emotional engine and conflict pressure, then land on actions, dialogue, blocking, and consequences."),
    ("角色在具体选择前暴露代价、误判或情绪转折", "character reveals cost, misjudgment, or emotional turning before a concrete choice"),
    ("角色很紧张", "character is nervous"),
    ("每个新增内容都服务于已给人物动机、场景阻力、悬念推进或情绪落点。", "Every addition serves given character motivations, scene resistance, suspense progression, or emotional landing points."),
    ("（fast=快速推进/moderate=平衡/slow=细腻铺陈）", "(fast=rapid/moderate=balanced/slow=detailed)"),
    ("（direct=直给/balanced=平衡/subtle=含蓄）", "(direct=direct/balanced=balanced/subtle=subtle)"),
    ("（规划参考，非已发生历史）：", "(planning reference, not established history):"),
    ("（仅供连续性识别，不要求主动使用）：", "(for continuity identification only, not required to actively use):"),
    ("（软约束；只在本章契约自然需要时轻触，不得为呼应而新增意象、符号或主题解释）：", "(soft constraint; only lightly touch when this chapter's contract naturally requires it):"),
    ("（只在本章契约允许时安排回收或强化，不得强行提前解释）：", "(only arrange payoff when this chapter's contract allows; do not force early explanation):"),
    ("这些条目只用于减少修辞通道重复；计划时优先保留人物、地点、关键道具和剧情锚点，只替换表达方式。", "These entries are only for reducing rhetorical channel repetition; prioritize keeping characters, locations, key props, and plot anchors, only changing expression."),
    ("以下条目记录近期高频表达机制；本章应改换情绪承载方式，避免同义词替换。", "The following entries record recent high-frequency expression mechanisms; this chapter should change emotional carriers, avoiding synonym substitution."),
    ("替代方向：", "Alternative directions: "),
    ("保留边界：", "Retention boundary: "),
    ("近例：", "Recent example: "),
    ("章", "chapter"),
    ("以下弧光存在停滞风险，只需轻触，不要强插整段副线。", "The following arcs risk stagnation; only lightly touch them, do not force-insert entire subplot segments."),
    ("上次推进第", "Last progressed in chapter"),
    ("章；建议", "; suggestion: "),
    ("本章曾是旧终章但已被延长：", "This chapter was formerly the final chapter but has been extended: "),
    ("按过渡/再开启章规划，不暴露为最终章。", "plan as transition/re-opening chapter, do not expose as final chapter."),
    ("本章不是全书终章：", "This chapter is not the book's final chapter: "),
    ("closing_contract 必须留下后续承接余地，不得写成全书结局或最终清算。", "closing_contract must leave room for continuation; do not write as book ending or final reckoning."),
    ("本章不是全书终章：章末只能留下可承接的阶段性钩子，不得写成全书结局、终局清算或最终命运定论。", "This chapter is not the book's final chapter: chapter ending may only leave stage hooks; do not write as book ending, final reckoning, or ultimate fate conclusion."),
    ("本章是当前 outline 的全书终章，可以执行全书级收束。", "This chapter is the current outline's book final chapter; book-level closure may be executed."),
    ("本章是当前 outline 的全书终章，可以完成全书级收束，但仍不得突破 source/contract 边界。", "This chapter is the current outline's book final chapter; book-level closure may be completed, but source/contract boundaries must not be breached."),
    ("本章曾是旧终章但已被延长：正文应转为过渡/再开启章，不要按最终章处理。", "This chapter was formerly the final chapter but has been extended: prose should transition to a re-opening chapter, do not treat as final chapter."),
    ("为第", "Generate executable"),
    ("章生成可执行", "for chapter"),
    ("本阶段的唯一核心产物是 scene-based 计划：把桥接、必达事件、禁止变化和出口目标全部落入已有字段。", "The sole core deliverable of this stage is a scene-based plan: map bridge, required events, forbidden changes, and exit targets into existing fields."),
    ("章节位置：", "Chapter position: "),
    ("章；", "/"),
    ("章末只能留下可承接的阶段性钩子", "chapter ending may only leave stage hooks"),
    ("写第", "Write chapter"),
    ("章《", "chapter"),
    ("》正文。", "prose."),
    ("（★ 硬约束：必须控制在", "(★ Hard constraint: must stay within"),
    ("字之间，超出视为不合格）", "words, exceeding is unacceptable)"),
    (" BridgeArtifact 已在 Planning 阶段吸收到 PlanArtifact.opening_bridge；DRAFT 不再读取独立 BridgeCard。", "BridgeArtifact has been absorbed into PlanArtifact.opening_bridge during Planning; DRAFT no longer reads independent BridgeCard."),
    (" DRAFT 只消费 PlanArtifact 的 scene_intents / opening_bridge、单章契约投影、局部世界规则、局部风格/声纹投影。", "DRAFT only consumes PlanArtifact's scene_intents/opening_bridge, single-chapter contract projection, local world rules, local style/voice projection."),
    (" 六要素文学合同已在 Planning 阶段转译进 scene 字段；DRAFT 只执行这些字段，不重新规划人物弧、主题、伏笔或场景功能。", "Six-element literary contract has been translated into scene fields during Planning; DRAFT only executes these fields, does not re-plan character arcs, themes, foreshadowing, or scene functions."),
    (" DRAFT 不消费 cross-scene intent，不读取人物大包，不读取全书级创作规划；跨场节奏与呼应留给 WAVE。", "DRAFT does not consume cross-scene intent, does not read character大包, does not read book-level creative planning; cross-scene rhythm is left to WAVE."),
    ("权威边界", "Authority boundary"),
    ("实体边界", "Entity boundary"),
    ("局部写作投影", "Local writing projection"),
    ("世界硬规则", "World hard rules"),
    ("风格投影", "Style projection"),
    ("角色声纹投影", "Character voice projection"),
    ("ticket/window 修复边界", "Ticket/window repair boundary"),
    ("polish 边界", "Polish boundary"),
    ("extraction 边界", "Extraction boundary"),
    ("缺少", "Missing"),
    ("本步骤没有初始化权威投影，应由上游 gate 阻断", "this step has no initialization authority projection and should be blocked by upstream gate"),
    ("不要凭空补全", "do not fabricate"),
    ("或", "or"),
    ("。", "."),
    ("：", ": "),
    ("；", "; "),
    ("、", ", "),
    ("（", "("),
    ("）", ")"),
    ("【", "["),
    ("】", "]"),
    ("「", "\""),
    ("」", "\""),
    ("『", "'"),
    ("』", "'"),
    ("——", "—"),
    ("……", "..."),
]

def translate_content(content):
    result = content
    for zh, en in TRANSLATIONS:
        result = result.replace(zh, en)
    return result

def main():
    translated = 0
    skipped = 0
    errors = 0
    for root, _dirs, files in os.walk(ZH):
        for f in files:
            if not f.endswith('.j2'):
                continue
            zh_path = os.path.join(root, f)
            rel = os.path.relpath(zh_path, ZH)
            en_path = os.path.join(EN, rel)
            if os.path.exists(en_path):
                skipped += 1
                continue
            try:
                with open(zh_path, 'r', encoding='utf-8') as fh:
                    content = fh.read()
                translated_content = translate_content(content)
                os.makedirs(os.path.dirname(en_path), exist_ok=True)
                with open(en_path, 'w', encoding='utf-8') as fh:
                    fh.write(translated_content)
                translated += 1
                print(f"  OK {rel}")
            except Exception as e:
                errors += 1
                print(f"  ERR {rel}: {e}")
    print(f"\nDone: {translated} translated, {skipped} skipped, {errors} errors")

if __name__ == "__main__":
    main()
