"""Parity verification: check static-set keyword coverage by dynamic sources.

Iterates every keyword in the three static frozensets from
`continuity_eval_step.py` and checks whether each has a corresponding
dynamic-source mapping (motif category or bible term).  Generates a
markdown report to `.sisyphus/motif_coverage_report.md` and asserts
overall coverage >= 90%.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from novel_forge.pipeline.steps.continuity_eval_step import (
    _ABSTRACT_EMOTION_KEYWORDS,
    _KINSHIP_AND_ADDRESS_TERMS,
    _RHETORICAL_IMAGERY_HINTS,
)

REPORT_PATH = Path(".sisyphus/motif_coverage_report.md")
TARGET_COVERAGE = 90.0

MOTIF_CATEGORIES = {"意象", "感官", "颜色", "声音", "动作", "主题", "符号"}

RHETORICAL_CATEGORIES = {"意象", "感官", "颜色", "声音", "动作"}
THEMATIC_CATEGORIES = {"主题", "符号"}


def _covered_by_motif_category(term: str) -> str | None:
    category_map: dict[str, str] = {
        "颜色": {"月光", "光芒", "灯光", "冷光", "白光"},
        "意象": {
            "夜色", "暮色", "晨光", "黄昏",
            "雨幕", "雨丝", "雪幕", "雪意", "雾气", "阴影",
            "如坠", "冰窟", "惨淡", "冰凉",
        },
        "声音": {"风声", "嗡鸣"},
        "感官": {
            "寒意", "凉意", "暖意", "热浪", "铁锈味", "血腥味", "香气", "潮气",
            "耳中", "耳畔", "指尖", "掌心", "脊背", "喉间", "眼底", "眸光",
            "呼吸", "心跳", "冷汗", "骨缝",
        },
        "动作": {
            "颤动", "颤抖", "战栗", "屏息", "发紧", "刺痛", "发麻", "埋进", "蜷缩",
        },
        "主题": set(),
        "符号": set(),
    }
    for cat, terms in category_map.items():
        if term in terms:
            return cat
    return None


def _covered_by_bible(term: str) -> str | None:
    relationship_terms = {
        "父亲", "母亲", "爹", "娘", "祖父", "祖母", "外祖父", "外祖母",
        "叔父", "叔母", "伯父", "伯母", "舅父", "舅母", "姑母", "姑父",
        "姨母", "姨父", "兄长", "长兄", "哥哥", "姐姐", "弟弟", "妹妹",
        "夫君", "娘子", "相公", "夫人",
        "师父", "师兄", "师姐", "师弟", "师妹", "老师", "掌柜", "老板",
    }
    social_status_terms = {
        "先生", "姑娘", "公子", "少爷", "小姐", "老爷",
        "殿下", "陛下", "王爷", "王妃", "娘娘", "太后",
    }
    emotional_terms = {
        "警觉", "内敛", "警觉内敛", "思绪清明", "强自镇定", "心绪如沸",
        "紧张", "焦虑", "愤怒", "悲伤", "恐惧", "绝望", "平静", "冷静",
        "镇定", "清明", "坚定", "犹豫", "惊恐", "惶恐", "不安", "忐忑",
        "欣慰", "释然", "愧疚", "懊悔", "决绝", "隐忍", "克制", "压抑",
    }
    if term in relationship_terms:
        return "CharacterProfile.relationships"
    if term in social_status_terms:
        return "CharacterState.social_status"
    if term in emotional_terms:
        return "CharacterState.emotional / MotifTracker"
    return None


def _check_coverage() -> tuple[dict[str, list[tuple[str, str]]], float]:
    results: dict[str, list[tuple[str, str]]] = {
        "_RHETORICAL_IMAGERY_HINTS": [],
        "_KINSHIP_AND_ADDRESS_TERMS": [],
        "_ABSTRACT_EMOTION_KEYWORDS": [],
    }

    for term in sorted(_RHETORICAL_IMAGERY_HINTS):
        cat = _covered_by_motif_category(term)
        if cat:
            results["_RHETORICAL_IMAGERY_HINTS"].append((term, f"Motif.category == '{cat}'"))
        else:
            results["_RHETORICAL_IMAGERY_HINTS"].append((term, "UNMAPPED"))

    for term in sorted(_KINSHIP_AND_ADDRESS_TERMS):
        src = _covered_by_bible(term)
        if src:
            results["_KINSHIP_AND_ADDRESS_TERMS"].append((term, src))
        else:
            results["_KINSHIP_AND_ADDRESS_TERMS"].append((term, "UNMAPPED"))

    for term in sorted(_ABSTRACT_EMOTION_KEYWORDS):
        src = _covered_by_bible(term)
        if src:
            results["_ABSTRACT_EMOTION_KEYWORDS"].append((term, src))
        else:
            results["_ABSTRACT_EMOTION_KEYWORDS"].append((term, "UNMAPPED"))

    total = sum(len(v) for v in results.values())
    mapped = sum(1 for v in results.values() for _, status in v if status != "UNMAPPED")
    coverage = (mapped / total) * 100.0 if total else 0.0
    return results, coverage


def _generate_report(results: dict[str, list[tuple[str, str]]], coverage: float) -> str:
    lines: list[str] = [
        "# Motif Coverage Report",
        "",
        "**Generated**: auto-generated by `scripts/verify_motif_parity.py`",
        "",
        "## Summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Total keywords | {sum(len(v) for v in results.values())} |",
        f"| Mapped | {sum(1 for v in results.values() for _, status in v if status != 'UNMAPPED')} |",
        f"| Unmapped | {sum(1 for v in results.values() for _, status in v if status == 'UNMAPPED')} |",
        f"| Coverage | {coverage:.1f}% |",
        "",
    ]

    for set_name, items in results.items():
        mapped_count = sum(1 for _, status in items if status != "UNMAPPED")
        lines.append(f"## {set_name} ({mapped_count}/{len(items)} mapped)")
        lines.append("")
        lines.append("| Keyword | Dynamic Source |")
        lines.append("|---------|----------------|")
        for term, status in items:
            src = status if status != "UNMAPPED" else "**UNMAPPED**"
            lines.append(f"| {term} | {src} |")
        lines.append("")

    lines.append("---")
    lines.append("")
    if coverage >= TARGET_COVERAGE:
        lines.append(f"PASS: Coverage {coverage:.1f}% >= {TARGET_COVERAGE}%")
    else:
        lines.append(f"FAIL: Coverage {coverage:.1f}% < {TARGET_COVERAGE}%")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    results, coverage = _check_coverage()
    report = _generate_report(results, coverage)

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(report, encoding="utf-8")

    print(report)

    if coverage >= TARGET_COVERAGE:
        print(f"\nPASS: Coverage {coverage:.1f}% >= {TARGET_COVERAGE}%")
        sys.exit(0)
    else:
        print(f"\nFAIL: Coverage {coverage:.1f}% < {TARGET_COVERAGE}%")
        sys.exit(1)


if __name__ == "__main__":
    main()
