"""Element data classes and library definitions."""

from __future__ import annotations

from dataclasses import dataclass, replace
from pathlib import Path
from typing import Any, Literal

from novel_forge.core.schemas.blueprint_elements import BlueprintElementCard

ELEMENT_LIBRARY_VERSION = "2026.05"
_REQUIRED_CORE_IDS: tuple[str, ...] = (
    "core_time_anchor",
    "core_location_anchor",
    "core_character_anchor",
    "core_event_chain",
    "core_phase_progression",
    "core_causal_closure",
)


@dataclass(frozen=True)
class _ElementDefinition:
    element_id: str
    name: str
    category: str
    tier: Literal["required", "extension"]
    description: str
    rationale: str
    recommended_genres: tuple[str, ...]
    prompt_hint: str
    ui_hint: str
    source: Literal["builtin", "external"] = "builtin"
    implementation_guide: str = ""
    verification_anchors: tuple[str, ...] = ()
    verification_mode: Literal["anchor", "structural", "llm"] = "anchor"
    intensity_hint: str = ""
    requires: tuple[str, ...] = ()
    excludes: tuple[str, ...] = ()
    complements: tuple[str, ...] = ()
    phase_affinity: tuple[str, ...] = ()

    def to_card(
        self,
        *,
        reason: str = "",
        selection_source: str = "",
        selection_score: float = 0.0,
        user_weight: float | None = None,
        user_locked: bool = False,
        user_enabled: bool | None = None,
    ) -> BlueprintElementCard:
        return BlueprintElementCard(
            element_id=self.element_id,
            name=self.name,
            category=self.category,
            tier=self.tier,
            description=self.description,
            rationale=self.rationale,
            recommended_genres=list(self.recommended_genres),
            prompt_hint=self.prompt_hint,
            implementation_guide=self.implementation_guide,
            verification_anchors=list(self.verification_anchors),
            verification_mode=self.verification_mode,
            intensity_hint=self.intensity_hint,
            requires=list(self.requires),
            excludes=list(self.excludes),
            complements=list(self.complements),
            phase_affinity=list(self.phase_affinity),
            ui_hint=self.ui_hint,
            selection_reason=reason,
            library_source=self.source,
            selection_source=selection_source,
            selection_score=max(0.0, float(selection_score or 0.0)),
            user_weight=user_weight,
            user_locked=user_locked,
            user_enabled=user_enabled,
        )


_ELEMENT_LIBRARY: tuple[_ElementDefinition, ...] = (
    _ElementDefinition(
        "core_time_anchor",
        "时间锚定",
        "叙事基础",
        "required",
        "锁定故事时间范围与关键时间节点，防止时序漂移。",
        "没有时间锚，章节推进容易出现白天黑夜与季节错位。",
        ("通用",),
        "在每个阶段注明时间段与时间推进触发点。",
        "timeline",
    ),
    _ElementDefinition(
        "core_location_anchor",
        "空间锚定",
        "叙事基础",
        "required",
        "明确主场景与阶段场景切换规则，避免地点跳切。",
        "场景不连续会直接损伤读者空间感和沉浸感。",
        ("通用",),
        "每个阶段标注主要地点与转场条件。",
        "map",
    ),
    _ElementDefinition(
        "core_character_anchor",
        "人物锚定",
        "叙事基础",
        "required",
        "固定核心角色名单、角色功能与叙事视角职责。",
        "角色职责不清会造成冲突焦点分散与动机失真。",
        ("通用",),
        '为核心角色写清"目标-阻力-变化"。',
        "card",
    ),
    _ElementDefinition(
        "core_event_chain",
        "事件链",
        "叙事基础",
        "required",
        "定义主事件链：触发事件、关键推进、终局事件。",
        "事件链是保持主线可追踪的最低骨架。",
        ("通用",),
        '按"触发-升级-决断-后果"组织关键事件。',
        "checklist",
    ),
    _ElementDefinition(
        "core_phase_progression",
        "起承转合推进",
        "叙事结构",
        "required",
        "保证叙事阶段具备起承转合与张力递进逻辑。",
        "结构闭环决定读者是否感知到'讲完一个完整故事'。",
        ("通用",),
        "至少拆分4段：引入、发展、对抗、收束。",
        "curve",
    ),
    _ElementDefinition(
        "core_causal_closure",
        "因果闭环",
        "叙事结构",
        "required",
        "确保关键决策都有代价与结果，避免悬空因果。",
        "因果闭环是连贯性和可信度的底层约束。",
        ("通用",),
        '关键转折必须给出"原因-行动-后果"。',
        "ledger",
    ),
    _ElementDefinition(
        "romance_emotional_barriers",
        "情感障碍阶梯",
        "言情机制",
        "extension",
        "设计关系推进中的外部障碍与内部障碍升级序列。",
        "言情主线依赖障碍层层解除，避免无阻力撒糖。",
        ("言情", "现言", "古言", "青春", "都市"),
        "让障碍与突破代价体现在具体场景冲突中，不要把阶段名或障碍标签直接写进正文。",
        "ladder",
    ),
    _ElementDefinition(
        "romance_relationship_contract",
        "关系契约与边界",
        "言情机制",
        "extension",
        "定义角色关系底线、承诺变化与关系拐点契约。",
        "明确边界能提升关系戏张力与冲突真实感。",
        ("言情", "婚恋", "破镜重圆", "双强"),
        '标注"关系初始状态-关键承诺-最终关系形态"。',
        "card",
    ),
    _ElementDefinition(
        "romance_sweet_bitter_ratio",
        "甜虐配比节奏",
        "言情机制",
        "extension",
        "控制糖点、虐点与回暖节点比例，防止情绪失衡。",
        "情绪曲线稳定直接影响追更与付费留存。",
        ("言情", "甜宠", "虐恋", "都市情感"),
        "给出每阶段情绪目标和回暖窗口。",
        "curve",
    ),
    _ElementDefinition(
        "farming_resource_loop",
        "资源经营循环",
        "种田经营",
        "extension",
        "建立资源投入-产出-再投入的成长循环。",
        "种田/经营叙事核心是看得见的积累与反馈。",
        ("种田", "经营", "古代日常", "基建"),
        "每阶段明确资源、收益、下一步投入方向。",
        "ledger",
    ),
    _ElementDefinition(
        "farming_season_calendar",
        "农事季节节律",
        "种田经营",
        "extension",
        "绑定季节、节气与生产活动的时间推进规则。",
        "季节节律是种田题材的真实感和节奏感来源。",
        ("种田", "古代", "乡土", "经营"),
        "在阶段描述中体现季节变化与农事节点。",
        "timeline",
    ),
    _ElementDefinition(
        "farming_community_network",
        "乡里关系网",
        "种田经营",
        "extension",
        "规划家族、邻里、乡绅、商贩关系带来的机会和阻力。",
        "社区关系网决定种田故事冲突密度与生活质感。",
        ("种田", "家长里短", "乡村", "古代日常"),
        "列出关键关系节点与利益变化。",
        "graph",
    ),
    _ElementDefinition(
        "mystery_clue_ledger",
        "线索账本",
        "悬疑推理",
        "extension",
        "记录线索投放、发现者、误导状态与回收章节。",
        "推理题材最怕线索遗失或超前泄底。",
        ("悬疑", "推理", "刑侦", "本格"),
        "每个关键线索标注投放章与回收章。",
        "ledger",
    ),
    _ElementDefinition(
        "mystery_red_herring",
        "误导线与反证",
        "悬疑推理",
        "extension",
        "设置合理红鲱鱼并安排反证揭示顺序。",
        "误导与反证能维持阅读猜测张力。",
        ("悬疑", "推理", "反转"),
        "将误导线与真相线并行标注。",
        "matrix",
    ),
    _ElementDefinition(
        "mystery_reveal_order",
        "真相揭示顺序",
        "悬疑推理",
        "extension",
        "规划真相拆解层级与揭秘节奏。",
        "揭示顺序决定反转是否成立。",
        ("悬疑", "推理", "刑侦"),
        "让假象、裂缝与真相通过不同场景逐步显形，不要把揭示阶段名直接写进正文。",
        "timeline",
    ),
    _ElementDefinition(
        "scifi_rule_reveal",
        "规则揭示顺序",
        "硬科幻",
        "extension",
        "定义世界规则/科技规则的分层揭示路径。",
        "硬科幻需要可验证规则而非随手设定。",
        ("科幻", "硬科幻", "太空歌剧"),
        "按阶段安排规则公开比例与验证场景。",
        "timeline",
    ),
    _ElementDefinition(
        "scifi_ethics_tradeoff",
        "科技伦理代价",
        "硬科幻",
        "extension",
        "为关键技术决策绑定伦理冲突与社会代价。",
        "没有代价约束的科技设定会失去可信度。",
        ("科幻", "赛博", "反乌托邦"),
        "每个重大技术选择写明收益与代价。",
        "matrix",
    ),
    _ElementDefinition(
        "progression_power_curve",
        "能力成长曲线",
        "升级成长",
        "extension",
        "规划主角能力阶段、上限与成长触发条件。",
        "升级流核心爽点来自可预期且有门槛的成长。",
        ("升级流", "玄幻", "异能", "游戏"),
        "按阶段标注能力层级、限制与突破成果。",
        "curve",
    ),
    _ElementDefinition(
        "progression_bottleneck_break",
        "瓶颈与突破机制",
        "升级成长",
        "extension",
        "明确瓶颈类型、突破代价与失败后果。",
        "没有瓶颈的成长会失去挑战感。",
        ("升级流", "玄幻", "修仙", "系统"),
        "至少设置两次硬瓶颈与一次高代价突破。",
        "ladder",
    ),
    _ElementDefinition(
        "xianxia_realm_resource",
        "境界-资源耦合",
        "仙侠玄幻",
        "extension",
        "绑定境界层级与资源获取、势力关系变化。",
        '修仙玄幻需要"境界与资源"双线协同才能稳定。',
        ("修仙", "玄幻", "仙侠"),
        "给出境界跃迁条件和资源竞争冲突。",
        "matrix",
    ),
    _ElementDefinition(
        "political_faction_balance",
        "阵营博弈平衡",
        "权谋战争",
        "extension",
        "维护势力目标、盟约变化与背叛成本。",
        "权谋题材依赖阵营关系的动态平衡。",
        ("权谋", "历史", "战争", "朝堂"),
        "每个阶段明确各方目标与可交易筹码。",
        "graph",
    ),
    _ElementDefinition(
        "war_frontline_shift",
        "战线推进与补给",
        "权谋战争",
        "extension",
        "规划战线推进、补给压力与战略目标切换。",
        "战争叙事需要空间推进和资源约束。",
        ("战争", "军事", "历史"),
        "转折点体现战线变化和代价。",
        "map",
    ),
    _ElementDefinition(
        "horror_dread_rhythm",
        "恐惧节奏管理",
        "恐怖惊悚",
        "extension",
        "安排压迫段、缓冲段与爆发段的节奏组合。",
        "持续高压会疲劳，节奏起伏才会放大恐惧。",
        ("恐怖", "惊悚", "怪谈"),
        "每个高潮前设置短暂安全窗口。",
        "curve",
    ),
    _ElementDefinition(
        "historical_protocol_constraint",
        "礼制与时代约束",
        "历史古代",
        "extension",
        "约束角色行为在时代制度与礼法框架内。",
        "历史题材需要行为逻辑和时代语境匹配。",
        ("历史", "古代", "宫廷", "权谋"),
        "关键冲突标注制度限制与破局方式。",
        "checklist",
    ),
    _ElementDefinition(
        "comedy_setup_payoff",
        "包袱铺垫回收",
        "喜剧轻松",
        "extension",
        "规划笑点铺垫、递进和回收节点。",
        "喜剧结构依赖节奏化回收，不只是堆梗。",
        ("喜剧", "轻小说", "日常"),
        "每个段落至少有一个功能型包袱回收。",
        "ledger",
    ),
    _ElementDefinition(
        "youth_growth_trigger",
        "成长触发器",
        "青春成长",
        "extension",
        "定义身份认同变化的触发事件与关系镜像。",
        "成长题材需要内在变化被外部事件触发。",
        ("青春", "校园", "成长"),
        "为主角安排价值观冲突与自我选择节点。",
        "ladder",
    ),
    _ElementDefinition(
        "workplace_goal_kpi",
        "任务闭环与KPI",
        "职场现实",
        "extension",
        "将职场目标拆解为阶段任务与结果反馈。",
        "职场叙事要有明确任务线和绩效后果。",
        ("职场", "现实", "都市"),
        "每阶段写清任务目标、阻碍、结果。",
        "checklist",
    ),
    _ElementDefinition(
        "thriller_countdown",
        "倒计时压力",
        "惊悚动作",
        "extension",
        "引入可量化倒计时并绑定失败后果。",
        "倒计时能自然提升节奏和危机强度。",
        ("惊悚", "动作", "灾难"),
        "转折点必须映射到倒计时节点。",
        "timeline",
    ),
    _ElementDefinition(
        "apocalypse_resource_scarcity",
        "末日资源稀缺",
        "末日生存",
        "extension",
        "追踪食物、水源、燃料、弹药等核心生存资源的消耗与争夺。",
        "稀缺性是末日题材的底层驱动力，决定角色选择和阵营冲突。",
        ("末日", "废土", "丧尸", "后启示录", "灾难"),
        "每阶段标注关键资源存量变化，及因稀缺导致的道德抉择。",
        "ledger",
    ),
    _ElementDefinition(
        "apocalypse_sanctuary_politics",
        "庇护所政治",
        "末日生存",
        "extension",
        "规划幸存者聚居点内部的权力结构、准入规则与领袖更替。",
        "封闭社群的内部矛盾比外部威胁更能驱动深层冲突。",
        ("末日", "废土", "后启示录", "灾难"),
        "定义聚居点的治理规则、分裂条件和信任崩塌触发点。",
        "graph",
    ),
    _ElementDefinition(
        "apocalypse_moral_erosion",
        "道德底线侵蚀",
        "末日生存",
        "extension",
        "追踪主角/群体道德标准在极端压力下的逐步滑移。",
        "道德侵蚀是末日叙事的核心张力——读者关注底线何时被突破。",
        ("末日", "废土", "丧尸", "后启示录"),
        '为关键抉择节点设置"道德成本"标签，记录角色底线的每次退让。',
        "ladder",
    ),
    _ElementDefinition(
        "fantasy_magic_cost",
        "魔法代价体系",
        "奇幻魔法",
        "extension",
        "定义魔法/超自然力量的使用规则、资源消耗与反噬代价。",
        "无代价的魔法会摧毁冲突张力，硬魔法体系是奇幻叙事可信度基石。",
        ("奇幻", "西幻", "魔法", "巫师", "黑暗奇幻"),
        "每次重大施法标注消耗类型、量级与不可逆后果。",
        "matrix",
    ),
    _ElementDefinition(
        "fantasy_prophecy_subversion",
        "预言与颠覆",
        "奇幻魔法",
        "extension",
        "管理预言/命运线索的投放、角色回应与最终颠覆或应验。",
        "预言驱动的叙事需要精确控制信息揭示节奏，避免剧透或落空。",
        ("奇幻", "西幻", "史诗", "命运", "神话"),
        "将预言拆为多层解读，每阶段只揭示一层含义，终章给出颠覆性解读。",
        "timeline",
    ),
    _ElementDefinition(
        "fantasy_race_culture",
        "种族文化碰撞",
        "奇幻魔法",
        "extension",
        "规划不同种族/文明间的文化差异、偏见壁垒与融合契机。",
        "种族设定是世界观深度的核心体现，也是跨阵营冲突的天然来源。",
        ("奇幻", "西幻", "史诗", "异世界"),
        "为涉及跨种族互动的场景标注文化冲突点和误解风险。",
        "graph",
    ),
    _ElementDefinition(
        "urban_hidden_world",
        "表里世界设定",
        "都市异能",
        "extension",
        "维护现实世界与超自然世界的交界规则、暴露风险与维持机制。",
        '双世界张力是都市异能的核心卖点——"普通人身边的非日常"。',
        ("都市异能", "无限流", "灵异", "现代奇幻"),
        "每次超自然事件标注暴露等级与掩盖代价。",
        "matrix",
    ),
    _ElementDefinition(
        "urban_instance_rules",
        "副本规则揭示",
        "无限流",
        "extension",
        "分层揭示副本/任务世界的隐藏规则，从表面规则到底层真相。",
        "规则推理是无限流的核心阅读爽点，要控制揭示节奏避免一次给完。",
        ("无限流", "规则怪谈", "生存游戏", "系统"),
        '每个副本拆为"表面规则→隐藏规则→真实规则"三层，逐层揭示。',
        "ladder",
    ),
    _ElementDefinition(
        "sports_training_arc",
        "训练-突破弧线",
        "体育竞技",
        "extension",
        "规划技能精进、体能极限与心理瓶颈的突破序列。",
        '竞技叙事的爽点来自"看得见的成长"与"突破极限的瞬间"。',
        ("竞技", "体育", "电竞", "棋牌"),
        "按赛季/赛事节点安排训练目标、瓶颈事件和突破成果。",
        "curve",
    ),
    _ElementDefinition(
        "sports_match_rhythm",
        "赛事节奏编排",
        "体育竞技",
        "extension",
        "控制比赛场景的攻防节奏、逆转时机与高光时刻安排。",
        "比赛场景是竞技文的核心场景，需要精确的节奏设计避免流水账。",
        ("竞技", "体育", "电竞", "格斗"),
        '每场关键赛事设计"落后→追平→反超"或"领先→危机→逆转"节奏模板。',
        "curve",
    ),
    _ElementDefinition(
        "sports_team_chemistry",
        "团队化学反应",
        "体育竞技",
        "extension",
        "追踪队友间信任、配合默契与内部冲突的演化。",
        "团队叙事依赖人际关系动态，单靠个人英雄主义无法支撑全程。",
        ("竞技", "体育", "电竞", "团队"),
        "标注团队信任度变化事件、磨合关键节点与分裂/凝聚触发器。",
        "graph",
    ),
    _ElementDefinition(
        "spy_cover_integrity",
        "身份伪装维护",
        "谍战间谍",
        "extension",
        "追踪主角/关键角色的伪装身份完整度与暴露风险。",
        '谍战核心张力来自"随时可能暴露"的持续危机感。',
        ("谍战", "间谍", "卧底", "潜伏"),
        "让伪装压力和暴露征兆体现在动作、对白失误与他人反应里，不要直接标注等级或风险信号。",
        "ladder",
    ),
    _ElementDefinition(
        "spy_intelligence_flow",
        "情报流转与验真",
        "谍战间谍",
        "extension",
        "管理情报获取、传递、验证和利用的完整链条。",
        "情报的真伪和流向决定谍战叙事的逻辑严密性。",
        ("谍战", "间谍", "军事", "冷战"),
        "每条关键情报标注来源、验证状态和使用时机。",
        "ledger",
    ),
    _ElementDefinition(
        "spy_loyalty_web",
        "忠诚网与双面人",
        "谍战间谍",
        "extension",
        "维护角色真实忠诚关系图，标注双面人身份和转变节点。",
        "忠诚反转是谍战题材的核心爆点，需要提前铺垫线索。",
        ("谍战", "间谍", "卧底", "反转"),
        '为可疑角色设计"表面忠诚链"与"真实忠诚链"的差异，标注揭示时机。',
        "graph",
    ),
    _ElementDefinition(
        "scifi_first_contact",
        "第一接触协议",
        "太空歌剧",
        "extension",
        "规划异文明接触时的沟通障碍、文化误读与冲突升级序列。",
        "第一接触场景需要精确的信息不对称设计，是太空歌剧的标志场景。",
        ("科幻", "太空歌剧", "星际", "外星"),
        "标注双方信息差、误解触发点和沟通突破条件。",
        "matrix",
    ),
    _ElementDefinition(
        "comedy_misunderstanding_chain",
        "误会连锁反应",
        "喜剧机制",
        "extension",
        "设计误会的投放、发酵和最终澄清的节奏曲线。",
        "误会喜剧的笑点来自层层叠加，过早澄清会扼杀喜剧效果。",
        ("喜剧", "轻小说", "日常", "言情"),
        "每个误会标注投放时机、发酵场景数和最大可容忍澄清延迟。",
        "timeline",
    ),
    _ElementDefinition(
        "youth_identity_mirror",
        "身份认同镜像",
        "青春成长",
        "extension",
        "通过与他人的关系映射来推动主角的自我认知变化。",
        '青春叙事的深层主题是"我是谁"——需要通过mirrors推动自我发现。',
        ("青春", "校园", "成长", "文艺"),
        '为每阶段指定一个"镜像角色"，其选择/态度迫使主角反思自我。',
        "card",
    ),
    _ElementDefinition(
        "workplace_office_politics",
        "职场权力博弈",
        "职场现实",
        "extension",
        "追踪办公室政治中的站队、利益交换与派系冲突。",
        "职场叙事仅有KPI不够，人际博弈才是读者关注的核心冲突。",
        ("职场", "都市", "现实", "商战"),
        "标注关键派系关系、利益节点和站队代价。",
        "graph",
    ),
    _ElementDefinition(
        "horror_unreliable_perception",
        "不可靠感知",
        "心理恐怖",
        "extension",
        "系统性引入知觉怀疑——主角（和读者）无法确定所见是否真实。",
        '心理恐怖的核心不是怪物，而是"你不能相信自己的眼睛"。',
        ("恐怖", "心理恐怖", "克苏鲁", "怪谈"),
        '每个恐怖场景标注"置信度等级"——真实事件 vs 可能的幻觉/误认。',
        "matrix",
    ),
    _ElementDefinition(
        "court_document_trail",
        "文书证据链",
        "官场权谋",
        "extension",
        "追踪奏疏、账册、判牍、密信等文书的来源、流转与证据效力。",
        "官场/权谋故事常以文书改变权力格局，证据链清楚才能让反转可信。",
        ("权谋", "历史", "官场", "朝堂", "悬疑"),
        "为关键文书标注来源、经手人、可验证细节、被篡改风险和最终使用时机。",
        "ledger",
    ),
    _ElementDefinition(
        "court_ceremony_power_map",
        "礼仪权力场",
        "官场权谋",
        "extension",
        "用朝会、宴饮、祭祀、审讯等仪式空间呈现权力排序与关系变化。",
        "制度化场景能把抽象权力变成可见动作，尤其适合历史/宫廷/朝堂。",
        ("权谋", "历史", "宫廷", "朝堂", "古代"),
        "每个仪式场景标注席位、称谓、行礼顺序、越礼行为及其政治后果。",
        "map",
    ),
    _ElementDefinition(
        "palace_private_public_split",
        "公私场域切换",
        "宫廷宅斗",
        "extension",
        "区分公开场合的身份表演与私密场合的真实交易、试探或崩溃。",
        "宫廷/宅斗张力来自同一人物在不同场域的面具差异。",
        ("宫廷", "宅斗", "家族", "古言", "权谋"),
        "每阶段安排至少一次公私场域反差，公开语言与私下真实目标必须互相照应。",
        "matrix",
    ),
    _ElementDefinition(
        "family_inheritance_pressure",
        "继承与家族债务",
        "家族宅斗",
        "extension",
        "追踪家族名分、财产、爵位、债务和声誉如何压迫角色选择。",
        "家族叙事的核心不是亲缘标签，而是资源与责任如何代际传递。",
        ("宅斗", "家族", "古代", "宫斗", "现实"),
        "为家族线标注继承资格、债务来源、可交易资源和每次退让的家庭代价。",
        "graph",
    ),
    _ElementDefinition(
        "wuxia_code_vs_survival",
        "侠义与生存冲突",
        "武侠江湖",
        "extension",
        "让侠义承诺、门派规矩与现实求生之间形成可检验冲突。",
        "武侠的情绪重量来自角色是否愿为原则付出代价。",
        ("武侠", "江湖", "古风", "复仇"),
        "每个关键抉择写清角色维护了哪条义理、牺牲了什么现实利益。",
        "ladder",
    ),
    _ElementDefinition(
        "wuxia_school_rivalry",
        "门派恩怨谱系",
        "武侠江湖",
        "extension",
        "管理门派、师承、旧仇、盟约与武学传承之间的关系网。",
        "江湖不是背景板，门派谱系能持续制造行动理由和身份压力。",
        ("武侠", "江湖", "仙侠", "古风"),
        "为门派关系标注旧怨根源、现行盟约、破盟代价和传承物证。",
        "graph",
    ),
    _ElementDefinition(
        "revenge_cost_ladder",
        "复仇代价阶梯",
        "复仇机制",
        "extension",
        "规划复仇行动从取证、试探、反击到终局清算的代价升级。",
        "复仇线需要让胜利越来越昂贵，否则只会变成机械打脸。",
        ("复仇", "权谋", "悬疑", "武侠", "都市"),
        "每次反击必须绑定一项新增代价：关系破裂、道德折损、身份暴露或资源耗尽。",
        "ladder",
    ),
    _ElementDefinition(
        "investigation_procedure_chain",
        "调查程序链",
        "刑侦调查",
        "extension",
        "把发现、取证、验证、推翻、复盘拆成清晰程序，约束破案逻辑。",
        "调查题材的爽点来自一步步逼近真相，而不是灵光一现。",
        ("刑侦", "悬疑", "推理", "谍战", "现实"),
        "每条线索必须标注获取方式、可信度、验证行动和可能被推翻的条件。",
        "checklist",
    ),
    _ElementDefinition(
        "business_market_feedback",
        "市场反馈回路",
        "商战经营",
        "extension",
        "追踪产品/策略投入市场后的竞争反应、现金流变化与信誉损益。",
        "商战和经营叙事需要外部反馈，避免角色只在会议室里赢。",
        ("商战", "经营", "职场", "都市", "创业"),
        "每阶段写清一次市场动作、对手反制、数据反馈和下一步策略修正。",
        "ledger",
    ),
    _ElementDefinition(
        "campus_social_rank",
        "校园关系阶层",
        "校园青春",
        "extension",
        "管理班级、社团、寝室、教师与家庭期待构成的隐性等级。",
        "校园故事的冲突往往来自小型社会秩序，而不只是考试或恋爱。",
        ("校园", "青春", "成长", "现实"),
        "为关键场景标注角色在小圈层中的位置变化和被排斥/接纳的触发点。",
        "graph",
    ),
    _ElementDefinition(
        "healing_daily_ritual",
        "治愈日常仪式",
        "治愈日常",
        "extension",
        "用重复但渐变的日常仪式承载角色恢复、关系升温和主题回响。",
        "治愈不是无冲突，而是让细小行动持续产生情绪修复。",
        ("治愈", "日常", "美食", "种田", "青春"),
        "设计一个会反复出现的日常动作，每次出现都必须有细微关系或认知变化。",
        "timeline",
    ),
    _ElementDefinition(
        "literary_symbol_motif",
        "象征母题织入",
        "文学风格",
        "extension",
        "选择少量核心物象/声音/动作，作为主题与人物变化的重复变奏。",
        "文学向作品需要意象承担结构功能，而不是只做漂亮描写。",
        ("文学", "文艺", "现实", "历史", "女性"),
        "限定2-4个核心母题，标注首次出现、变奏节点和终局回响。",
        "timeline",
    ),
    _ElementDefinition(
        "literary_silence_subtext",
        "沉默与潜台词",
        "文学风格",
        "extension",
        "让沉默、错答、转移话题和动作细节承担未说出口的信息。",
        "克制叙事的力量来自读者能读出角色没有说的话。",
        ("文学", "文艺", "悬疑", "言情", "现实"),
        "每个关键对话场景必须设计至少一处潜台词，但正文不得解释其含义。",
        "card",
    ),
    _ElementDefinition(
        "time_loop_variation",
        "循环差异记录",
        "时间机制",
        "extension",
        "追踪时间循环/重生/多周目的固定点、变量和记忆保留规则。",
        "时间机制题材若不记录变量，很容易前后矛盾或失去推理乐趣。",
        ("重生", "循环", "时间旅行", "科幻", "悬疑"),
        "每次循环标注不变量、已改变变量、角色记忆范围和新增代价。",
        "matrix",
    ),
    _ElementDefinition(
        "nonhuman_viewpoint_constraint",
        "非人视角约束",
        "特殊视角",
        "extension",
        "约束非人、AI、怪物、动物或异族 POV 的感知边界与价值判断。",
        "特殊视角的优势在于陌生化，必须避免写成普通人换皮。",
        ("科幻", "奇幻", "怪谈", "实验文学", "异族"),
        "列出该视角能感知/不能理解/误判的人类行为，并在场景中持续遵守。",
        "checklist",
    ),
    _ElementDefinition(
        "editorial_denouement_budget",
        "高潮后余波预算",
        "出版级编辑",
        "extension",
        "约束主高潮后章节数量、功能分配与确认性场景复用，防止多次尾声。",
        "长篇后段常因支线圆满、婚礼、终场回环叠加而退坡，需要在初始化时建立预算。",
        ("通用", "长篇", "言情", "商战", "悬疑", "都市"),
        "标注主高潮、预计余波章数、允许保留的尾声功能和禁止重复确认的场景类型。",
        "ledger",
    ),
    _ElementDefinition(
        "editorial_voice_matrix",
        "角色声纹矩阵",
        "出版级编辑",
        "extension",
        "为主要角色定义句长、停顿、解释倾向、情绪句法和禁用口吻。",
        "长篇多角色高压对话容易变成同一作者的整齐表达，需要声纹矩阵约束。",
        ("通用", "长篇", "言情", "群像", "商战", "权谋"),
        "每个主要角色给出可执行声纹：句式节奏、解释倾向、情绪升高时的变化和避用句式。",
        "matrix",
    ),
    _ElementDefinition(
        "editorial_revelation_ladder",
        "揭示阶梯",
        "出版级编辑",
        "extension",
        "把悬疑、记忆、前史、信物或世界规则拆成分级揭示，并要求每级带来行动后果。",
        "只反复写'快想起来了'会消耗悬疑，分级揭示能让信息递进绑定新选择。",
        ("悬疑", "言情", "前世今生", "奇幻", "科幻", "长篇"),
        "为重要信息线建立分级：每级写清触发物、允许透露的信息和必须产生的行动后果。",
        "ladder",
    ),
    _ElementDefinition(
        "editorial_scene_resistance",
        "场景阻力设计",
        "出版级编辑",
        "extension",
        "把谈判、对峙、等待、告白等场景的阻力落实为空间、流程、物件、人群或时间窗口。",
        "只有氛围没有阻力会让场景变软，阻力能迫使角色做选择。",
        ("通用", "商战", "言情", "悬疑", "职场", "权谋"),
        "每个关键场景至少设计一个可见阻力，如门、台阶、人群、签字窗口、屏幕、电话或物件传递。",
        "checklist",
    ),
    _ElementDefinition(
        "editorial_symbol_restraint",
        "象征解释克制",
        "出版级编辑",
        "extension",
        "约束核心信物、地点、主题句和反复意象的解释次数与升级方式。",
        "象征物每次出现都解释含义会削弱余味；应通过语境变化和动作承载意义。",
        ("文学", "言情", "前世今生", "历史", "都市", "长篇"),
        "为每个核心象征标注叙事功能、最多解释次数和再次出现时必须改变的语境功能。",
        "ledger",
    ),
    _ElementDefinition(
        "editorial_revision_plan",
        "出版修订方案",
        "出版级编辑",
        "extension",
        "把全书编辑审计结果转成章节合并、补戏、重命名、时间桥和语言删改的修订方案。",
        "出版级问题通常不能靠逐句修复解决，需要先结构压缩，再人物补戏，最后语言精修。",
        ("通用", "长篇", "出版", "连载", "改编"),
        "审计后按结构、人物、语言、标题、时间桥分层输出修订动作，不混入事实一致性修复。",
        "ledger",
    ),
    _ElementDefinition(
        "quality_hook_score_config",
        "钩子评分权重配置",
        "质量评估",
        "extension",
        "定义追读力评估中钩子强度的评分权重和微兑现上限，支持不同题材的差异化评分。",
        "不同题材对钩子强度的要求不同：网文追求强钩子，文学类作品允许弱钩子。",
        ("通用", "可配置"),
        "生成JSON配置：{hook_score_strong:4.0, hook_score_medium:2.5, hook_score_weak:1.0, payoff_cap:3, transition_penalty:1.0}",
        "config",
    ),
    _ElementDefinition(
        "quality_strand_keywords",
        "情节线关键词配置",
        "质量评估",
        "extension",
        "定义三条情节线（Quest/Fire/Constellation）的关键词集合，用于章节内容类型推断。",
        "不同题材的关键词差异大：推理用线索/证据，玄幻用修炼/突破，历史用奏对/朱批。",
        ("通用", "可配置"),
        "生成JSON配置：{quest_keywords:['战斗','任务'], fire_keywords:['感情','信任'], constellation_keywords:['势力','阵营']}",
        "config",
    ),
    _ElementDefinition(
        "quality_time_keywords",
        "时间验证关键词配置",
        "质量评估",
        "extension",
        "定义时间跨度验证的关键词集合，用于检测时间回跳和大跨度间隔。",
        "不同语言/题材的时间表达习惯不同：中文网文用三天后/数日后，西幻可用Three days later。",
        ("通用", "可配置"),
        "生成JSON配置：{large_gap_keywords:['三天后','数日后'], skip_keywords:['次日','翌日']}",
        "config",
    ),
    # ========================================================================
    # 新增：关系动态类
    # ========================================================================
    _ElementDefinition(
        "relationship_power_shift",
        "关系权力转移",
        "关系机制",
        "extension",
        "追踪角色间权力/地位/依赖关系的变化轨迹。",
        "关系张力常来自权力不对等及其动态变化，而非静态设定。",
        ("言情", "权谋", "职场", "家族", "通用"),
        "标注每次权力转移的触发事件、转移方向和后果。",
        "curve",
    ),
    _ElementDefinition(
        "relationship_trust_arc",
        "信任弧线",
        "关系机制",
        "extension",
        "管理角色间信任的建立、破裂与修复周期。",
        "信任变化是关系戏的核心驱动力，需要可追踪的节点。",
        ("言情", "谍战", "团队", "通用"),
        "为每段关键关系标注信任基线、破坏事件和修复条件。",
        "curve",
    ),
    _ElementDefinition(
        "relationship_boundary_test",
        "边界试探与突破",
        "关系机制",
        "extension",
        "设计角色间物理/情感/道德边界的试探、跨越与后果。",
        "关系推进常通过边界试探实现，需要控制试探节奏和代价。",
        ("言情", "悬疑", "心理", "通用"),
        "标注试探类型（语言/行为/情感）、被接受或拒绝的后果。",
        "ladder",
    ),
    # ========================================================================
    # 新增：叙事节奏类
    # ========================================================================
    _ElementDefinition(
        "pacing_breath_window",
        "节奏呼吸窗口",
        "叙事节奏",
        "extension",
        "在高强度场景后安排缓冲段，防止读者疲劳。",
        "持续高压会麻木，节奏起伏才能放大关键场景的冲击力。",
        ("通用", "惊悚", "动作", "悬疑"),
        "每个高潮后必须安排至少一个缓冲场景，承载情绪消化或信息整理。",
        "curve",
    ),
    _ElementDefinition(
        "pacing_tension_release",
        "张力释放曲线",
        "叙事节奏",
        "extension",
        "规划悬念/冲突的积累与释放节奏，避免过早泄底或持续悬空。",
        "张力管理决定读者是否愿意翻页——释放太早无趣，太晚疲劳。",
        ("通用", "悬疑", "言情", "惊悚"),
        "标注每个张力源的积累阶段、峰值和释放方式。",
        "curve",
    ),
    # ========================================================================
    # 新增：信息管理类
    # ========================================================================
    _ElementDefinition(
        "foreshadowing_thread",
        "伏笔线索管理",
        "伏笔管理",
        "extension",
        "追踪伏笔的投放、暗示强度与回收时机。",
        "伏笔需要精心控制暗示程度：太明显失去惊喜，太隐晦读者忽略。",
        ("通用", "悬疑", "奇幻", "科幻"),
        "每个伏笔标注投放章、暗示等级（弱/中/强）和预计回收章。",
        "ledger",
    ),
    _ElementDefinition(
        "information_asymmetry",
        "信息不对称设计",
        "信息管理",
        "extension",
        "管理读者、角色、POV之间的信息差，制造悬念或戏剧性讽刺。",
        "信息不对称是悬念和喜剧的核心机制，需要精确控制谁知道什么。",
        ("通用", "悬疑", "喜剧", "言情"),
        "标注每个场景的信息分布：读者知道什么、POV角色知道什么、其他角色知道什么。",
        "matrix",
    ),
    # ========================================================================
    # 新增：角色发展类
    # ========================================================================
    _ElementDefinition(
        "supporting_character_arc",
        "配角弧光",
        "角色发展",
        "extension",
        "为主要配角设计独立的变化轨迹，避免工具人化。",
        "配角弧光能增加世界真实感和主题厚度，但需控制篇幅不抢主线。",
        ("通用", "长篇", "群像"),
        "为每个主要配角标注起始状态、触发事件、变化方向和终局状态。",
        "card",
    ),
    _ElementDefinition(
        "antagonist_motivation",
        "反派动机深度",
        "角色发展",
        "extension",
        "为对手角色建立可信的动机体系，避免脸谱化。",
        "反派动机决定冲突质量——越可信的动机，冲突越有张力。",
        ("通用", "悬疑", "权谋", "奇幻"),
        "标注反派的核心诉求、道德自洽逻辑和不可妥协的底线。",
        "card",
    ),
    _ElementDefinition(
        "character_voice_differentiation",
        "角色声纹区分",
        "角色发展",
        "extension",
        "为每个主要角色定义独特的语言习惯、句式节奏和禁用表达。",
        "多角色对话容易变成同一作者的整齐表达，声纹区分能提升真实感。",
        ("通用", "长篇", "群像", "出版"),
        "为每个主要角色给出3-5个可执行声纹特征，如句式长度、口头禅、解释倾向。",
        "matrix",
    ),
    # ========================================================================
    # 新增：场景构建类
    # ========================================================================
    _ElementDefinition(
        "scene_atmosphere_layer",
        "场景氛围层次",
        "场景设计",
        "extension",
        "用感官细节、空间布局和环境变化构建场景氛围。",
        "氛围不是形容词堆砌，而是通过具体感官信号和空间关系传递。",
        ("通用", "文学", "恐怖", "言情"),
        "每个关键场景标注主导感官（视觉/听觉/嗅觉/触觉）、空间焦点和氛围基调。",
        "checklist",
    ),
    _ElementDefinition(
        "scene_purpose_clarity",
        "场景目的清晰度",
        "场景设计",
        "extension",
        "确保每个场景有明确的叙事功能：推进情节、揭示角色、建立关系或传递信息。",
        "无目的的场景会拖慢节奏，每个场景必须至少服务一个叙事目标。",
        ("通用",),
        "为每个场景标注主要目的和次要目的，删除无明确功能的场景。",
        "checklist",
    ),
    # ========================================================================
    # 新增：主题表达类
    # ========================================================================
    _ElementDefinition(
        "theme_question_progression",
        "主题问题推进",
        "主题表达",
        "extension",
        "将核心主题转化为可检验的问题，通过角色选择逐步回答。",
        "主题不是口号，而是通过角色在关键节点的选择来体现。",
        ("通用", "文学", "长篇"),
        "标注核心主题问题，以及每个关键场景如何推进对该问题的回答。",
        "ladder",
    ),
    _ElementDefinition(
        "moral_complexity",
        "道德复杂性",
        "主题表达",
        "extension",
        "避免非黑即白的道德判断，让角色在灰色地带做选择。",
        "道德复杂性提升故事深度，读者更关注'会怎么选'而非'谁对谁错'。",
        ("通用", "文学", "权谋", "末日"),
        "为关键抉择标注各选项的道德成本和收益，避免明显'正确'答案。",
        "matrix",
    ),
    # ========================================================================
    # 新增：文化/世界类
    # ========================================================================
    _ElementDefinition(
        "cultural_detail_integration",
        "文化细节融入",
        "世界构建",
        "extension",
        "通过饮食、服饰、礼仪、节日等日常细节展现文化背景。",
        "文化细节让世界真实可感，但需避免信息倾销，应融入场景动作。",
        ("历史", "奇幻", "古代", "乡土"),
        "每个涉及文化背景的场景标注1-2个具体细节，通过角色动作或对话自然呈现。",
        "checklist",
    ),
    _ElementDefinition(
        "worldbuilding_show_dont_tell",
        "世界观展示原则",
        "世界构建",
        "extension",
        "通过角色行为、冲突和后果展示世界规则，而非直接说明。",
        "直接说明世界观会打断叙事流，展示原则让读者自行拼凑理解。",
        ("科幻", "奇幻", "末日", "无限流"),
        "每个世界规则必须通过至少一个场景中的角色行动或后果来展示。",
        "checklist",
    ),
    # ========================================================================
    # 新增：修复预设引用（替换 custom_ 前缀要素）
    # ========================================================================
    _ElementDefinition(
        "family_dynamics_pressure",
        "家族动力压力",
        "家族宅斗",
        "extension",
        "追踪家族内部的权力结构、期望压力与代际冲突如何塑造角色选择。",
        "家族叙事的核心不是亲缘标签，而是资源、期望和责任如何代际传递。",
        ("宅斗", "家族", "古代", "现实"),
        "标注家族权力中心、角色在家族中的位置变化、以及每次家族事件对角色的压力。",
        "graph",
    ),
    _ElementDefinition(
        "mentor_apprentice_bond",
        "师徒羁绊",
        "武侠江湖",
        "extension",
        "管理师徒关系中的传承、期望、背叛与和解。",
        "师徒关系是武侠/修仙的核心情感线，承载技艺传承和价值观冲突。",
        ("武侠", "仙侠", "玄幻", "竞技"),
        "标注师徒关系的起始状态、传承内容、期望冲突和最终关系形态。",
        "card",
    ),
    _ElementDefinition(
        "food_narrative_vehicle",
        "食物叙事载体",
        "治愈日常",
        "extension",
        "用食物/烹饪作为情感表达、关系推进和主题承载的媒介。",
        "食物是跨越文化的情感语言，能自然承载记忆、关怀和关系变化。",
        ("治愈", "日常", "美食", "种田", "言情"),
        "每个与食物相关的场景标注食物类型、制作/分享过程和承载的情感或关系变化。",
        "timeline",
    ),
)


_ELEMENT_METADATA_PATCHES: dict[str, dict[str, Any]] = {
    "romance_emotional_barriers": {
        "complements": ("romance_sweet_bitter_ratio", "relationship_boundary_test"),
        "phase_affinity": ("develop", "climax"),
        "implementation_guide": "本章通过一次具体场景冲突展现障碍，例如外部压力事件、内心犹豫或第三方介入。障碍必须转化为动作、对白或选择代价，不要停留在关系说明。",
        "verification_anchors": ("外部压力事件", "内心犹豫动作", "第三方介入或误会升级"),
        "verification_mode": "structural",
        "intensity_hint": "聚焦章节至少安排一次可见阻力和一次关系反应。",
    },
    "romance_relationship_contract": {
        "complements": ("relationship_trust_arc", "relationship_power_shift"),
        "phase_affinity": ("intro", "develop", "resolution"),
        "implementation_guide": "让关系边界通过承诺、拒绝、条件交换或越界后果显形。正文必须写出角色如何守住或改写边界。",
        "verification_anchors": ("关系边界被说出或试探", "承诺条件变化", "越界后的后果"),
        "verification_mode": "structural",
        "intensity_hint": "聚焦章节以一次边界试探或承诺变化作为关系推进支点。",
    },
    "romance_sweet_bitter_ratio": {
        "complements": ("romance_emotional_barriers", "relationship_trust_arc"),
        "phase_affinity": ("develop", "climax", "resolution"),
        "implementation_guide": "本章明确安排一次情绪转折：甜点之后必须有代价或误会，虐点之后必须留出回暖窗口。不要只用情绪形容词，要写出触发事件。",
        "verification_anchors": ("情绪转折点", "回暖窗口", "障碍升级事件"),
        "verification_mode": "structural",
        "intensity_hint": "情绪起伏要可感知，但避免连续高强度拉扯。",
    },
    "mystery_clue_ledger": {
        "complements": ("mystery_reveal_order", "foreshadowing_thread", "investigation_procedure_chain"),
        "phase_affinity": ("intro", "develop", "climax"),
        "implementation_guide": "本章至少植入一条可回溯线索，可以是物件、对话漏洞、异常行为或记录痕迹。线索应能被读者事后复盘，但不能直接揭示答案。",
        "verification_anchors": ("新出现的可记录物件", "未被解释的对话片段", "角色的异常行为记录"),
        "verification_mode": "structural",
        "intensity_hint": "线索要具体可见，优先藏在行动和场景细节里。",
    },
    "mystery_red_herring": {
        "requires": ("mystery_clue_ledger",),
        "complements": ("information_asymmetry",),
        "phase_affinity": ("develop", "climax"),
        "implementation_guide": "误导线必须建立在真实可见证据上，同时留下可被反证的缝隙。不要让误导只靠角色口头猜测成立。",
        "verification_anchors": ("可疑但可反证的证据", "嫌疑方向被强化", "反证缝隙"),
        "verification_mode": "structural",
        "intensity_hint": "聚焦章节只强化一个主要误导，避免多线混乱。",
    },
    "mystery_reveal_order": {
        "requires": ("mystery_clue_ledger",),
        "complements": ("mystery_red_herring", "editorial_revelation_ladder"),
        "phase_affinity": ("develop", "climax", "resolution"),
        "implementation_guide": "本章只揭示真相的一层：先让假象裂开，再给出新的行动后果。不要一次性解释完整答案。",
        "verification_anchors": ("假象出现裂缝", "局部真相被确认", "揭示带来新行动后果"),
        "verification_mode": "structural",
        "intensity_hint": "揭示要递进，信息量服从本章行动后果。",
    },
    "scifi_rule_reveal": {
        "complements": ("worldbuilding_show_dont_tell", "information_asymmetry"),
        "phase_affinity": ("intro", "develop"),
        "implementation_guide": "让规则通过实验、失败、限制或他人反应被验证。不要用说明段一次性讲完科技设定。",
        "verification_anchors": ("规则被行动验证", "技术限制造成后果", "角色根据规则调整选择"),
        "verification_mode": "structural",
        "intensity_hint": "每章最多推进一条核心规则或一个规则例外。",
    },
    "scifi_ethics_tradeoff": {
        "complements": ("moral_complexity", "worldbuilding_show_dont_tell"),
        "phase_affinity": ("develop", "climax"),
        "implementation_guide": "把技术收益和伦理代价同时落到角色选择上，让至少一方承担可见损失。避免抽象辩论替代行动。",
        "verification_anchors": ("技术收益", "伦理代价", "角色承担损失"),
        "verification_mode": "structural",
        "intensity_hint": "冲突应有现实后果，而不是只停留在价值观讨论。",
    },
    "progression_power_curve": {
        "complements": ("progression_bottleneck_break", "sports_training_arc"),
        "phase_affinity": ("intro", "develop", "climax"),
        "implementation_guide": "写清能力当前上限、使用限制和进步触发条件。成长必须由训练、失败、资源或选择推动。",
        "verification_anchors": ("当前能力上限", "能力使用限制", "成长触发条件"),
        "verification_mode": "structural",
        "intensity_hint": "聚焦章节至少呈现一个限制和一个可见进步。",
    },
    "progression_bottleneck_break": {
        "requires": ("progression_power_curve",),
        "complements": ("xianxia_realm_resource",),
        "phase_affinity": ("develop", "climax"),
        "implementation_guide": "瓶颈必须以失败、资源不足、身体代价或规则门槛表现出来。突破要付出明确代价，并改变后续行动选择。",
        "verification_anchors": ("瓶颈失败", "突破代价", "突破后的能力变化"),
        "verification_mode": "structural",
        "intensity_hint": "突破不宜轻易完成，至少保留一个后续代价。",
    },
    "xianxia_realm_resource": {
        "requires": ("progression_power_curve",),
        "complements": ("progression_bottleneck_break", "mentor_apprentice_bond"),
        "phase_affinity": ("intro", "develop", "climax"),
        "implementation_guide": "境界变化必须绑定资源竞争、师承规则或势力后果。不要只写境界名升级。",
        "verification_anchors": ("境界门槛", "资源竞争", "势力关系变化"),
        "verification_mode": "structural",
        "intensity_hint": "聚焦章节优先呈现资源压力，而非堆叠术语。",
    },
    "horror_dread_rhythm": {
        "excludes": ("comedy_setup_payoff",),
        "complements": ("pacing_breath_window", "horror_unreliable_perception"),
        "phase_affinity": ("develop", "climax"),
        "implementation_guide": "恐惧应按安全错觉、异常信号、压迫升级、短暂缓冲的节奏推进。不要持续堆高音量式惊吓。",
        "verification_anchors": ("安全窗口被打破", "异常信号递增", "短暂缓冲段"),
        "verification_mode": "structural",
        "intensity_hint": "高压段之后必须留出呼吸窗口，放大下一次恐惧。",
    },
    "comedy_setup_payoff": {
        "excludes": ("horror_dread_rhythm",),
        "complements": ("comedy_misunderstanding_chain", "information_asymmetry"),
        "phase_affinity": ("intro", "develop", "resolution"),
        "implementation_guide": "笑点必须先有铺垫物、误解或重复动作，随后以角色选择造成回收。避免孤立段子破坏场景目标。",
        "verification_anchors": ("笑点铺垫", "误会递进", "回收动作"),
        "verification_mode": "structural",
        "intensity_hint": "聚焦章节保留一条主包袱链，不要密集堆梗。",
    },
    "thriller_countdown": {
        "complements": ("pacing_tension_release", "horror_dread_rhythm"),
        "phase_affinity": ("develop", "climax"),
        "implementation_guide": "倒计时必须有可量化剩余时间或机会次数，并绑定失败后果。每次推进都要改变角色选择。",
        "verification_anchors": ("可量化倒计时", "失败后果", "时间压力改变行动"),
        "verification_mode": "structural",
        "intensity_hint": "倒计时应推动行动，不作为背景装饰。",
    },
    "literary_symbol_motif": {
        "complements": ("literary_silence_subtext", "editorial_symbol_restraint"),
        "phase_affinity": ("intro", "develop", "resolution"),
        "implementation_guide": "选择一个物象、声音或动作在本章变奏出现，让它承载角色状态变化。不要解释象征含义。",
        "verification_anchors": ("重复物象变奏", "声音或动作回环", "语境功能变化"),
        "verification_mode": "structural",
        "intensity_hint": "克制使用，出现一次但必须有新语境。",
    },
    "literary_silence_subtext": {
        "complements": ("literary_symbol_motif", "scene_atmosphere_layer"),
        "phase_affinity": ("develop", "climax", "resolution"),
        "implementation_guide": "本章至少一处用沉默、错答、停顿、省略或环境细节承载潜台词。正文不要直白解释角色真实情绪。",
        "verification_anchors": ("未直说的情绪段落", "环境细节承载心理", "对话停顿或省略"),
        "verification_mode": "llm",
        "intensity_hint": "含蓄但必须可读，让读者能从动作和空白推断情绪。",
    },
    "relationship_power_shift": {
        "complements": ("romance_relationship_contract", "workplace_office_politics"),
        "phase_affinity": ("develop", "climax"),
        "implementation_guide": "通过资源、信息、身份或情绪筹码的变化，让关系中的主动权发生可见转移。",
        "verification_anchors": ("主动权变化", "筹码交换", "依赖关系改变"),
        "verification_mode": "structural",
        "intensity_hint": "聚焦章节要有一处权力位置变化，而非静态说明。",
    },
    "relationship_trust_arc": {
        "complements": ("romance_sweet_bitter_ratio", "spy_loyalty_web"),
        "phase_affinity": ("develop", "resolution"),
        "implementation_guide": "用一个具体选择改变信任水平：隐瞒、坦白、保护、背叛或补偿。必须写出对方的反应。",
        "verification_anchors": ("信任被破坏或修复", "坦白或隐瞒", "关系反应"),
        "verification_mode": "structural",
        "intensity_hint": "信任变化要小步可追踪，避免突然和解。",
    },
    "information_asymmetry": {
        "complements": ("mystery_clue_ledger", "comedy_setup_payoff", "spy_intelligence_flow"),
        "phase_affinity": ("intro", "develop", "climax"),
        "implementation_guide": "明确读者、POV角色和其他角色各自知道什么，并让信息差制造错误判断或行动优势。",
        "verification_anchors": ("读者与角色信息差", "POV误判", "信息优势改变行动"),
        "verification_mode": "structural",
        "intensity_hint": "聚焦章节只维护一组核心信息差，避免读者混乱。",
    },
    "foreshadowing_thread": {
        "complements": ("mystery_clue_ledger", "editorial_revelation_ladder"),
        "phase_affinity": ("intro", "develop"),
        "implementation_guide": "伏笔要以弱提示进入正文，例如异样物件、反常表情、重复措辞或不合时宜的细节。不要当场解释用途。",
        "verification_anchors": ("弱提示细节", "反常表情或措辞", "暂不解释的物件"),
        "verification_mode": "structural",
        "intensity_hint": "伏笔宁可少而准，不要密集插入多个无关暗示。",
    },
    "pacing_breath_window": {
        "complements": ("horror_dread_rhythm", "pacing_tension_release"),
        "phase_affinity": ("develop", "resolution"),
        "implementation_guide": "在高压事件后安排短暂缓冲，用整理信息、身体反应或环境静默承接余波。缓冲仍要服务后续选择。",
        "verification_anchors": ("高压后缓冲", "情绪余波", "信息整理"),
        "verification_mode": "structural",
        "intensity_hint": "缓冲应短而有效，不拖成无功能闲聊。",
    },
    "pacing_tension_release": {
        "complements": ("thriller_countdown", "pacing_breath_window"),
        "phase_affinity": ("develop", "climax", "resolution"),
        "implementation_guide": "让张力源先积累，再通过发现、摊牌、行动或代价释放一部分。释放后应产生新问题。",
        "verification_anchors": ("张力积累", "局部释放", "释放后的新问题"),
        "verification_mode": "structural",
        "intensity_hint": "不要只悬不放，也不要一次放空所有悬念。",
    },
    "scene_atmosphere_layer": {
        "complements": ("literary_silence_subtext", "horror_dread_rhythm"),
        "phase_affinity": ("intro", "develop", "climax"),
        "implementation_guide": "用具体感官、空间距离和环境变化塑造氛围，让氛围影响角色行动或判断。",
        "verification_anchors": ("主导感官细节", "空间焦点", "环境变化影响行动"),
        "verification_mode": "structural",
        "intensity_hint": "每个关键场景选择一到两个主导感官，避免堆形容词。",
    },
    "worldbuilding_show_dont_tell": {
        "complements": ("scifi_rule_reveal", "fantasy_magic_cost", "urban_instance_rules"),
        "phase_affinity": ("intro", "develop"),
        "implementation_guide": "世界规则必须通过角色行动、限制、失败或后果展示。避免解释性设定段落。",
        "verification_anchors": ("规则通过行动展示", "规则限制造成后果", "角色误用规则"),
        "verification_mode": "structural",
        "intensity_hint": "本章只展示与当前冲突直接相关的规则。",
    },
    "moral_complexity": {
        "complements": ("scifi_ethics_tradeoff", "apocalypse_moral_erosion", "revenge_cost_ladder"),
        "phase_affinity": ("develop", "climax"),
        "implementation_guide": "关键选择必须让多个选项都有代价和理由，避免明显正确答案。写出角色为何接受某项损失。",
        "verification_anchors": ("两难选择", "各选项代价", "角色承担损失"),
        "verification_mode": "structural",
        "intensity_hint": "冲突要有灰度，但不牺牲行动清晰度。",
    },
}


def _tuple_texts(value: Any) -> tuple[str, ...]:
    if not isinstance(value, (list, tuple, set)):
        return ()
    result: list[str] = []
    seen: set[str] = set()
    for raw in value:
        text = " ".join(str(raw or "").split()).strip()
        if not text or text in seen:
            continue
        seen.add(text)
        result.append(text)
    return tuple(result)


def _verification_mode(value: Any) -> Literal["anchor", "structural", "llm"]:
    mode = str(value or "anchor").strip().lower()
    if mode in {"anchor", "structural", "llm"}:
        return mode  # type: ignore[return-value]
    return "anchor"


def _apply_builtin_metadata(
    builtin: tuple[_ElementDefinition, ...],
) -> tuple[_ElementDefinition, ...]:
    patched: list[_ElementDefinition] = []
    for element in builtin:
        patch = _ELEMENT_METADATA_PATCHES.get(element.element_id)
        if patch:
            patch = dict(patch)
            for key in (
                "requires",
                "excludes",
                "complements",
                "phase_affinity",
                "verification_anchors",
            ):
                patch[key] = _tuple_texts(patch.get(key, ()))
            patch["verification_mode"] = _verification_mode(patch.get("verification_mode"))
            patched.append(replace(element, **patch))
        else:
            patched.append(element)
    return tuple(patched)


_ELEMENT_LIBRARY = _apply_builtin_metadata(_ELEMENT_LIBRARY)


def _repo_root() -> Path:
    for parent in Path(__file__).resolve().parents:
        if (parent / "pyproject.toml").exists() and (parent / "novel_forge").is_dir():
            return parent
    return Path(__file__).resolve().parents[4]


def external_element_library_path() -> Path:
    return _repo_root() / "data" / "element_library.json"


def _load_external_element_library() -> dict[str, dict[str, Any]]:
    try:
        path = external_element_library_path()
        if path.exists():
            import json

            with open(path, encoding="utf-8") as f:
                payload = json.load(f)
            return {item["element_id"]: item for item in payload.get("elements", [])}
    except Exception:
        pass
    return {}


def _merge_with_external(
    builtin: tuple[_ElementDefinition, ...],
) -> tuple[_ElementDefinition, ...]:
    external = _load_external_element_library()
    if not external:
        return builtin
    merged = {element.element_id: element for element in builtin}
    for eid, ext_data in external.items():
        merged[eid] = _ElementDefinition(
            element_id=eid,
            name=ext_data["name"],
            category=ext_data["category"],
            tier=ext_data.get("tier", "extension"),
            description=ext_data["description"],
            rationale=ext_data.get("rationale", ""),
            recommended_genres=tuple(ext_data.get("recommended_genres", [])),
            prompt_hint=ext_data.get("prompt_hint", ""),
            ui_hint=ext_data.get("ui_hint", "checklist"),
            source="external",
            implementation_guide=ext_data.get("implementation_guide", ""),
            verification_anchors=_tuple_texts(ext_data.get("verification_anchors", [])),
            verification_mode=_verification_mode(ext_data.get("verification_mode", "anchor")),
            intensity_hint=ext_data.get("intensity_hint", ""),
            requires=_tuple_texts(ext_data.get("requires", [])),
            excludes=_tuple_texts(ext_data.get("excludes", [])),
            complements=_tuple_texts(ext_data.get("complements", [])),
            phase_affinity=_tuple_texts(ext_data.get("phase_affinity", [])),
        )
    return tuple(merged.values())


_ELEMENT_LIBRARY = _merge_with_external(_ELEMENT_LIBRARY)
_LIBRARY_BY_ID: dict[str, _ElementDefinition] = {
    element.element_id: element for element in _ELEMENT_LIBRARY
}
_EXTENSION_LIBRARY_IDS: tuple[str, ...] = tuple(
    element.element_id for element in _ELEMENT_LIBRARY if element.tier == "extension"
)
_QUALITY_CONFIG_IDS: frozenset[str] = frozenset(
    {
        "quality_hook_score_config",
        "quality_strand_keywords",
        "quality_time_keywords",
    }
)
