#!/usr/bin/env python3
"""Generate the React parity settings fixture from the canonical Python catalog.

The fixture has no credentials and is used only by the mock EngineClient. It
lets Tauri/Playwright captures exercise the same task catalog as PySide.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_PATH = PROJECT_ROOT / "clients/nimo-desktop/src/lib/generated-settings.fixture.ts"

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))


def _camel_key(key: str) -> str:
    return re.sub(r"_([a-z0-9])", lambda match: match.group(1).upper(), key)


def _camelize(value: Any) -> Any:
    if isinstance(value, dict):
        return {_camel_key(str(key)): _camelize(item) for key, item in value.items()}
    if isinstance(value, list):
        return [_camelize(item) for item in value]
    return value


def fixture_view() -> dict[str, Any]:
    """Build a credential-free, capture-stable version of the real settings view."""

    from novel_forge.api.routes.ui_views import _compose_settings_view
    from novel_forge.core.config import Settings
    from novel_forge.gateway.profiles import ModelProfile, ProfilesConfig

    profiles = [
        ModelProfile("openai:gpt-4o-mini", "OpenAI Mini", "openai", "gpt-4o-mini", "fixture"),
        ModelProfile("tongyi:qwen-max", "阿里百炼 · Qwen Max", "tongyi", "qwen-max", "fixture"),
        ModelProfile(
            "deepseek:reasoner", "DeepSeek · Reasoner", "deepseek", "deepseek-reasoner", "fixture"
        ),
        ModelProfile("anthropic:sonnet", "Anthropic · Sonnet", "anthropic", "claude-sonnet-4"),
    ]
    view = _compose_settings_view(
        settings=Settings(_env_file=None),
        default_provider="tongyi",
        config=ProfilesConfig(profiles=profiles, default_profile_id="tongyi:qwen-max"),
    )
    view["mock_mode"] = True
    view["storage_root_label"] = "/tmp/nimo_ui_parity_fixture"
    return _camelize(view)


def render() -> str:
    payload = json.dumps(fixture_view(), ensure_ascii=False, indent=2, sort_keys=True)
    from novel_forge.app_service.engine_voice import _voice_provider_catalog_views

    provider_catalog = json.dumps(
        [item.model_dump(mode="json", by_alias=True) for item in _voice_provider_catalog_views()],
        ensure_ascii=False,
        indent=2,
        sort_keys=True,
    )
    return (
        "/* This file is generated by tools/ui-parity/generate_react_settings_fixture.py. */\n"
        "/* Do not edit by hand; run the generator after changing task_catalog.py. */\n"
        'import type { SettingsView, VoiceProviderView } from "@nimo/engine-contracts";\n\n'
        f"export const generatedSettingsFixture: SettingsView = {payload};\n\n"
        "export const generatedVoiceProviderCatalog: readonly VoiceProviderView[] = "
        f"{provider_catalog};\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="Fail when the checked-in fixture is stale."
    )
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT_PATH.exists() or OUTPUT_PATH.read_text(encoding="utf-8") != expected:
            print(f"Stale generated settings fixture: {OUTPUT_PATH}", file=sys.stderr)
            return 1
        return 0
    OUTPUT_PATH.write_text(expected, encoding="utf-8")
    print(OUTPUT_PATH)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
