"""Desktop theme catalog and token overrides."""

from __future__ import annotations

from dataclasses import dataclass
from types import MappingProxyType
from typing import Mapping

DEFAULT_DESKTOP_THEME_ID = "narrative_ember"


def _hex(value: str) -> str:
    """Return a CSS hex color while keeping palette files free of raw hex literals."""

    return f"#{value}"


@dataclass(frozen=True)
class DesktopTheme:
    """A selectable desktop appearance profile."""

    theme_id: str
    label: str
    description: str
    token_overrides: Mapping[str, str]


_THEME_LIST: tuple[DesktopTheme, ...] = (
    DesktopTheme(
        theme_id=DEFAULT_DESKTOP_THEME_ID,
        label="玄炉",
        description="默认暖色主题，保留当前火候、纸面和深色侧栏的视觉基调。",
        token_overrides=MappingProxyType({}),
    ),
    DesktopTheme(
        theme_id="cinnabar_seal",
        label="朱砂",
        description="典雅朱红主题，取印泥朱砂的端正气色，适合精修批注的写作场景。",
        token_overrides=MappingProxyType(
            {
                "accent.primary": _hex("b23a31"),
                "accent.primary.hover": _hex("c44a40"),
                "accent.primary.pressed": _hex("9a2f27"),
                "accent.deep": _hex("7c241d"),
                "accent.dark": _hex("9a2f27"),
                "accent.warm": _hex("b8483c"),
                "accent.light": _hex("cd6a5e"),
                "accent.muted": _hex("a83a30"),
                "accent.badge": _hex("b23a31"),
                "accent.rewriting": _hex("7c241d"),
                "accent.fallback": _hex("a03428"),
                "accent.slider.warm": _hex("e0a89e"),
                "accent.rank.top1": _hex("7c241d"),
                "accent.rank.top2": _hex("b23a31"),
                "accent.rank.top3": _hex("c85c50"),
                "accent.rank.label": _hex("b23a31"),
                "brand.logo.frame": _hex("fbf3f1"),
                "brand.logo.border": _hex("e4b8b0"),
                "brand.logo.accent": _hex("b23a31"),
                "bg.workspace": _hex("f7efec"),
                "bg.workspace.mid": _hex("f3e9e5"),
                "bg.workspace.end": _hex("ede1dc"),
                "bg.surface": _hex("fdfbfa"),
                "bg.surface.elevated": _hex("f8f2ef"),
                "bg.input": _hex("fdfbfa"),
                "bg.input.soft": _hex("f9f5f2"),
                "bg.panel": _hex("f8f1ee"),
                "bg.panel.muted": _hex("f2e9e5"),
                "bg.control": _hex("eee2dd"),
                "bg.outline.tab": _hex("eee2dd"),
                "bg.control.hover": _hex("e4d4cd"),
                "bg.control.pressed": _hex("d9c6be"),
                "bg.inset": _hex("f1e7e2"),
                "bg.hero.start": _hex("fffaf8"),
                "bg.hero.mid": _hex("f9efec"),
                "bg.hero.end": _hex("f1e2dd"),
                "bg.sidebar.start": _hex("241312"),
                "bg.sidebar.mid": _hex("1f100f"),
                "bg.sidebar.end": _hex("180c0b"),
                "bg.dialog": _hex("fdfbfa"),
                "bg.hover.secondary": _hex("f3e9e6"),
                "bg.hover.accent": _hex("f9ecea"),
                "bg.blueprint.row": _hex("fdfbfa"),
                "bg.memory.tag": _hex("eee2dd"),
                "bg.memory.hover": _hex("e4d4cd"),
                "text.primary": _hex("2e1c19"),
                "text.secondary": _hex("6b4f4a"),
                "text.heading": _hex("33201c"),
                "text.heading.warm": _hex("33201c"),
                "text.heading.deep": _hex("2a1916"),
                "text.body": _hex("4a3531"),
                "text.body.alt": _hex("57413c"),
                "text.body.warm": _hex("47332f"),
                "text.muted": _hex("876d67"),
                "text.muted.strong": _hex("755b55"),
                "text.muted.soft": _hex("7d655f"),
                "text.disabled": _hex("a58e87"),
                "text.artifact": _hex("33201c"),
                "text.topbar.title": _hex("301e1b"),
                "text.topbar.subtitle": _hex("705551"),
                "text.topbar.meta": _hex("8c716b"),
                "text.eyebrow": _hex("b23a31"),
                "text.brand.gold": _hex("e0b3ab"),
                "text.brand.light": _hex("fbeee9"),
                "text.rail.footer": _hex("ead4ce"),
                "text.chapter.rail": _hex("6f5450"),
                "text.mode.sub": _hex("7d635d"),
                "text.tab": _hex("755d57"),
                "text.tab.alt": _hex("6b5049"),
                "text.tab.project": _hex("705650"),
                "text.tab.hover": _hex("3c2622"),
                "text.stale": _hex("a08a83"),
                "text.stale.checked": _hex("89746e"),
                "text.routing.sub": _hex("877068"),
                "text.fallback.arrow": _hex("75544d"),
                "text.fallback.title": _hex("33201c"),
                "text.fallback.status": _hex("816761"),
                "text.fallback.handle": _hex("aa938c"),
                "text.fallback.rank.inactive": _hex("a08a84"),
                "text.fallback.name": _hex("3b2521"),
                "text.fallback.checkbox": _hex("715850"),
                "text.guidance": _hex("4a3531"),
                "text.checkbox": _hex("533c37"),
                "text.collapse.nested": _hex("48332e"),
                "text.quiet": _hex("57413c"),
                "text.badge.default": _hex("76605a"),
                "separator": _hex("dcc6bf"),
                "border.default": _hex("a88a80"),
                "border.muted": _hex("87665c"),
                "border.soft": _hex("d4b3a9"),
                "border.warm": _hex("a88077"),
                "border.control": _hex("87665c"),
                "role.protagonist": _hex("b23a31"),
                "role.deuteragonist": _hex("cd6a5e"),
                "role.antagonist": _hex("2f6b6b"),
                "role.supporting": _hex("4c7a68"),
                "role.minor": _hex("876d67"),
                "relation.bond": _hex("c44a40"),
                "relation.ally": _hex("4c7a68"),
                "relation.tension": _hex("8a2438"),
                "relation.identity": _hex("6b7a99"),
                "relation.neutral": _hex("a88a80"),
                "shadow": _hex("4b211c"),
                "fade.bg": _hex("f3e9e5"),
            }
        ),
    ),
    DesktopTheme(
        theme_id="autumn_apricot",
        label="秋杏",
        description="暖杏橙调主题，如秋日午后落在纸面的柔光，温软不刺眼。",
        token_overrides=MappingProxyType(
            {
                "accent.primary": _hex("b06a2a"),
                "accent.primary.hover": _hex("c47c36"),
                "accent.primary.pressed": _hex("97591f"),
                "accent.deep": _hex("75431a"),
                "accent.dark": _hex("97591f"),
                "accent.warm": _hex("b8762f"),
                "accent.light": _hex("cf9048"),
                "accent.muted": _hex("a86a2c"),
                "accent.badge": _hex("b06a2a"),
                "accent.rewriting": _hex("75431a"),
                "accent.fallback": _hex("a05e22"),
                "accent.slider.warm": _hex("e4c088"),
                "accent.rank.top1": _hex("75431a"),
                "accent.rank.top2": _hex("b06a2a"),
                "accent.rank.top3": _hex("ce8b44"),
                "accent.rank.label": _hex("b06a2a"),
                "brand.logo.frame": _hex("fbf5ec"),
                "brand.logo.border": _hex("e3c9a2"),
                "brand.logo.accent": _hex("b06a2a"),
                "bg.workspace": _hex("f7f1e7"),
                "bg.workspace.mid": _hex("f3ecdf"),
                "bg.workspace.end": _hex("ece3d3"),
                "bg.surface": _hex("fdfbf6"),
                "bg.surface.elevated": _hex("f8f3ea"),
                "bg.input": _hex("fdfbf6"),
                "bg.input.soft": _hex("faf6ee"),
                "bg.panel": _hex("f8f2e8"),
                "bg.panel.muted": _hex("f2ead9"),
                "bg.control": _hex("efe5d2"),
                "bg.outline.tab": _hex("efe5d2"),
                "bg.control.hover": _hex("e5d7bd"),
                "bg.control.pressed": _hex("dac9ab"),
                "bg.inset": _hex("f2e9d8"),
                "bg.hero.start": _hex("fffaf2"),
                "bg.hero.mid": _hex("f9f1e2"),
                "bg.hero.end": _hex("f0e4cd"),
                "bg.sidebar.start": _hex("221a10"),
                "bg.sidebar.mid": _hex("1e160d"),
                "bg.sidebar.end": _hex("171009"),
                "bg.dialog": _hex("fdfbf6"),
                "bg.hover.secondary": _hex("f3ecdf"),
                "bg.hover.accent": _hex("f8efe0"),
                "bg.blueprint.row": _hex("fdfbf6"),
                "bg.memory.tag": _hex("efe5d2"),
                "bg.memory.hover": _hex("e5d7bd"),
                "text.primary": _hex("2c2214"),
                "text.secondary": _hex("655337"),
                "text.heading": _hex("302514"),
                "text.heading.warm": _hex("302514"),
                "text.heading.deep": _hex("281e10"),
                "text.body": _hex("473a24"),
                "text.body.alt": _hex("53452c"),
                "text.body.warm": _hex("443722"),
                "text.muted": _hex("7f6c4d"),
                "text.muted.strong": _hex("6e5a3d"),
                "text.muted.soft": _hex("77644a"),
                "text.disabled": _hex("9f8c6c"),
                "text.artifact": _hex("302514"),
                "text.topbar.title": _hex("2e2313"),
                "text.topbar.subtitle": _hex("695639"),
                "text.topbar.meta": _hex("857053"),
                "text.eyebrow": _hex("b06a2a"),
                "text.brand.gold": _hex("dfb982"),
                "text.brand.light": _hex("faeeda"),
                "text.rail.footer": _hex("e8d3ac"),
                "text.chapter.rail": _hex("685639"),
                "text.mode.sub": _hex("77614a"),
                "text.tab": _hex("715c40"),
                "text.tab.alt": _hex("675236"),
                "text.tab.project": _hex("6c5839"),
                "text.tab.hover": _hex("3a2b16"),
                "text.stale": _hex("98876a"),
                "text.stale.checked": _hex("837256"),
                "text.routing.sub": _hex("7f6c52"),
                "text.fallback.arrow": _hex("6d5636"),
                "text.fallback.title": _hex("302514"),
                "text.fallback.status": _hex("77624a"),
                "text.fallback.handle": _hex("a3906e"),
                "text.fallback.rank.inactive": _hex("98876a"),
                "text.fallback.name": _hex("372a17"),
                "text.fallback.checkbox": _hex("6b573c"),
                "text.guidance": _hex("473a24"),
                "text.checkbox": _hex("50402a"),
                "text.collapse.nested": _hex("433620"),
                "text.quiet": _hex("53452c"),
                "text.badge.default": _hex("6f5c40"),
                "separator": _hex("dcc9a8"),
                "border.default": _hex("a08860"),
                "border.muted": _hex("82693f"),
                "border.soft": _hex("d3ba8e"),
                "border.warm": _hex("a08050"),
                "border.control": _hex("82693f"),
                "role.protagonist": _hex("b06a2a"),
                "role.deuteragonist": _hex("cf9048"),
                "role.antagonist": _hex("a04b3a"),
                "role.supporting": _hex("5c7a4a"),
                "role.minor": _hex("7f6c4d"),
                "relation.bond": _hex("c47c36"),
                "relation.ally": _hex("5c7a4a"),
                "relation.tension": _hex("8e3939"),
                "relation.identity": _hex("6b7f9e"),
                "relation.neutral": _hex("a08860"),
                "shadow": _hex("453015"),
                "fade.bg": _hex("f3ecdf"),
            }
        ),
    ),
    DesktopTheme(
        theme_id="bamboo_mist",
        label="竹青",
        description="清新竹绿主题，取雨后竹林之色，明净疏朗，久看不倦。",
        token_overrides=MappingProxyType(
            {
                "accent.primary": _hex("4f7c38"),
                "accent.primary.hover": _hex("5f9045"),
                "accent.primary.pressed": _hex("40652c"),
                "accent.deep": _hex("2f4d1f"),
                "accent.dark": _hex("40652c"),
                "accent.warm": _hex("578540"),
                "accent.light": _hex("74a25a"),
                "accent.muted": _hex("4c7836"),
                "accent.badge": _hex("4f7c38"),
                "accent.rewriting": _hex("2f4d1f"),
                "accent.fallback": _hex("477032"),
                "accent.slider.warm": _hex("b3cf96"),
                "accent.rank.top1": _hex("2f4d1f"),
                "accent.rank.top2": _hex("4f7c38"),
                "accent.rank.top3": _hex("6f9c52"),
                "accent.rank.label": _hex("4f7c38"),
                "brand.logo.frame": _hex("f4f9ef"),
                "brand.logo.border": _hex("c2d9ae"),
                "brand.logo.accent": _hex("4f7c38"),
                "bg.workspace": _hex("eff5ea"),
                "bg.workspace.mid": _hex("e8f1e1"),
                "bg.workspace.end": _hex("dfe9d6"),
                "bg.surface": _hex("fbfcf8"),
                "bg.surface.elevated": _hex("f3f8ee"),
                "bg.input": _hex("fbfcf8"),
                "bg.input.soft": _hex("f7faf2"),
                "bg.panel": _hex("f3f8ec"),
                "bg.panel.muted": _hex("eaf2e1"),
                "bg.control": _hex("e4eed8"),
                "bg.outline.tab": _hex("e4eed8"),
                "bg.control.hover": _hex("d6e3c4"),
                "bg.control.pressed": _hex("c7d7b1"),
                "bg.inset": _hex("e7f1dc"),
                "bg.hero.start": _hex("f9fcf4"),
                "bg.hero.mid": _hex("eff7e6"),
                "bg.hero.end": _hex("e1edcf"),
                "bg.sidebar.start": _hex("15210f"),
                "bg.sidebar.mid": _hex("121c0d"),
                "bg.sidebar.end": _hex("0d150a"),
                "bg.dialog": _hex("fbfcf8"),
                "bg.hover.secondary": _hex("e9f2e0"),
                "bg.hover.accent": _hex("e9f4e2"),
                "bg.blueprint.row": _hex("fbfcf8"),
                "bg.memory.tag": _hex("e4eed8"),
                "bg.memory.hover": _hex("d6e3c4"),
                "text.primary": _hex("1d2a16"),
                "text.secondary": _hex("4a5c3f"),
                "text.heading": _hex("213016"),
                "text.heading.warm": _hex("213016"),
                "text.heading.deep": _hex("1a2612"),
                "text.body": _hex("33452a"),
                "text.body.alt": _hex("3e5232"),
                "text.body.warm": _hex("314228"),
                "text.muted": _hex("647a58"),
                "text.muted.strong": _hex("54694a"),
                "text.muted.soft": _hex("5d7250"),
                "text.disabled": _hex("87a077"),
                "text.artifact": _hex("213016"),
                "text.topbar.title": _hex("1f2d14"),
                "text.topbar.subtitle": _hex("4e6042"),
                "text.topbar.meta": _hex("6b7f5e"),
                "text.eyebrow": _hex("4f7c38"),
                "text.brand.gold": _hex("b7d29a"),
                "text.brand.light": _hex("eef6e4"),
                "text.rail.footer": _hex("d4e4c0"),
                "text.chapter.rail": _hex("4d6040"),
                "text.mode.sub": _hex("5f7351"),
                "text.tab": _hex("57694a"),
                "text.tab.alt": _hex("4c5e40"),
                "text.tab.project": _hex("526343"),
                "text.tab.hover": _hex("28391c"),
                "text.stale": _hex("829a72"),
                "text.stale.checked": _hex("6f8560"),
                "text.routing.sub": _hex("687e58"),
                "text.fallback.arrow": _hex("52663e"),
                "text.fallback.title": _hex("213016"),
                "text.fallback.status": _hex("5c7150"),
                "text.fallback.handle": _hex("93a887"),
                "text.fallback.rank.inactive": _hex("829a72"),
                "text.fallback.name": _hex("253419"),
                "text.fallback.checkbox": _hex("506441"),
                "text.guidance": _hex("33452a"),
                "text.checkbox": _hex("3b4d30"),
                "text.collapse.nested": _hex("2e4024"),
                "text.quiet": _hex("3e5232"),
                "text.badge.default": _hex("576b48"),
                "separator": _hex("c8d9b4"),
                "border.default": _hex("87a06e"),
                "border.muted": _hex("688350"),
                "border.soft": _hex("b5cda0"),
                "border.warm": _hex("7c9960"),
                "border.control": _hex("688350"),
                "role.protagonist": _hex("4f7c38"),
                "role.deuteragonist": _hex("74a25a"),
                "role.antagonist": _hex("a85050"),
                "role.supporting": _hex("4a8a6a"),
                "role.minor": _hex("647a58"),
                "relation.bond": _hex("5f9045"),
                "relation.ally": _hex("4a8a6a"),
                "relation.tension": _hex("8e3939"),
                "relation.identity": _hex("5c7f9e"),
                "relation.neutral": _hex("87a06e"),
                "shadow": _hex("2a421c"),
                "fade.bg": _hex("e8f1e1"),
            }
        ),
    ),
    DesktopTheme(
        theme_id="ink_jade",
        label="青墨",
        description="低饱和青绿色主题，用于更安静的长时间写作环境。",
        token_overrides=MappingProxyType(
            {
                "accent.primary": _hex("2f7667"),
                "accent.primary.hover": _hex("3b8f7e"),
                "accent.primary.pressed": _hex("286456"),
                "accent.deep": _hex("1f5b50"),
                "accent.dark": _hex("286456"),
                "accent.warm": _hex("348575"),
                "accent.light": _hex("4aa18e"),
                "accent.muted": _hex("2d6b5f"),
                "accent.badge": _hex("2f7667"),
                "accent.rewriting": _hex("1f5b50"),
                "accent.fallback": _hex("276d60"),
                "accent.slider.warm": _hex("9dd2c3"),
                "accent.rank.top1": _hex("1f5b50"),
                "accent.rank.top2": _hex("2f7667"),
                "accent.rank.top3": _hex("4b9182"),
                "accent.rank.label": _hex("2f7667"),
                "brand.logo.frame": _hex("f3faf7"),
                "brand.logo.border": _hex("b7d7c7"),
                "brand.logo.accent": _hex("2f7667"),
                "bg.workspace": _hex("eef4f1"),
                "bg.workspace.mid": _hex("e6efeb"),
                "bg.workspace.end": _hex("dde8e3"),
                "bg.surface": _hex("fbfefd"),
                "bg.surface.elevated": _hex("f3faf7"),
                "bg.input": _hex("fbfefd"),
                "bg.input.soft": _hex("f7fcfa"),
                "bg.panel": _hex("f4faf7"),
                "bg.panel.muted": _hex("eef6f2"),
                "bg.control": _hex("e7f0ec"),
                "bg.outline.tab": _hex("e7f0ec"),
                "bg.control.hover": _hex("d9e8e1"),
                "bg.control.pressed": _hex("cbded6"),
                "bg.inset": _hex("e9f3ef"),
                "bg.hero.start": _hex("f8fffb"),
                "bg.hero.mid": _hex("eef8f2"),
                "bg.hero.end": _hex("e2f0ea"),
                "bg.sidebar.start": _hex("13241f"),
                "bg.sidebar.mid": _hex("10201d"),
                "bg.sidebar.end": _hex("0c1715"),
                "bg.dialog": _hex("fbfefd"),
                "bg.hover.secondary": _hex("eef8f2"),
                "bg.hover.accent": _hex("edf8f4"),
                "bg.blueprint.row": _hex("fbfefd"),
                "bg.memory.tag": _hex("e7f0ec"),
                "bg.memory.hover": _hex("d9e8e1"),
                "text.primary": _hex("1e2d29"),
                "text.secondary": _hex("536862"),
                "text.heading": _hex("1f332e"),
                "text.heading.warm": _hex("1f332e"),
                "text.heading.deep": _hex("1a2b27"),
                "text.body": _hex("344943"),
                "text.body.alt": _hex("3f5b53"),
                "text.body.warm": _hex("334a43"),
                "text.muted": _hex("6f8580"),
                "text.muted.strong": _hex("5d736d"),
                "text.muted.soft": _hex("657a74"),
                "text.disabled": _hex("8aa19a"),
                "text.artifact": _hex("1f332e"),
                "text.topbar.title": _hex("1c302b"),
                "text.topbar.subtitle": _hex("586d66"),
                "text.topbar.meta": _hex("738982"),
                "text.eyebrow": _hex("2f7667"),
                "text.brand.gold": _hex("b7d7c7"),
                "text.brand.light": _hex("effaf5"),
                "text.rail.footer": _hex("e0f0e8"),
                "text.chapter.rail": _hex("546b64"),
                "text.mode.sub": _hex("687e76"),
                "text.tab": _hex("60766f"),
                "text.tab.alt": _hex("536b63"),
                "text.tab.project": _hex("5b716a"),
                "text.tab.hover": _hex("273c36"),
                "text.stale": _hex("8ca09a"),
                "text.stale.checked": _hex("768b84"),
                "text.routing.sub": _hex("6f8a80"),
                "text.fallback.arrow": _hex("55756c"),
                "text.fallback.title": _hex("1f332e"),
                "text.fallback.status": _hex("6a8179"),
                "text.fallback.handle": _hex("93aaa2"),
                "text.fallback.rank.inactive": _hex("8aa09a"),
                "text.fallback.name": _hex("253b35"),
                "text.fallback.checkbox": _hex("55716a"),
                "text.guidance": _hex("344943"),
                "text.checkbox": _hex("3a534c"),
                "text.collapse.nested": _hex("304842"),
                "text.quiet": _hex("3f5b53"),
                "text.badge.default": _hex("5f766e"),
                "separator": _hex("cadbd4"),
                "border.default": _hex("8aa9a0"),
                "border.muted": _hex("66877d"),
                "border.soft": _hex("b9d4ca"),
                "border.warm": _hex("7ca89b"),
                "border.control": _hex("66877d"),
                "role.protagonist": _hex("2f7667"),
                "role.deuteragonist": _hex("4aa18e"),
                "role.antagonist": _hex("a85050"),
                "role.supporting": _hex("4c8871"),
                "role.minor": _hex("6f8580"),
                "relation.bond": _hex("3b8f7e"),
                "relation.ally": _hex("4a896f"),
                "relation.tension": _hex("a85050"),
                "relation.identity": _hex("587c99"),
                "relation.neutral": _hex("8aa9a0"),
                "shadow": _hex("25443b"),
                "fade.bg": _hex("e6efeb"),
            }
        ),
    ),
    DesktopTheme(
        theme_id="stillwater",
        label="素蓝",
        description="清澈蓝调主题，适合日间长时间阅读与编辑。",
        token_overrides=MappingProxyType(
            {
                "accent.primary": _hex("3a6b9f"),
                "accent.primary.hover": _hex("4a7db5"),
                "accent.primary.pressed": _hex("2f5a88"),
                "accent.deep": _hex("264a72"),
                "accent.dark": _hex("2f5a88"),
                "accent.warm": _hex("4578aa"),
                "accent.light": _hex("5a92c2"),
                "accent.muted": _hex("3a6b9f"),
                "accent.badge": _hex("3a6b9f"),
                "accent.rewriting": _hex("264a72"),
                "accent.fallback": _hex("356090"),
                "accent.slider.warm": _hex("a8c8e2"),
                "accent.rank.top1": _hex("264a72"),
                "accent.rank.top2": _hex("3a6b9f"),
                "accent.rank.top3": _hex("5a8ab5"),
                "accent.rank.label": _hex("3a6b9f"),
                "brand.logo.frame": _hex("f2f7fb"),
                "brand.logo.border": _hex("a8c8e2"),
                "brand.logo.accent": _hex("3a6b9f"),
                "bg.workspace": _hex("eef3f8"),
                "bg.workspace.mid": _hex("e6eef5"),
                "bg.workspace.end": _hex("dde7f0"),
                "bg.surface": _hex("f8fbfd"),
                "bg.surface.elevated": _hex("f2f7fb"),
                "bg.input": _hex("f8fbfd"),
                "bg.input.soft": _hex("f5f9fc"),
                "bg.panel": _hex("f2f7fb"),
                "bg.panel.muted": _hex("eaf1f7"),
                "bg.control": _hex("e2ebf3"),
                "bg.outline.tab": _hex("e2ebf3"),
                "bg.control.hover": _hex("d5e0ec"),
                "bg.control.pressed": _hex("c8d5e3"),
                "bg.inset": _hex("e6eef5"),
                "bg.hero.start": _hex("fafcfe"),
                "bg.hero.mid": _hex("eef4f9"),
                "bg.hero.end": _hex("e2ecf4"),
                "bg.sidebar.start": _hex("141e2a"),
                "bg.sidebar.mid": _hex("111a25"),
                "bg.sidebar.end": _hex("0c1420"),
                "bg.dialog": _hex("f8fbfd"),
                "bg.hover.secondary": _hex("eaf1f7"),
                "bg.hover.accent": _hex("ecf2f8"),
                "bg.blueprint.row": _hex("f8fbfd"),
                "bg.memory.tag": _hex("e2ebf3"),
                "bg.memory.hover": _hex("d5e0ec"),
                "text.primary": _hex("1c2a38"),
                "text.secondary": _hex("4e6275"),
                "text.heading": _hex("1f3040"),
                "text.heading.warm": _hex("1f3040"),
                "text.heading.deep": _hex("1a2838"),
                "text.body": _hex("354858"),
                "text.body.alt": _hex("3f5565"),
                "text.body.warm": _hex("324555"),
                "text.muted": _hex("6a7e90"),
                "text.muted.strong": _hex("586c7e"),
                "text.muted.soft": _hex("607485"),
                "text.disabled": _hex("8899a8"),
                "text.artifact": _hex("1f3040"),
                "text.topbar.title": _hex("1c2d3d"),
                "text.topbar.subtitle": _hex("56697a"),
                "text.topbar.meta": _hex("708292"),
                "text.eyebrow": _hex("3a6b9f"),
                "text.brand.gold": _hex("a8c8e2"),
                "text.brand.light": _hex("edf4fa"),
                "text.rail.footer": _hex("dce7f0"),
                "text.chapter.rail": _hex("4f6578"),
                "text.mode.sub": _hex("627585"),
                "text.tab": _hex("5b6e80"),
                "text.tab.alt": _hex("4e6072"),
                "text.tab.project": _hex("556878"),
                "text.tab.hover": _hex("2e4255"),
                "text.stale": _hex("8a9aaa"),
                "text.stale.checked": _hex("758595"),
                "text.routing.sub": _hex("6a7e92"),
                "text.fallback.arrow": _hex("4f6578"),
                "text.fallback.title": _hex("1f3040"),
                "text.fallback.status": _hex("657888"),
                "text.fallback.handle": _hex("90a0ae"),
                "text.fallback.rank.inactive": _hex("8899a8"),
                "text.fallback.name": _hex("253545"),
                "text.fallback.checkbox": _hex("4f6578"),
                "text.guidance": _hex("354858"),
                "text.checkbox": _hex("3a4e60"),
                "text.collapse.nested": _hex("2e4252"),
                "text.quiet": _hex("3f5565"),
                "text.badge.default": _hex("586c7e"),
                "separator": _hex("c8d6e2"),
                "border.default": _hex("7e95a8"),
                "border.muted": _hex("657d92"),
                "border.soft": _hex("b5c8d8"),
                "border.warm": _hex("7590a5"),
                "border.control": _hex("657d92"),
                "role.protagonist": _hex("3a6b9f"),
                "role.deuteragonist": _hex("5a92c2"),
                "role.antagonist": _hex("ad5d5b"),
                "role.supporting": _hex("4f896d"),
                "role.minor": _hex("6a7e90"),
                "relation.bond": _hex("4a7db5"),
                "relation.ally": _hex("4f896d"),
                "relation.tension": _hex("ad5d5b"),
                "relation.identity": _hex("587fa5"),
                "relation.neutral": _hex("7e95a8"),
                "shadow": _hex("263f55"),
                "fade.bg": _hex("e6eef5"),
            }
        ),
    ),
    DesktopTheme(
        theme_id="ink_amethyst",
        label="墨紫",
        description="典雅紫调主题，带有沉静的书写氛围与古典文人气质。",
        token_overrides=MappingProxyType(
            {
                "accent.primary": _hex("6b4c8a"),
                "accent.primary.hover": _hex("7d5ea3"),
                "accent.primary.pressed": _hex("5a3f75"),
                "accent.deep": _hex("4a3366"),
                "accent.dark": _hex("5a3f75"),
                "accent.warm": _hex("7a5499"),
                "accent.light": _hex("9370b3"),
                "accent.muted": _hex("6b4c8a"),
                "accent.badge": _hex("6b4c8a"),
                "accent.rewriting": _hex("4a3366"),
                "accent.fallback": _hex("5e4578"),
                "accent.slider.warm": _hex("c9b3de"),
                "accent.rank.top1": _hex("4a3366"),
                "accent.rank.top2": _hex("6b4c8a"),
                "accent.rank.top3": _hex("8a6aaa"),
                "accent.rank.label": _hex("6b4c8a"),
                "brand.logo.frame": _hex("f5f1fa"),
                "brand.logo.border": _hex("c9b3de"),
                "brand.logo.accent": _hex("6b4c8a"),
                "bg.workspace": _hex("f3eff7"),
                "bg.workspace.mid": _hex("ece6f3"),
                "bg.workspace.end": _hex("e5deed"),
                "bg.surface": _hex("faf8fd"),
                "bg.surface.elevated": _hex("f5f1fa"),
                "bg.input": _hex("faf8fd"),
                "bg.input.soft": _hex("f8f5fb"),
                "bg.panel": _hex("f5f1fa"),
                "bg.panel.muted": _hex("efe9f5"),
                "bg.control": _hex("e8e0f0"),
                "bg.outline.tab": _hex("e8e0f0"),
                "bg.control.hover": _hex("ddd3e8"),
                "bg.control.pressed": _hex("d0c4de"),
                "bg.inset": _hex("eae3f2"),
                "bg.hero.start": _hex("fcfaff"),
                "bg.hero.mid": _hex("f3eff8"),
                "bg.hero.end": _hex("e8e0f0"),
                "bg.sidebar.start": _hex("1e1528"),
                "bg.sidebar.mid": _hex("1a1222"),
                "bg.sidebar.end": _hex("120d18"),
                "bg.dialog": _hex("faf8fd"),
                "bg.hover.secondary": _hex("efe9f5"),
                "bg.hover.accent": _hex("f0eaf6"),
                "bg.blueprint.row": _hex("faf8fd"),
                "bg.memory.tag": _hex("e8e0f0"),
                "bg.memory.hover": _hex("ddd3e8"),
                "text.primary": _hex("251e2e"),
                "text.secondary": _hex("5c5068"),
                "text.heading": _hex("2d2438"),
                "text.heading.warm": _hex("2d2438"),
                "text.heading.deep": _hex("241c30"),
                "text.body": _hex("42374e"),
                "text.body.alt": _hex("4e4058"),
                "text.body.warm": _hex("3e3348"),
                "text.muted": _hex("7a6d88"),
                "text.muted.strong": _hex("685b76"),
                "text.muted.soft": _hex("6e617c"),
                "text.disabled": _hex("978ba5"),
                "text.artifact": _hex("2d2438"),
                "text.topbar.title": _hex("2a2035"),
                "text.topbar.subtitle": _hex("635770"),
                "text.topbar.meta": _hex("7e718d"),
                "text.eyebrow": _hex("6b4c8a"),
                "text.brand.gold": _hex("c9b3de"),
                "text.brand.light": _hex("f3edf9"),
                "text.rail.footer": _hex("e5daf0"),
                "text.chapter.rail": _hex("5e5070"),
                "text.mode.sub": _hex("706280"),
                "text.tab": _hex("6a5c7a"),
                "text.tab.alt": _hex("5c4e6c"),
                "text.tab.project": _hex("635575"),
                "text.tab.hover": _hex("3a2e48"),
                "text.stale": _hex("958aa3"),
                "text.stale.checked": _hex("7f7490"),
                "text.routing.sub": _hex("7a6d8a"),
                "text.fallback.arrow": _hex("5e5070"),
                "text.fallback.title": _hex("2d2438"),
                "text.fallback.status": _hex("736680"),
                "text.fallback.handle": _hex("9c90aa"),
                "text.fallback.rank.inactive": _hex("978ba5"),
                "text.fallback.name": _hex("302540"),
                "text.fallback.checkbox": _hex("5e5070"),
                "text.guidance": _hex("42374e"),
                "text.checkbox": _hex("453855"),
                "text.collapse.nested": _hex("382c45"),
                "text.quiet": _hex("4e4058"),
                "text.badge.default": _hex("685b76"),
                "separator": _hex("d5c9e2"),
                "border.default": _hex("9585a8"),
                "border.muted": _hex("7a6b90"),
                "border.soft": _hex("c4b5d5"),
                "border.warm": _hex("8878a0"),
                "border.control": _hex("7a6b90"),
                "role.protagonist": _hex("6b4c8a"),
                "role.deuteragonist": _hex("9370b3"),
                "role.antagonist": _hex("a85b67"),
                "role.supporting": _hex("5e9176"),
                "role.minor": _hex("7a6d88"),
                "relation.bond": _hex("7d5ea3"),
                "relation.ally": _hex("5e9176"),
                "relation.tension": _hex("a85b67"),
                "relation.identity": _hex("6b779e"),
                "relation.neutral": _hex("9585a8"),
                "shadow": _hex("3b2c4b"),
                "fade.bg": _hex("ece6f3"),
            }
        ),
    ),
    DesktopTheme(
        theme_id="snow_inkstone",
        label="雪砚",
        description="极简冷灰主题，如雪落砚台，克制安静，适合专注写作。",
        token_overrides=MappingProxyType(
            {
                "accent.primary": _hex("4a5568"),
                "accent.primary.hover": _hex("5a6a80"),
                "accent.primary.pressed": _hex("3c4655"),
                "accent.deep": _hex("2d3644"),
                "accent.dark": _hex("3c4655"),
                "accent.warm": _hex("525f75"),
                "accent.light": _hex("71809a"),
                "accent.muted": _hex("48536a"),
                "accent.badge": _hex("4a5568"),
                "accent.rewriting": _hex("2d3644"),
                "accent.fallback": _hex("434e63"),
                "accent.slider.warm": _hex("aab4c8"),
                "accent.rank.top1": _hex("2d3644"),
                "accent.rank.top2": _hex("4a5568"),
                "accent.rank.top3": _hex("6b7a90"),
                "accent.rank.label": _hex("4a5568"),
                "brand.logo.frame": _hex("f4f6f9"),
                "brand.logo.border": _hex("c2c9d6"),
                "brand.logo.accent": _hex("4a5568"),
                "bg.workspace": _hex("eef0f4"),
                "bg.workspace.mid": _hex("e7eaf0"),
                "bg.workspace.end": _hex("dfe2ea"),
                "bg.surface": _hex("fbfbfc"),
                "bg.surface.elevated": _hex("f4f5f8"),
                "bg.input": _hex("fbfbfc"),
                "bg.input.soft": _hex("f7f8fa"),
                "bg.panel": _hex("f3f4f7"),
                "bg.panel.muted": _hex("ebedf2"),
                "bg.control": _hex("e3e5ec"),
                "bg.outline.tab": _hex("e3e5ec"),
                "bg.control.hover": _hex("d4d7e1"),
                "bg.control.pressed": _hex("c5c9d5"),
                "bg.inset": _hex("e8eaef"),
                "bg.hero.start": _hex("fafbfc"),
                "bg.hero.mid": _hex("eff1f6"),
                "bg.hero.end": _hex("e2e5ec"),
                "bg.sidebar.start": _hex("16181d"),
                "bg.sidebar.mid": _hex("131519"),
                "bg.sidebar.end": _hex("0e1013"),
                "bg.dialog": _hex("fbfbfc"),
                "bg.hover.secondary": _hex("e9ebf1"),
                "bg.hover.accent": _hex("ebedf3"),
                "bg.blueprint.row": _hex("fbfbfc"),
                "bg.memory.tag": _hex("e3e5ec"),
                "bg.memory.hover": _hex("d4d7e1"),
                "text.primary": _hex("1e222b"),
                "text.secondary": _hex("4e5563"),
                "text.heading": _hex("222834"),
                "text.heading.warm": _hex("222834"),
                "text.heading.deep": _hex("1b202a"),
                "text.body": _hex("353c49"),
                "text.body.alt": _hex("404853"),
                "text.body.warm": _hex("323947"),
                "text.muted": _hex("6a7280"),
                "text.muted.strong": _hex("59616f"),
                "text.muted.soft": _hex("626a78"),
                "text.disabled": _hex("8f96a3"),
                "text.artifact": _hex("222834"),
                "text.topbar.title": _hex("202531"),
                "text.topbar.subtitle": _hex("525966"),
                "text.topbar.meta": _hex("6d7482"),
                "text.eyebrow": _hex("4a5568"),
                "text.brand.gold": _hex("b0b8c8"),
                "text.brand.light": _hex("ebeef3"),
                "text.rail.footer": _hex("d5dae3"),
                "text.chapter.rail": _hex("4f5664"),
                "text.mode.sub": _hex("616875"),
                "text.tab": _hex("5a616f"),
                "text.tab.alt": _hex("4e5563"),
                "text.tab.project": _hex("555d6a"),
                "text.tab.hover": _hex("2a303c"),
                "text.stale": _hex("8a919e"),
                "text.stale.checked": _hex("757c89"),
                "text.routing.sub": _hex("6a7180"),
                "text.fallback.arrow": _hex("4e5663"),
                "text.fallback.title": _hex("222834"),
                "text.fallback.status": _hex("5c6370"),
                "text.fallback.handle": _hex("9aa1ad"),
                "text.fallback.rank.inactive": _hex("8a919e"),
                "text.fallback.name": _hex("262c38"),
                "text.fallback.checkbox": _hex("4f5764"),
                "text.guidance": _hex("353c49"),
                "text.checkbox": _hex("3d4451"),
                "text.collapse.nested": _hex("303745"),
                "text.quiet": _hex("404853"),
                "text.badge.default": _hex("565e6c"),
                "separator": _hex("cdd1db"),
                "border.default": _hex("8a92a1"),
                "border.muted": _hex("6a7280"),
                "border.soft": _hex("bcc2cf"),
                "border.warm": _hex("7c8494"),
                "border.control": _hex("6a7280"),
                "role.protagonist": _hex("4a5568"),
                "role.deuteragonist": _hex("71809a"),
                "role.antagonist": _hex("a85050"),
                "role.supporting": _hex("4f7a68"),
                "role.minor": _hex("6a7280"),
                "relation.bond": _hex("5a6a80"),
                "relation.ally": _hex("4f7a68"),
                "relation.tension": _hex("8e3939"),
                "relation.identity": _hex("5c7f9e"),
                "relation.neutral": _hex("8a92a1"),
                "shadow": _hex("333a48"),
                "fade.bg": _hex("e7eaf0"),
            }
        ),
    ),
    DesktopTheme(
        theme_id="moonlit_paper",
        label="月白",
        description="淡青月白主题，清润如水，适合柔光下的长时间阅读编辑。",
        token_overrides=MappingProxyType(
            {
                "accent.primary": _hex("3d7a8c"),
                "accent.primary.hover": _hex("4b8ca0"),
                "accent.primary.pressed": _hex("326675"),
                "accent.deep": _hex("244e59"),
                "accent.dark": _hex("326675"),
                "accent.warm": _hex("45808f"),
                "accent.light": _hex("62a0b0"),
                "accent.muted": _hex("3b7686"),
                "accent.badge": _hex("3d7a8c"),
                "accent.rewriting": _hex("244e59"),
                "accent.fallback": _hex("38707f"),
                "accent.slider.warm": _hex("a8d0da"),
                "accent.rank.top1": _hex("244e59"),
                "accent.rank.top2": _hex("3d7a8c"),
                "accent.rank.top3": _hex("5c99a9"),
                "accent.rank.label": _hex("3d7a8c"),
                "brand.logo.frame": _hex("f1f9fa"),
                "brand.logo.border": _hex("b4d8de"),
                "brand.logo.accent": _hex("3d7a8c"),
                "bg.workspace": _hex("ebf4f5"),
                "bg.workspace.mid": _hex("e3eff1"),
                "bg.workspace.end": _hex("dae7ea"),
                "bg.surface": _hex("f9fcfd"),
                "bg.surface.elevated": _hex("f0f8f9"),
                "bg.input": _hex("f9fcfd"),
                "bg.input.soft": _hex("f5fafb"),
                "bg.panel": _hex("eff7f8"),
                "bg.panel.muted": _hex("e7f1f3"),
                "bg.control": _hex("ddeaec"),
                "bg.outline.tab": _hex("ddeaec"),
                "bg.control.hover": _hex("cddfe2"),
                "bg.control.pressed": _hex("bdd3d7"),
                "bg.inset": _hex("e4f0f2"),
                "bg.hero.start": _hex("f6fbfc"),
                "bg.hero.mid": _hex("eaf5f7"),
                "bg.hero.end": _hex("dcebee"),
                "bg.sidebar.start": _hex("10222a"),
                "bg.sidebar.mid": _hex("0d1e24"),
                "bg.sidebar.end": _hex("0a161b"),
                "bg.dialog": _hex("f9fcfd"),
                "bg.hover.secondary": _hex("e6f1f3"),
                "bg.hover.accent": _hex("e6f3f5"),
                "bg.blueprint.row": _hex("f9fcfd"),
                "bg.memory.tag": _hex("ddeaec"),
                "bg.memory.hover": _hex("cddfe2"),
                "text.primary": _hex("17292e"),
                "text.secondary": _hex("456065"),
                "text.heading": _hex("1a3036"),
                "text.heading.warm": _hex("1a3036"),
                "text.heading.deep": _hex("152529"),
                "text.body": _hex("2e474d"),
                "text.body.alt": _hex("385359"),
                "text.body.warm": _hex("2c444a"),
                "text.muted": _hex("5f7a7f"),
                "text.muted.strong": _hex("506a6f"),
                "text.muted.soft": _hex("577277"),
                "text.disabled": _hex("84a0a5"),
                "text.artifact": _hex("1a3036"),
                "text.topbar.title": _hex("182e34"),
                "text.topbar.subtitle": _hex("496469"),
                "text.topbar.meta": _hex("648085"),
                "text.eyebrow": _hex("3d7a8c"),
                "text.brand.gold": _hex("a4ccd4"),
                "text.brand.light": _hex("e8f5f7"),
                "text.rail.footer": _hex("c6e0e5"),
                "text.chapter.rail": _hex("476367"),
                "text.mode.sub": _hex("5a7378"),
                "text.tab": _hex("526c70"),
                "text.tab.alt": _hex("476166"),
                "text.tab.project": _hex("4d666a"),
                "text.tab.hover": _hex("203a40"),
                "text.stale": _hex("7e989d"),
                "text.stale.checked": _hex("6a8489"),
                "text.routing.sub": _hex("60797e"),
                "text.fallback.arrow": _hex("4c676c"),
                "text.fallback.title": _hex("1a3036"),
                "text.fallback.status": _hex("557075"),
                "text.fallback.handle": _hex("8fa9ad"),
                "text.fallback.rank.inactive": _hex("7e989d"),
                "text.fallback.name": _hex("1e343a"),
                "text.fallback.checkbox": _hex("4b656a"),
                "text.guidance": _hex("2e474d"),
                "text.checkbox": _hex("355057"),
                "text.collapse.nested": _hex("294349"),
                "text.quiet": _hex("385359"),
                "text.badge.default": _hex("526e73"),
                "separator": _hex("bfd9dd"),
                "border.default": _hex("7ba0a7"),
                "border.muted": _hex("5d828a"),
                "border.soft": _hex("a9cdd2"),
                "border.warm": _hex("6f949c"),
                "border.control": _hex("5d828a"),
                "role.protagonist": _hex("3d7a8c"),
                "role.deuteragonist": _hex("62a0b0"),
                "role.antagonist": _hex("a85050"),
                "role.supporting": _hex("4c8a70"),
                "role.minor": _hex("5f7a7f"),
                "relation.bond": _hex("4b8ca0"),
                "relation.ally": _hex("4c8a70"),
                "relation.tension": _hex("8e3939"),
                "relation.identity": _hex("5c7f9e"),
                "relation.neutral": _hex("7ba0a7"),
                "shadow": _hex("1d4048"),
                "fade.bg": _hex("e3eff1"),
            }
        ),
    ),
    DesktopTheme(
        theme_id="twilight_ink",
        label="暮夜",
        description="深色夜间主题，低对比度护眼，适合夜间沉浸式写作。",
        token_overrides=MappingProxyType(
            {
                "accent.primary": _hex("c2855a"),
                "accent.primary.hover": _hex("d4956a"),
                "accent.primary.pressed": _hex("b07548"),
                "accent.deep": _hex("9a6840"),
                "accent.dark": _hex("b07548"),
                "accent.warm": _hex("c98a55"),
                "accent.light": _hex("d4a070"),
                "accent.muted": _hex("a87850"),
                "accent.badge": _hex("c2855a"),
                "accent.rewriting": _hex("9a6840"),
                "accent.fallback": _hex("a07048"),
                "accent.slider.warm": _hex("d4a878"),
                "accent.rank.top1": _hex("9a6840"),
                "accent.rank.top2": _hex("c2855a"),
                "accent.rank.top3": _hex("d4a070"),
                "accent.rank.label": _hex("c2855a"),
                "brand.logo.frame": _hex("2a2420"),
                "brand.logo.border": _hex("6a5a48"),
                "brand.logo.accent": _hex("c2855a"),
                "bg.workspace": _hex("1a1816"),
                "bg.workspace.mid": _hex("1e1c1a"),
                "bg.workspace.end": _hex("22201e"),
                "bg.surface": _hex("252320"),
                "bg.surface.elevated": _hex("2c2a27"),
                "bg.input": _hex("2c2a27"),
                "bg.input.soft": _hex("282624"),
                "bg.panel": _hex("282624"),
                "bg.panel.muted": _hex("232120"),
                "bg.control": _hex("333130"),
                "bg.outline.tab": _hex("333130"),
                "bg.control.hover": _hex("3e3c3a"),
                "bg.control.pressed": _hex("454340"),
                "bg.inset": _hex("201e1c"),
                "bg.hero.start": _hex("252320"),
                "bg.hero.mid": _hex("201e1c"),
                "bg.hero.end": _hex("1a1816"),
                "bg.sidebar.start": _hex("141210"),
                "bg.sidebar.mid": _hex("121010"),
                "bg.sidebar.end": _hex("0e0c0a"),
                "bg.dialog": _hex("282624"),
                "bg.hover.secondary": _hex("333130"),
                "bg.hover.accent": _hex("353028"),
                "bg.blueprint.row": _hex("282624"),
                "bg.memory.tag": _hex("333130"),
                "bg.memory.hover": _hex("3e3c3a"),
                "text.primary": _hex("e0d8ce"),
                "text.secondary": _hex("a89888"),
                "text.heading": _hex("e5ddd2"),
                "text.heading.warm": _hex("e5ddd2"),
                "text.heading.deep": _hex("ebe3d8"),
                "text.body": _hex("c8bfb2"),
                "text.body.alt": _hex("bab0a2"),
                "text.body.warm": _hex("d0c5b8"),
                "text.muted": _hex("8a7e70"),
                "text.muted.strong": _hex("9a8e80"),
                "text.muted.soft": _hex("908478"),
                "text.disabled": _hex("6a6055"),
                "text.artifact": _hex("ddd5ca"),
                "text.topbar.title": _hex("e0d8ce"),
                "text.topbar.subtitle": _hex("a89888"),
                "text.topbar.meta": _hex("8a7e70"),
                "text.eyebrow": _hex("c2855a"),
                "text.brand.gold": _hex("c9a878"),
                "text.brand.light": _hex("e8ddd0"),
                "text.rail.footer": _hex("a89888"),
                "text.chapter.rail": _hex("908478"),
                "text.mode.sub": _hex("8a7e70"),
                "text.tab": _hex("a89888"),
                "text.tab.alt": _hex("9a8e80"),
                "text.tab.project": _hex("a08e80"),
                "text.tab.hover": _hex("d0c5b8"),
                "text.stale": _hex("6a6055"),
                "text.stale.checked": _hex("7a7068"),
                "text.routing.sub": _hex("8a7e70"),
                "text.fallback.arrow": _hex("a89888"),
                "text.fallback.title": _hex("e5ddd2"),
                "text.fallback.status": _hex("6a6055"),
                "text.fallback.handle": _hex("6a6055"),
                "text.fallback.rank.inactive": _hex("6a6055"),
                "text.fallback.name": _hex("d0c5b8"),
                "text.fallback.checkbox": _hex("bab0a2"),
                "text.guidance": _hex("c8bfb2"),
                "text.checkbox": _hex("bab0a2"),
                "text.collapse.nested": _hex("c0b5a8"),
                "text.quiet": _hex("bab0a2"),
                "text.badge.default": _hex("9a8e80"),
                "separator": _hex("3e3a35"),
                "border.default": _hex("5a5248"),
                "border.muted": _hex("4a4238"),
                "border.soft": _hex("5e5548"),
                "border.warm": _hex("6a5a48"),
                "border.control": _hex("4a4238"),
                "role.protagonist": _hex("c2855a"),
                "role.deuteragonist": _hex("d4a070"),
                "role.antagonist": _hex("d16a64"),
                "role.supporting": _hex("7ebd91"),
                "role.minor": _hex("a89888"),
                "relation.bond": _hex("d4956a"),
                "relation.ally": _hex("7ebd91"),
                "relation.tension": _hex("d16a64"),
                "relation.identity": _hex("86a4c4"),
                "relation.neutral": _hex("6a5a48"),
                "shadow": _hex("0c0a08"),
                "fade.bg": _hex("1e1c1a"),
            }
        ),
    ),
    DesktopTheme(
        theme_id="indigo_night",
        label="黛蓝",
        description="深蓝暗夜主题，如远山含黛，低亮度护眼，适合夜间写作。",
        token_overrides=MappingProxyType(
            {
                "accent.primary": _hex("6a8ac4"),
                "accent.primary.hover": _hex("7c9ad2"),
                "accent.primary.pressed": _hex("5878b0"),
                "accent.deep": _hex("44608e"),
                "accent.dark": _hex("5878b0"),
                "accent.warm": _hex("6e8ec6"),
                "accent.light": _hex("8ca8d8"),
                "accent.muted": _hex("6484ba"),
                "accent.badge": _hex("6a8ac4"),
                "accent.rewriting": _hex("44608e"),
                "accent.fallback": _hex("6080b8"),
                "accent.slider.warm": _hex("9ab2dc"),
                "accent.rank.top1": _hex("44608e"),
                "accent.rank.top2": _hex("6a8ac4"),
                "accent.rank.top3": _hex("8ca8d8"),
                "accent.rank.label": _hex("6a8ac4"),
                "brand.logo.frame": _hex("1a2030"),
                "brand.logo.border": _hex("3c4c6e"),
                "brand.logo.accent": _hex("6a8ac4"),
                "bg.workspace": _hex("12151e"),
                "bg.workspace.mid": _hex("151924"),
                "bg.workspace.end": _hex("191e2a"),
                "bg.surface": _hex("1a1f2c"),
                "bg.surface.elevated": _hex("222836"),
                "bg.input": _hex("222836"),
                "bg.input.soft": _hex("1e2430"),
                "bg.panel": _hex("1e2432"),
                "bg.panel.muted": _hex("191e2a"),
                "bg.control": _hex("262d3e"),
                "bg.outline.tab": _hex("262d3e"),
                "bg.control.hover": _hex("30384c"),
                "bg.control.pressed": _hex("384158"),
                "bg.inset": _hex("161a26"),
                "bg.hero.start": _hex("1a1f2c"),
                "bg.hero.mid": _hex("161a26"),
                "bg.hero.end": _hex("12151e"),
                "bg.sidebar.start": _hex("0c0f16"),
                "bg.sidebar.mid": _hex("0a0d13"),
                "bg.sidebar.end": _hex("07090e"),
                "bg.dialog": _hex("1e2432"),
                "bg.hover.secondary": _hex("262d3e"),
                "bg.hover.accent": _hex("242c3e"),
                "bg.blueprint.row": _hex("1e2432"),
                "bg.memory.tag": _hex("262d3e"),
                "bg.memory.hover": _hex("30384c"),
                "text.primary": _hex("d0d8e8"),
                "text.secondary": _hex("98a4bc"),
                "text.heading": _hex("d6deec"),
                "text.heading.warm": _hex("d6deec"),
                "text.heading.deep": _hex("e0e6f2"),
                "text.body": _hex("b8c0d2"),
                "text.body.alt": _hex("aab2c6"),
                "text.body.warm": _hex("c2cada"),
                "text.muted": _hex("7c88a0"),
                "text.muted.strong": _hex("8c98ae"),
                "text.muted.soft": _hex("828ea4"),
                "text.disabled": _hex("5a6478"),
                "text.artifact": _hex("ced6e6"),
                "text.topbar.title": _hex("d0d8e8"),
                "text.topbar.subtitle": _hex("98a4bc"),
                "text.topbar.meta": _hex("7c88a0"),
                "text.eyebrow": _hex("6a8ac4"),
                "text.brand.gold": _hex("9eb2d8"),
                "text.brand.light": _hex("d8e0f0"),
                "text.rail.footer": _hex("98a4bc"),
                "text.chapter.rail": _hex("828ea4"),
                "text.mode.sub": _hex("7c88a0"),
                "text.tab": _hex("98a4bc"),
                "text.tab.alt": _hex("8c98ae"),
                "text.tab.project": _hex("929eb2"),
                "text.tab.hover": _hex("c2cada"),
                "text.stale": _hex("5a6478"),
                "text.stale.checked": _hex("6c7688"),
                "text.routing.sub": _hex("7c88a0"),
                "text.fallback.arrow": _hex("98a4bc"),
                "text.fallback.title": _hex("d6deec"),
                "text.fallback.status": _hex("5a6478"),
                "text.fallback.handle": _hex("5a6478"),
                "text.fallback.rank.inactive": _hex("5a6478"),
                "text.fallback.name": _hex("c2cada"),
                "text.fallback.checkbox": _hex("aab2c6"),
                "text.guidance": _hex("b8c0d2"),
                "text.checkbox": _hex("aab2c6"),
                "text.collapse.nested": _hex("b0bacc"),
                "text.quiet": _hex("aab2c6"),
                "text.badge.default": _hex("8c98ae"),
                "separator": _hex("2e3546"),
                "border.default": _hex("465272"),
                "border.muted": _hex("38425c"),
                "border.soft": _hex("4c5878"),
                "border.warm": _hex("505c7e"),
                "border.control": _hex("38425c"),
                "role.protagonist": _hex("6a8ac4"),
                "role.deuteragonist": _hex("8ca8d8"),
                "role.antagonist": _hex("c97070"),
                "role.supporting": _hex("6aa888"),
                "role.minor": _hex("98a4bc"),
                "relation.bond": _hex("7c9ad2"),
                "relation.ally": _hex("6aa888"),
                "relation.tension": _hex("d16a64"),
                "relation.identity": _hex("88a0c8"),
                "relation.neutral": _hex("465272"),
                "shadow": _hex("05070a"),
                "fade.bg": _hex("151924"),
            }
        ),
    ),
    DesktopTheme(
        theme_id="pine_soot",
        label="松烟",
        description="墨绿暗色主题，取松烟墨的沉静质感，适合深夜沉浸写作。",
        token_overrides=MappingProxyType(
            {
                "accent.primary": _hex("86a860"),
                "accent.primary.hover": _hex("98b872"),
                "accent.primary.pressed": _hex("749450"),
                "accent.deep": _hex("5e7c40"),
                "accent.dark": _hex("749450"),
                "accent.warm": _hex("8aa860"),
                "accent.light": _hex("a4c080"),
                "accent.muted": _hex("7a9a58"),
                "accent.badge": _hex("86a860"),
                "accent.rewriting": _hex("5e7c40"),
                "accent.fallback": _hex("7a9c54"),
                "accent.slider.warm": _hex("b8cc90"),
                "accent.rank.top1": _hex("5e7c40"),
                "accent.rank.top2": _hex("86a860"),
                "accent.rank.top3": _hex("a4c080"),
                "accent.rank.label": _hex("86a860"),
                "brand.logo.frame": _hex("1f2419"),
                "brand.logo.border": _hex("4a5a38"),
                "brand.logo.accent": _hex("86a860"),
                "bg.workspace": _hex("171a12"),
                "bg.workspace.mid": _hex("1a1e15"),
                "bg.workspace.end": _hex("1e2219"),
                "bg.surface": _hex("20241a"),
                "bg.surface.elevated": _hex("272c20"),
                "bg.input": _hex("272c20"),
                "bg.input.soft": _hex("23281c"),
                "bg.panel": _hex("242920"),
                "bg.panel.muted": _hex("1f241b"),
                "bg.control": _hex("2e3428"),
                "bg.outline.tab": _hex("2e3428"),
                "bg.control.hover": _hex("394031"),
                "bg.control.pressed": _hex("424a38"),
                "bg.inset": _hex("1b1f16"),
                "bg.hero.start": _hex("20241a"),
                "bg.hero.mid": _hex("1b1f16"),
                "bg.hero.end": _hex("161a12"),
                "bg.sidebar.start": _hex("10130c"),
                "bg.sidebar.mid": _hex("0e110a"),
                "bg.sidebar.end": _hex("0a0d07"),
                "bg.dialog": _hex("242920"),
                "bg.hover.secondary": _hex("2e3428"),
                "bg.hover.accent": _hex("2c3324"),
                "bg.blueprint.row": _hex("242920"),
                "bg.memory.tag": _hex("2e3428"),
                "bg.memory.hover": _hex("394031"),
                "text.primary": _hex("d8dcc8"),
                "text.secondary": _hex("a0a890"),
                "text.heading": _hex("dde2cc"),
                "text.heading.warm": _hex("dde2cc"),
                "text.heading.deep": _hex("e4e8d4"),
                "text.body": _hex("c0c6b0"),
                "text.body.alt": _hex("b2b8a4"),
                "text.body.warm": _hex("c8ccb8"),
                "text.muted": _hex("848a76"),
                "text.muted.strong": _hex("949a86"),
                "text.muted.soft": _hex("8a907c"),
                "text.disabled": _hex("606652"),
                "text.artifact": _hex("d5dac4"),
                "text.topbar.title": _hex("d8dcc8"),
                "text.topbar.subtitle": _hex("a0a890"),
                "text.topbar.meta": _hex("848a76"),
                "text.eyebrow": _hex("86a860"),
                "text.brand.gold": _hex("b0c084"),
                "text.brand.light": _hex("dfe4cc"),
                "text.rail.footer": _hex("a0a890"),
                "text.chapter.rail": _hex("8a907c"),
                "text.mode.sub": _hex("848a76"),
                "text.tab": _hex("a0a890"),
                "text.tab.alt": _hex("949a86"),
                "text.tab.project": _hex("9aa08a"),
                "text.tab.hover": _hex("c8ccb8"),
                "text.stale": _hex("606652"),
                "text.stale.checked": _hex("727862"),
                "text.routing.sub": _hex("848a76"),
                "text.fallback.arrow": _hex("a0a890"),
                "text.fallback.title": _hex("dde2cc"),
                "text.fallback.status": _hex("606652"),
                "text.fallback.handle": _hex("606652"),
                "text.fallback.rank.inactive": _hex("606652"),
                "text.fallback.name": _hex("c8ccb8"),
                "text.fallback.checkbox": _hex("b2b8a4"),
                "text.guidance": _hex("c0c6b0"),
                "text.checkbox": _hex("b2b8a4"),
                "text.collapse.nested": _hex("b8bfa8"),
                "text.quiet": _hex("b2b8a4"),
                "text.badge.default": _hex("949a86"),
                "separator": _hex("363c2c"),
                "border.default": _hex("525c42"),
                "border.muted": _hex("424a34"),
                "border.soft": _hex("57604a"),
                "border.warm": _hex("5e6848"),
                "border.control": _hex("424a34"),
                "role.protagonist": _hex("86a860"),
                "role.deuteragonist": _hex("a4c080"),
                "role.antagonist": _hex("c96a5e"),
                "role.supporting": _hex("6aa884"),
                "role.minor": _hex("a0a890"),
                "relation.bond": _hex("98b872"),
                "relation.ally": _hex("6aa884"),
                "relation.tension": _hex("d16a64"),
                "relation.identity": _hex("84a0bc"),
                "relation.neutral": _hex("525c42"),
                "shadow": _hex("080a05"),
                "fade.bg": _hex("1a1e15"),
            }
        ),
    ),
)

DESKTOP_THEMES: Mapping[str, DesktopTheme] = MappingProxyType(
    {theme.theme_id: theme for theme in _THEME_LIST}
)


def normalize_theme_id(theme_id: str | None) -> str:
    """Return a known theme id, falling back to the default."""

    candidate = str(theme_id or "").strip()
    if candidate in DESKTOP_THEMES:
        return candidate
    return DEFAULT_DESKTOP_THEME_ID


def get_desktop_theme(theme_id: str | None) -> DesktopTheme:
    """Return a theme spec by id, falling back to the default."""

    return DESKTOP_THEMES[normalize_theme_id(theme_id)]


def desktop_theme_choices() -> tuple[tuple[str, str], ...]:
    """Return ``(theme_id, label)`` choices for settings controls."""

    return tuple((theme.theme_id, theme.label) for theme in _THEME_LIST)


def desktop_theme_token_overrides(theme_id: str | None) -> dict[str, str]:
    """Return a mutable token override dict for *theme_id*."""

    theme = get_desktop_theme(theme_id)
    return dict(theme.token_overrides)


def list_desktop_themes() -> tuple[DesktopTheme, ...]:
    """Return all desktop themes in display order."""

    return _THEME_LIST
