"""Backward-compat shim for novel_forge.desktop.pages.document_renderer.reports.

The original 4244-line document_renderer_reports.py was decomposed into a
subpackage in the M3.4 refactor. This shim keeps existing imports of the
form 'from novel_forge.desktop.pages.document_renderer_reports import X'
working. Names relocated to dedicated submodules during the P2 migration
(spec, eval_report, generic_report, humanize) are imported from their
canonical submodules so their definitions stay authoritative; everything
else still lives in ``reports/__init__.py``.
"""

from __future__ import annotations

from novel_forge.desktop.pages.document_renderer.reports import (  # noqa: F401  # noqa: F401, F811
    _BIBLE_FIELD_LABELS,
    _CAUSAL_ISSUE_TYPE_LABELS,
    _CONFLICT_LEVEL_STYLE,
    _COVERAGE_STRENGTH_LABELS,
    _CREATIVE_CHARACTER_IMPORTANCE_LABELS,
    _DEVIATION_TYPE_LABELS,
    _ENTITY_ACTION_LABELS,
    _ENTITY_TYPE_LABELS,
    _EVAL_DIM_LABELS,
    _EXPRESSION_CHANNEL_LABELS,
    _EXPRESSION_LEVEL_LABELS,
    _GENERIC_KEY_LABELS,
    _GENERIC_META_KEYS,
    _GENRE_LABELS,
    _GUARD_DECISION_LABELS,
    _HUMANIZE_SEVERITY_LABELS,
    _HUMANIZE_SEVERITY_ORDER,
    _INIT_STAGE_LABELS,
    _ISSUE_TYPE_LABELS,
    _KB_BOUNDARY_REASON_LABELS,
    _KB_KNOWLEDGE_TYPE_LABELS,
    _KB_VERDICT_LABELS,
    _KB_VISIBILITY_LABELS,
    _NARRATIVE_PHASE_LABELS,
    _REWRITE_SCOPE_LABELS,
    _RISK_LEVEL_STYLE,
    _SETUP_PHASE_LABELS,
    _SETUP_STRENGTH_LABELS,
    _SEVERITY_STYLE,
    _SEVERITY_STYLE_EXTENDED,
    _STAGE_VISIBILITY_HELP,
    _STAGE_VISIBILITY_LABELS,
    _STAGE_VISIBILITY_ORDER,
    _STAGE_VISIBILITY_POLICIES,
    _SUSPENSE_TYPE_LABELS,
    _TONE_LABELS,
    _TRANSITION_MODE_LABELS,
    _URGENCY_STYLE,
    _collect_thread_chapter_numbers,
    _compact_items,
    _creative_character_status,
    _eval_dim_label,
    _explicit_thread_chapter_range,
    _expression_channel_label,
    _expression_guidance_payload,
    _expression_level_tag,
    _expression_record_meta,
    _extract_positive_ints,
    _first_positive_int,
    _format_thread_chapter_range,
    _humanize_bool_label,
    _humanize_category_distribution,
    _humanize_metric,
    _humanize_score_label,
    _humanize_severity_tone,
    _parse_stringified_dict,
    _render_llm_narrative_contract_sections,
    _report_list,
    _report_text,
    _safe_float,
    _safe_int,
    _severity_tone,
    _stage_visibility_count,
    _stage_visibility_entries,
    _stage_visibility_metric_cell,
    _stage_visibility_policy_text,
    _state_confidence,
    _state_count_by,
    _state_dict,
    _state_dict_items,
    _state_evidence_cards,
    _state_list,
    _state_severity_label,
    _state_tag,
    _state_update_cards,
    _state_verdict_label,
    _tag,
    _truthy_report_flag,
    generic_key_label,
    render_alignment_report,
    render_alignment_report_body_html,
    render_bridge,
    render_canon_state,
    render_causal_report,
    render_causal_report_body_html,
    render_chapter_contracts,
    render_chapter_plan,
    render_continuity_report,
    render_continuity_report_body_html,
    render_creative_report,
    render_expression_repetition_report,
    render_guard_report,
    render_guard_report_body_html,
    render_init_editorial_readiness_report,
    render_init_readiness_report,
    render_knowledge_boundary_report,
    render_llm_narrative_contract,
    render_narrative_contract,
    render_reading_power_window_report,
    render_repair_plan_report,
    render_research_dossier_report,
    render_stage_visibility_report,
    render_state_adjudication_index,
    render_state_adjudication_report,
    render_state_evidence_snapshot,
    render_state_ledger,
    render_state_pending_queue,
    render_story_state_projection,
    render_web_research_report,
)
from novel_forge.desktop.pages.document_renderer.reports.eval_report import (  # noqa: F401
    render_eval_report,
    render_eval_report_body_html,
)
from novel_forge.desktop.pages.document_renderer.reports.generic_report import (  # noqa: F401
    _generic_is_empty,
    _generic_is_scalar,
    _generic_item_title,
    _generic_list_items,
    _generic_metric,
    _generic_render_dict,
    _generic_render_value,
    _generic_scalar_html,
    _generic_tag,
    render_generic_report,
    render_generic_report_body_html,
)
from novel_forge.desktop.pages.document_renderer.reports.humanize import (  # noqa: F401
    render_humanize_report,
    render_humanize_report_body_html,
)
from novel_forge.desktop.pages.document_renderer.reports.spec import (  # noqa: F401
    render_spec,
    render_story_bible,
)
